### ISSUE TITLE
Select component didn't start animation when start closing

### ISSUE THREAD

**Issue by cheolhow** [radix-ui/primitives#2069] opened 2023-04-04 16:28 UTC
### Current Behavior

Select component didn't start closing animation

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/react-radix-dropdown-menu-animation-forked-nc8k0m?file=/src/App.js)

### Suggested solution

The Select's data-state attribute seems to attach fine when open, but not when closed.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| @radix-ui/react-select |         |   1.2.1      |
| React            | n/a     |   17.0.2      |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by joaom00** [comment] 2023-04-04 17:24
Exit animations are not yet supported in `Select`.

Duplicate of https://github.com/radix-ui/primitives/issues/1893

**Closed** 2023-04-13 14:41 UTC
Labels: Resolution: Duplicate, Package: react/select
