### ISSUE TITLE
[ContextMenu][DropdownMenu] Hidden scrollbars appear when Menu/ContextMenu is active 

### ISSUE THREAD

**Issue by jordn** [radix-ui/primitives#1272] opened 2022-03-25 12:26 UTC
### Current Behavior
I've tried adding a context menu and a floating menu, and both times there\s a weird behaviour that when they're active, the scrollbars within the app all appear (I'm on a mac and they're hidden by default until you scroll)

![scroll](https://user-images.githubusercontent.com/1463197/160119935-bdccb0ec-2bc3-41e8-8690-6e9781424bb5.gif)

### Expected behavior
I wouldn't expect this to have any impact on the scrollbars. I'd like the background to be inactive, and unscrollable ideally.

### Reproducible example
... let me come back to you, if this isn't a known issue/easy fix.

### Your environment

```
    "@radix-ui/colors": "^0.1.8",
    "@radix-ui/react-dropdown-menu": "^0.1.6",
    "@radix-ui/react-icons": "^1.1.0",
    "@radix-ui/react-popover": "^0.1.6",
    "@radix-ui/react-slider": "^0.1.4",
    "@radix-ui/react-tooltip": "^0.1.6",
    "react": "17.0.2",
```

on Chrome 99.0.4844.51, MacOs 12.3

**Comment by jordn** [comment] 2022-03-28 14:06
The cause, AFAICT is that the body gets a `pointer-events: none` style, and on mac (with default scrollbar behaviour) this shows the scrollbars of all overlays.

<img width="486" alt="Screenshot 2022-03-28 at 15 03 33" src="https://user-images.githubusercontent.com/1463197/160415315-9a78b288-c3a4-4e41-8df7-a62c1b9f6588.png">




p.s. So grateful to your team for building this! Such attention to detail and a huge value to the community. 🙏

**Comment by benoitgrelard** [comment] 2022-04-01 08:01
That is quite strange!
I cannot reproduce it on my end, do you have a sandbox where you can reproduce this?

**Comment by andy-hook** [comment] 2022-04-01 08:31
We had one report of this in the past which I did briefly look at https://discord.com/channels/752614004387610674/908788354508808242

As @jordn says, applying `pointer-events: none` to a parent element will show scroll bars regardless of the MacOS scrollbar visibility setting.

As it seems like an OS level issue and I'm not sure how we'd solve for it without using a different method to manage inert state / pointer-events.

Easiest way I found to repro is to set "Show scroll bars" to "When scrolling" and toggle the checkbox [in this sandbox](https://codesandbox.io/s/eager-https-gonjd?file=/src/App.tsx). You might need to restart you browser / machine for the scroll setting to take.

**Comment by benoitgrelard** [comment] 2022-04-01 09:14
Ah yeah I can see it on that sandbox.
I'm really curious why i've never seen in the wild before though, given that the "When scrolling" is the setting I always use.

**Comment by benoitgrelard** [comment] 2022-04-06 10:40
This isn't something we can fix unfortunately so we'll have to close the issue.

**Closed by benoitgrelard** 2022-04-06 10:40 UTC

**Comment by jordn** [comment] 2022-04-06 11:06
(The sandbox mentioned above https://codesandbox.io/s/eager-https-gonjd?file=/src/App.tsx )

Thanks for the responses but I disagree that you can't do anything about it. 

I think this is caused by the use of `react-remove-scroll` (quick research, i might be mistaken) which disabled background clicking and scroll in this way. I don't think it's affected the Modulz websites because you're using ScrollAreas with custom scrollbars in the places I've seen which aren't affected. So maybe this seems lower impact to the team than we think it is.

However, if you look at how MUI does context menu (https://stackblitz.com/run?file=demo.js) they put `overflow: hidden` on the body and a full width/height overlay panel below the popover to disable clicking on other elements. That feels like that could be a solution here too.

**Comment by benoitgrelard** [comment] 2022-04-06 12:09
The provided sandbox shows that it isn't linked to `react-remove-scroll` but rather `pointer-events`.

**Comment by jordn** [comment] 2022-04-07 06:43
Sorry wasn’t clear. That was the same link as Andy posted above. I didn’t
see the link and I thought it was helpful to have it here rather buried in
discord.

You can ignore that and the point still stands

Jordan
Linkedin <https://linkedin.com/in/jordanburgess> / (+44) 7919 921456
WhatsApp
<https://api.whatsapp.com/send?phone=+447919921456&text=hey%20%F0%9F%91%8B&source=signature>
or
schedule a Zoom <https://calendly.com/jordanburgess/>

**Comment by dsdeur** [comment] 2022-04-14 22:01
I ran into the same issue. You can work around it with an overlay that is toggled from  `onOpenChange` to block the events.   Quick demo:
- [Normal situation, showing scrollbars](https://codesandbox.io/s/objective-smoke-ppyjcs?file=/App.js:2974-3261)
- [With workaround](https://codesandbox.io/s/nice-mclean-ilf2zh?file=/App.js:2974-3719)

(`overflow: hidden` is already applied to the body so no extra handling needed)

**Comment by jordn** [comment] 2022-04-15 05:55
Nice thanks! That's definitely better. Does this work as you'd want on windows/macs-with different settings?

For me, mac with "show scrollbars' this causes the scrollbar area to disappear completely. Which is also a little bit jarring.
![fix](https://user-images.githubusercontent.com/1463197/163527462-9314bf2e-0423-45a1-bd28-661bc98b6e4b.gif)

**Comment by dsdeur** [comment] 2022-04-15 07:09
I have not tested windows (yet). On mac it looks better; it's pretty much the same for always visible scrollbars, much better with auto hiding.

The body scrollbar disappearing is because of the `overflow: hidden` on the body which removes the scroll completely. You could override that as well ([see](https://codesandbox.io/s/blissful-leaf-e6b64y?file=/App.js:3344-3400)) but then the scrollbar stays available as the blocking div can't cover the body scrollbar. 

MUI has this same issue btw, I'm not sure there is a perfect solution. Maybe custom scrollbars could give more options, or depending on the app you could not use body scroll, but that could create other issues. For my use case the overlay is sufficient.

**Comment by tinybrain** [comment] 2022-05-25 06:33
Love this menu... but I really want to keep body scrolling.

This seems to also do the trick.

```css
body {
  width: 100vw;
  overflow-x: hidden;
  padding-right: calc(0px - var(--removed-body-scroll-bar-size)) !important;
}
```

**Comment by benoitgrelard** [comment] 2022-05-25 07:39
@tinybrain I believe this is a different thing. If what you want is to keep body scrolling, what you want is to make your menu non-modal (ie. enable actions behind it) by passing the `modal={false}` prop to the `Root` part.

**Comment by BenTarman** [comment] 2022-06-13 10:06
@benoitgrelard thanks for that! Was overriding the scrollbar/padding in my apps global css file to fix the scrollbar content jumping but just needed to set modal to false.

Kind of feel that for dropdownmenu this should be defaulted to false.

**Comment by adam-lynch** [comment] 2022-07-21 13:21
`modal={false}` is especially useful for browser extensions

**Comment by sandgraham** [comment] 2022-12-16 01:43
I have a small workaround for those who don't want to use `modal={true}` or overwrite the `pointer-events` styling used by radix-ui for inert behavior:

https://stackblitz.com/edit/react-y9idvr?file=src/App.js

Essentially, set `::-webkit-scrollbar` to `display: none` for anything outside of our dropdown. The macOS setting that causes the original issue in Chrome creates scrollbars that overlay content rather than the typical scrollbar which pushes content aside. We can use this quirk to safely apply our "hide scrollbar" styles.

In the example provided above I use two classes to manage the scrollbar styles: `remove-scrollbars` which hides scrollbars on itself and its descendants and `keep-scrollbars` which keeps default scrollbars for itself and descendants. When opening a dropdown we detect the client's scrollbar width. If it is 0 we can assume it is safe to hide scrollbars and apply the `remove-scrollbars` class to the body element. We apply the `keep-scrollbars` class to any part of the app that is still scrollable - which in practice should just be our modal components so this can be static.

I'm not sure if this technique can be made safe for inclusion in Radix UI itself, but for a small amount of code it can help hide this issue in your app (at least until Chrome [fixes it](https://bugs.chromium.org/p/chromium/issues/detail?id=1280013)).

**Comment by websiddu** [comment] 2023-01-16 03:29
It's bit hacky but you can do something like this, 

```
body:has(> [data-state="open"]),
body:has(> [data-radix-popper-content-wrapper]) {
  ::-webkit-scrollbar {
    display: none;
  }
}
```

**Comment by ligaz** [comment] 2023-11-09 15:37
We just fixed a similar issue on our side. It turned out that we have applied an overflow hidden on the `html` root element. Leaving it just for the `body` fixed it for us:
```diff
-  html,
   body {
     @apply overflow-x-hidden;
  }
```

_[`overflow-x-hidden`](https://tailwindcss.com/docs/overflow) is a Tailwind directive._

**Comment by smultar** [comment] 2024-01-01 07:20
> Love this menu... but I really want to keep body scrolling.
> 
> This seems to also do the trick.
> 
> ```css
> body {
>   width: 100vw;
>   overflow-x: hidden;
>   padding-right: calc(0 - var(--removed-body-scroll-bar-size)) !important;
> }
> ```

This worked for me and I truly appreciate you for this.

**Comment by odilonferreira** [comment] 2024-04-26 20:19
> We just fixed a similar issue on our side. It turned out that we have applied an overflow hidden on the `html` root element. Leaving it just for the `body` fixed it for us:
> 
> ```diff
> -  html,
>    body {
>      @apply overflow-x-hidden;
>   }
> ```
> 
> _[`overflow-x-hidden`](https://tailwindcss.com/docs/overflow) is a Tailwind directive._

This worked for me, using tailwind. Thank you for that!

**Comment by daross-wizehire** [comment] 2025-02-27 16:54
I was able to solve this by setting `box-sizing: content-box;` on the `body`. That makes it so `react-remove-scroll-bar` 's changes to the margin and padding don't affect the content within. Might not work for everyone, since that could cause other layout issues, but it worked for me.
