### ISSUE TITLE
Select inside Dialog: "Uncaught InternalError: too much recursion"

### ISSUE THREAD

**Issue by angelod1as** [radix-ui/primitives#1681] opened 2022-09-22 15:52 UTC
### Current Behavior

Whenever I open a Select inside a Dialog, `Uncaught InternalError: too much recursion` happens.

https://user-images.githubusercontent.com/13950513/191791530-162bb566-09c4-4de2-bd2c-a9cb303c94dd.mov

I created a copy of my file in CodeSandbox, and the error that appears is different. The code is exactly the same:

https://user-images.githubusercontent.com/13950513/191793302-500f3d85-06bb-4ff7-99fe-b3b7672cd267.mov

I have absolutely no clue what might be happening. As seen in CodeSandbox, I'm only using Radix-UI components.

Also: is there something I can do to improve this bug-tracking?

### Expected behavior

The `recursion error` should not happen.

### Reproducible example

[Almost reproducible example](https://codesandbox.io/s/brave-nova-odg4y7?file=/src/App.tsx)

### Additional context

The code in the CodeSandbox and in my page is **the same**. Apart from that, I'm running my page in NextJS. There's no custom code in `_app` and this page has only the code in CodeSandbox.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dialog | 1.0.0 |
| Radix Package(s) | @radix-ui/react-select | 1.0.0 |
| React            | n/a     | 17.0.2 |
| Browser          | firefox | 104.0.2 (64-bit)         |
| Node             | n/a     | v16.14.2        |
| npm/yarn         | yarn         |        1.22.19 |
| Operating System |  MacOS       |         12.5.1 (21G83) |

**Comment by andy-hook** [comment] 2022-09-22 16:17
@angelod1as Looks like [this issue](https://github.com/radix-ui/primitives/issues/1296) though in your description is says you're running matching `1.0.0` versions, is that absolutely the case in your local project?

I'm unable to repro from your example in Firefox.

> I created a copy of my file in CodeSandbox, and the error that appears is different

The error in the second video is thrown by csb code and not radix related afaik.

**Comment by angelod1as** [comment] 2022-09-22 16:58
@andy-hook Yes, both are `1.0.0`. 

I can't repro this as well in csb. This bummers me a lot. I'll try to create a repo with nextjs and reproduce in github.

**Comment by angelod1as** [comment] 2022-09-22 19:20
@andy-hook, I found a solution. Adding a `container` to the `Select.Portal` stops the recursive error. It bugs other stuff — like not showing the content on the first click — but that's another investigation for tomorrow.

**Comment by andy-hook** [comment] 2022-09-23 08:10
@angelod1as Did you have any luck with a repro project? I'm fairly certain this can be resolved by bumping package versions. Are you running other primitives like `DropdownMenu`, `Popover`, `ContextMenu` ? I would try bumping all of your Radix packages to latest if you haven't already, and clean any residual cache or lock files to test.

**Comment by angelod1as** [comment] 2022-09-23 08:30
@andy-hook No luck. I created a fresh install of Next yesterday, installed the packages, and the issue wouldn't happen. It's something in my codebase specifically.

I think I solved it, but I'm sorry not to be able to share more than this:

- A Select works normally outside a Dialog.
- If a Select is inside a Dialog, the recursive error happens when you click the Select trigger.
- To stop the recursive error, I had to manually set a ref and a `container` in the Dialog (see link below)
- Now, the recursive error stops happening... but the Select won't open properly anymore.
- The solution for this is manually controlling the open state.
- Now, no recursion error happens, and it works properly (at least apparently).

[See here the updated code with what's exactly on my codebase](https://codesandbox.io/s/brave-nova-odg4y7?file=/src/App.tsx).

Also, yes, I do have other packages installed:

```
    "@radix-ui/react-accordion": "^0.1.6",
    "@radix-ui/react-dialog": "1.0.0",
    "@radix-ui/react-dropdown-menu": "0.1.6",
    "@radix-ui/react-label": "^1.0.0",
    "@radix-ui/react-progress": "^0.1.4",
    "@radix-ui/react-select": "^1.0.0",
    "@radix-ui/react-switch": "^0.1.5",
    "@radix-ui/react-toggle-group": "1.0.0",
    "@radix-ui/react-tooltip": "^0.1.7",
```

I'll try bumping all of the possible ones to 1.0.0 and see what happens.

**Comment by andy-hook** [comment] 2022-09-23 08:38
> I created a fresh install of Next yesterday, installed the packages, and the issue wouldn't happen

This strongly suggests a dependency conflict to me. Upgrade all of your Radix packages if you can, I feel that's very likely to solve it and be the best solution.

**Comment by angelod1as** [comment] 2022-09-23 10:06
@andy-hook I'll do that. As I couldn't reproduce, it's ok to close this. Thanks a lot for the support.

**Comment by andy-hook** [comment] 2022-09-23 10:14
@angelod1as No probs! but please follow up if you're still having issues after refreshing.

**Closed by andy-hook** 2022-09-23 10:14 UTC

**Comment by kirkov** [comment] 2022-11-09 14:16
Hi. I just ran into the same issue locally in Firefox (106.0.5 Mac). I'm also able to reproduce the issue in the codesandbox that @angelod1as provided every time. I bumped all the dependencies locally to 1.0.0+ but still seeing the issue. 

<img width="766" alt="Screenshot 2022-11-09 at 15 09 37" src="https://user-images.githubusercontent.com/239877/200852685-b0293725-10ab-4aae-939f-7965a96b034e.png">

<img width="594" alt="Screenshot 2022-11-09 at 15 07 33" src="https://user-images.githubusercontent.com/239877/200852751-a6265b44-f1ff-472d-9e32-680a8401072b.png">

**Comment by eneskaya** [comment] 2023-06-20 08:32
@angelod1as @andy-hook I can reproduce the issue with both your sandboxes 100% of the time on Firefox. It does not seem that your `container` fix worked really.

<img width="1374" alt="Screenshot 2023-06-20 at 10 30 49" src="https://github.com/radix-ui/primitives/assets/964419/5ea0a3f2-45c3-4788-affb-8aebafd15e9d">

**Comment by McTom234** [comment] 2023-08-25 03:36
Heyya, I had this issue a while ago. Back then, I was able to fix it by using the latest versions of all primitives I had. Just now I am encountering this issue again, with all the latest versions and a fresh npm install. So, I vote for reopening as well 👼

**Comment by matejm** [comment] 2023-09-11 11:43
Having a same issue here with latest versions of `radix-ui/react-dialog`(1.0.4) and `radix-ui/react-select` (1.2.2). Tried upgrading both of them to latest release candidate and same issue persists.

**Comment by SteveMeta** [comment] 2023-11-15 17:04
Same issue as reported. This bug crashes firefox for me.

**Comment by angelod1as** [comment] 2023-11-16 09:32
(Why is this issue closed?)

**Comment by McTom234** [comment] 2023-11-16 10:53
I haven't had problems recently. I keep all my radix ui packages up to date (all, e.g. not only select and dialog)

**Comment by ccssmnn** [comment] 2024-02-12 14:10
> See here the updated code with what's exactly on my codebase

Having the same issue with latest versions in my codebase.

**Comment by matheusaugm** [comment] 2024-05-21 11:55
> > See here the updated code with what's exactly on my codebase
> 
> Having the same issue with latest versions in my codebase.

I'm still having the same issue, were you able to fix it?

**Comment by acadams** [comment] 2024-09-10 20:08
I noticed this issue after upgrading `@radix-ui/react-dropdown-menu` from `2.0.6` to `2.1.1` and had to revert back to the former.
