### ISSUE TITLE
[Tooltip][Mobile] - Not triggering on focus 

### ISSUE THREAD

**Issue by alinebujato** [radix-ui/primitives#1351] opened 2022-04-28 15:09 UTC
### Current Behavior

The tooltip is not triggered when focusing over the trigger on mobile. This is expected [accessibility behavior](https://www.w3.org/TR/wai-aria-practices-1.2/#keyboard-interaction-23).

### Expected behavior

The tooltip should show on focus.

### Reproducible example

[Tooltip - Mobile](https://859r0g.csb.app/)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-tooltip      |    0.1.7    |
| React            | n/a     |         |
| Browser          |    all     |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |   all      |         |

**Comment by drianoaz** [comment] 2022-04-28 15:56
I did some tests and apparently this problem was solved in the version `0.1.8-rc.10`

**Comment by benoitgrelard** [comment] 2022-04-29 09:43
Yeah so it's definitely by design and they shouldn't open on mobile.

> @benoitgrelard Given the previous point, is this is a regression from [this change](https://github.com/radix-ui/primitives/pull/1314/files#r846350751)?

Hmm, yeah potentially. I'll close this issue be open another one for the regression 👍

**Closed by benoitgrelard** 2022-04-29 09:43 UTC

**Comment by benoitgrelard** [comment] 2022-04-29 09:45
#1354

**Comment by Simonpedro** [comment] 2022-06-23 16:00
> Yeah so it's definitely by design and they shouldn't open on mobile.

Hey @benoitgrelard, I just noticed it doesn't open on mobile and thought it was a bug or a misconfiguration and ended up here. Out of curiosity, can I ask what's the rationale behind this statement? Thanks!

**Comment by benoitgrelard** [comment] 2022-06-23 16:22
Hey @Simonpedro,

Have a look here for some more explanations: https://github.com/radix-ui/primitives/issues/955
