### ISSUE TITLE
Some clicks (changes) in popover closes it when it's used inside a dialog

### ISSUE THREAD

**Issue by artaommahe** [radix-ui/primitives#2269] opened 2023-07-12 14:07 UTC
### Current Behavior

- having a form with popover inside dialog
- form has selected tags list, popover allows to select/remove tags
- adding tags from popover works fine (`setState([...tags, tag])`)
- removing tag makes popover close (`setState(tags.filter((t) => t !== tag))`)
- works fine outside of the dialog

### Expected behavior

Removing case should not close popover that is inside a dialog

### Reproducible example

https://codesandbox.io/s/little-hill-l9fmdl?file=/src/App.tsx

### Additional context

- removing tags list before popover fixes the issue
- adding `modal` to popover fixes the issue

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dialog     |     1.0.4    |
| Radix Package(s) |    @radix-ui/react-popover     |     1.0.6    |
| React            | n/a     |    18.2.0/17.0.2     |
| Browser          |    Chrome     |    114.0.5735.198     |
| Assistive tech   |         |         |
| Node             | n/a     |    18.6.0     |
| npm/yarn         |   npm      |    9.5.1     |
| Operating System |    MacOS     |     13.4.1    |

**Comment by taoliujun** [comment] 2023-08-01 05:15
Hi man, have you solved it? I have same problem.

**Comment by artaommahe** [comment] 2023-08-01 07:11
Used modal=true on popover

**Comment by daichangxin** [comment] 2023-08-01 07:31
> Used modal=true on popover

Thank you so much!

**Comment by taoliujun** [comment] 2023-08-01 07:38
@artaommahe I love you so much.

**Comment by joaom00** [comment] 2023-08-19 00:26
Hey, the issue seems to be the same as https://github.com/radix-ui/primitives/issues/2180. Upgrade to the RC version should work

[Codesandbox](https://codesandbox.io/s/old-pond-d5kc66)

**Comment by benoitgrelard** [comment] 2024-03-07 09:12
Duplicate of #2180

**Closed by benoitgrelard** 2024-03-07 09:12 UTC
