### ISSUE TITLE
`<Popover.Close />` and `<Form.Submit />` don't work when nested.

### ISSUE THREAD

**Issue by MimmyJau** [radix-ui/primitives#2462] opened 2023-10-17 21:16 UTC
### Current Behavior

Mouse-clicking the result of nesting `<Form.Submit />` inside a `<Popover.Close asChild />` will close the popover but not submit the form. You get the same behaviour (popover closes but form doesn't submit) even if you nest `<Popover.Close />` inside `<Form.Submit asChild />`.

On the other hand, pressing `Enter` will submit the form but not close the popover if you nest `<Form.Submit />` inside a `<Popover.Close asChild />`. The reverse nesting will only close the popover when pressing `Enter`. 

### Expected behavior

Would expect both the form to be submitted and the popover to close regardless of whether the user clicks the nested button or presses `Enter` and regardless of which component is nested in the other.

### Reproducible example

[CodeSandbox minimal reproducible example](https://codesandbox.io/s/gifted-ives-x7txkj)

```typescript
import * as React from "react";
import * as Form from '@radix-ui/react-form'
import * as Popover from '@radix-ui/react-popover'

export function App() {

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    alert("submitting!")
  }
  
  return (
    <Popover.Root>
      <Popover.Trigger>Open Sesame</Popover.Trigger>
      <Popover.Content>
        <Form.Root onSubmit={handleSubmit}>
          <Form.Field name="form">
            <Form.Control />
          </Form.Field>
          <Popover.Close asChild>
            <Form.Submit>Submit</Form.Submit>
          </Popover.Close>
        </Form.Root>
      </Popover.Content>
    </Popover.Root>
  )
}
```

### Suggested solution

None, but happy to work on a solution if help is needed.

### Additional context

One can solve this problem by controlling the `open` state of `<Popover />` manually, but my sense is they should play nicely together out-of-the-box.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-form        |   `0.0.3`      |
| React            | n/a     |   `18.2`      |
| Browser          |  Chrome       |   `118.0.5993.70`      |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by joaom00** [comment] 2023-10-18 14:51
Probably because `Form.Submit` is being unmounted causing onSubmit to never happen. I think the right way to handle this is as you are already doing, controlling the open and close state when the submit is finished

**Comment by MimmyJau** [comment] 2023-10-18 17:07
If it's true that `Form.Submit` is being unmounted, then wouldn't that also apply to a `<button>` as in this [small example](https://codesandbox.io/s/vibrant-bose-dpsnvm?file=/src/App.tsx)? 

It seems like the button is able to handle the click before the popover unmounts it, but correct me if I'm misinterpreting what you're saying.

**Comment by joaom00** [comment] 2023-10-19 12:10
> If it's true that Form.Submit is being unmounted

sorry, I meant `Form.Root`

**Comment by MimmyJau** [comment] 2023-10-19 19:07
To add one more toy [example](https://codesandbox.io/s/pensive-mahavira-c9grjw?file=/src/App.tsx), when you add the `onClick` handler explicitly to `Form.Submit`, the `onClick` works as expected but the `Popover` will no longer close.

**Comment by joaom00** [comment] 2023-10-19 20:52
> but the Popover will no longer close

Yeah, because `e.preventDefault()` prevents Radix from closing the popover.

**Comment by benoitgrelard** [comment] 2024-03-08 12:21
As explained by @joaom00 this is expected behaviour because the `Close` button is wired to close the popover straight away. When performing any sort of async operation, you'll need to control the state so you can close in your own time.

Have a look at this guide example for `Dialog` which is the same idea.

https://www.radix-ui.com/primitives/docs/components/dialog#close-after-asynchronous-form-submission

**Closed by benoitgrelard** 2024-03-08 12:21 UTC
Labels: Resolution: Expected Behaviour, Package: react/popover
