### ISSUE TITLE
@radix-ui/react-label - role="label" is invalid

### ISSUE THREAD

**Issue by gtiminskis-sc** [radix-ui/primitives#1310] opened 2022-04-06 08:21 UTC
## Bug report
Running react-label component through [`jest-axe`](https://github.com/nickcolley/jest-axe) produces an accessibility error:
```
    "ARIA roles used must conform to valid values (aria-roles)"

    Fix all of the following:
      Role must be one of the valid ARIA roles: label

    You can find more information on this issue here: 
    https://dequeuniversity.com/rules/axe/4.2/aria-roles?application=axeAPI
 ```

I believe it is caused by `role="label"` being applied on the element.

Looking at the guidelines for [axe core](https://dequeuniversity.com/rules/axe/4.2/aria-roles?application=axeAPI) and the list of [WAI-ARIA roles on Mozilla](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles) it doesn't appear that `role="label"` is valid.

### Current Behavior
Using the component results in the following HTML:
```
import { Root } from "@radix-ui/react-label";

<Root>My Label</Root>
```
```
<span role="label" id="radix-3">My Label</span>
```
### Expected behavior
Not exactly sure. Would using a label HTML element be a viable solution?
```
<label id="radix-3">My Label</label>
```

### Reproducible example

[CodeSandbox Example](https://codesandbox.io/s/bold-morning-tkqfh7?file=/src/Label.test.js)
Run tests => See Problems

Thank you!

**Comment by benoitgrelard** [comment] 2022-04-06 11:27
This issue is a duplicate of #638 where we've explained original thoughts.
That said, we are also investigating if we can now rely on native `label` in #1233.

I'll close this issue now.

**Closed by benoitgrelard** 2022-04-06 11:27 UTC
Labels: Resolution: Duplicate
