### ISSUE TITLE
Tooltip - ArrowOffset behaviour support

### ISSUE THREAD

**Issue by lucastobrazil** [radix-ui/primitives#1578] opened 2022-07-27 11:19 UTC
### Overview

With the recent `1.0.0` release of Tooltip (https://github.com/radix-ui/primitives/pull/1531), the behaviour around alignment of the tooltip has changed. As discussed by @andy-hook [on Discord](https://discord.com/channels/752614004387610674/803656530259738674/1001472353622052864), the new behaviour means the tooltip is always _trying_ to be aligned to the centre of the trigger. 

For use cases where we want the tooltip to appear to the left-most (ie. start) or right-most (ie. end) side of the trigger, we can now no longer align the arrow to the left/right properly, nor with any offset to account for the border radius.

See below example:

<img width="576" alt="Screen Shot 2022-07-27 at 7 55 50 am" src="https://user-images.githubusercontent.com/8508891/181234114-67367d04-8239-49e2-9abb-61e2320c30ef.png">

### Who does this impact? Who is this for?

Users who wish to allow the tooltip to be pointed at the start/end in a more predictable way.

### Additional context

Personally, I am okay with the behaviour we inherited from `floating-ui`, but I wanted to raise it as it's now not possible to offer the option of this alignment.

**Comment by benoitgrelard** [comment] 2022-08-01 15:32
Hey @lucastobrazil,

Thanks for raising this up!

> Personally, I am okay with the behaviour we inherited from floating-ui, but I wanted to raise it as it's now not possible to offer the option of this alignment.

We are aware of the change in behaviour with the adoption of `floating-ui` here. In many ways, the way it worked before was because of a simplification on our part with our home-grown popper version. There isn't many reason why it would be more aesthetically pleasing to have the arrow aligned with the start/end of the content rather than centered on the trigger it comes out of. It was always really the goal.

> nor with any offset to account for the border radius.

This is actually still possible via the new `arrowPadding` prop on `Content`. It is there specifically for edge cases where the arrow is centered but also very close to the side of the popper and you have a `border-radius` on `Content` so you need to make sure the arrow will disappear early enough so it doesn't appear disconnected.


In light of this, I will close the issue as that is intended behaviour from our side.

**Closed by benoitgrelard** 2022-08-01 15:32 UTC
Labels: Type: Discussion, Package: react/popper

**Comment by tom2strobl** [comment] 2022-09-06 13:42
@benoitgrelard I mean I respect that you guys want to force the arrow being centered for your library as this is clearly your choice to be made, but who in the world actually wants the possibility of `align: start` and then an arrow _not_ at the start?
In terms of UX anchoring an element to an alignment means the origin that the arrow should point to is exactly that visual anchor.

I don't see how `arrowPadding` actually does anything when its always centered anyway? If the trigger is so wide that its center-x value is greater than the size of the tooltip, then the arrow is never shown since its out of bounds.

Here's a sandbox that showcases the issue: https://codesandbox.io/s/radix-ui-slider-forked-qguwvx?file=/src/App.tsx

Unless I understood something fundamentally wrong?

**Comment by benoitgrelard** [comment] 2022-09-20 10:05
> but who in the world actually wants the possibility of align: start and then an arrow not at the start?

The "start" part of the alignment refers to the alignment of the `Content`, not the `Arrow`.

> I don't see how `arrowPadding` actually does anything when its always centered anyway?

`arrowPadding` isn't here to move the `Arrow`, but rather to accommodate things like a border radius on the `Content` as otherwise the `Arrow` would appear to bleed out of it.

> If the trigger is so wide that its center-x value is greater than the size of the tooltip, then the arrow is never shown since its out of bounds.

That is correct and is just a limitation of those constraints. In our experience these cases are more rare than the opposite and the center constraint for the arrow is what people want.

> Unless I understood something fundamentally wrong?

No you are understanding things correctly 👍

**Comment by tom2strobl** [comment] 2022-09-20 12:12
@benoitgrelard thanks for clarification, fair enough
