### ISSUE TITLE
AspectRatio.Root not working with server side render for nextjs

### ISSUE THREAD

**Issue by Bowriverstudio** [radix-ui/primitives#2346] opened 2023-08-17 16:16 UTC
## Bug report

On Nextjs 13 with server side rendering I get the following error if I do not use the directive

 'use client'

### Current Behavior

<pre><span>./src/components/ACFCustomBlocks/MmxWhoWeAre/MmxWhoWeAre.tsx
ReactServerComponentsError:

You're importing a component that needs flushSync. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

   ,-[</span><span style="color: var(--color-ansi-cyan);">//node_modules/@radix-ui/react-primitive/dist/index.mjs</span><span>:1:1]
 </span><span>1</span><span> | import $4q5Fq$babelruntimehelpersesmextends from "@babel/runtime/helpers/esm/extends";
 </span><span>2</span><span> | import {forwardRef as $4q5Fq$forwardRef, useEffect as $4q5Fq$useEffect, createElement as $4q5Fq$createElement} from "react";
 </span><span>3</span><span> | import {flushSync as $4q5Fq$flushSync} from "react-dom";
   : </span><span style="color: var(--color-ansi-red); font-weight: 800;">        ^^^^^^^^^</span><span>
 </span><span>4</span><span> | import {Slot as $4q5Fq$Slot} from "@radix-ui/react-slot";
 </span><span>5</span><span> | 
   `----

### Expected behavior

I expect the code

<AspectRatio.Root ratio={image_width / image_height} className='not-prose'>
                                    <Image
                                        src={image_url}
                                        fill
                                        alt=''
                                    />
                                </AspectRatio.Root>
                                
                              to work with nextjs 13 serverside.

### Reproducible example

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   
    "@radix-ui/colors": "^1.0.1",
    "@radix-ui/react-accordion": "^1.1.2",
    "@radix-ui/react-aspect-ratio": "^1.0.3",
    "@radix-ui/react-checkbox": "^1.0.4",
    "@radix-ui/react-dialog": "^1.0.4",
    "@radix-ui/react-dropdown-menu": "^2.0.5",
    "@radix-ui/react-form": "^0.0.3",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-menubar": "^1.0.3",
    "@radix-ui/react-navigation-menu": "^1.1.3",
    "@radix-ui/react-popover": "^1.0.6",
    "@radix-ui/react-radio-group": "^1.1.3",
    "@radix-ui/react-scroll-area": "^1.0.4",
    "@radix-ui/react-select": "1.2.2",
    "@radix-ui/react-slider": "^1.1.2",
    "@radix-ui/react-switch": "^1.0.3",
    "@radix-ui/react-tabs": "^1.0.4",
    "@radix-ui/react-toast": "^1.1.4",
    "@radix-ui/react-toggle-group": "^1.0.4",
    "@radix-ui/react-tooltip": "^1.0.6",

      |         |
| React            | n/a     |         |
    "react-dom": "^18.2.0",

| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |

node -v
v20.2.0

| npm/yarn         |         |         |

 yarn -v
1.22.19

| Operating System |      MAC   |      12.5.1   |

**Comment by TheMikeyRoss** [comment] 2023-08-31 08:26
I have a similar issue that seems to be coming from the tooltip component when used in next 13

```
./node_modules\@floating-ui\react-dom\dist\floating-ui.react-dom.esm.js
ReactServerComponentsError:

You're importing a component that needs useEffect. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials
```

**Comment by mszekiel** [comment] 2023-09-14 18:52
I can see same behavior for `Label.Root` component.

**Comment by danvoyce** [comment] 2023-10-01 12:31
I'm getting the same for `react-select`. I get why this doesn't work, however It says [here](https://www.radix-ui.com/primitives/docs/guides/server-side-rendering) that Primitives should work on the server

**Comment by staranbeer** [comment] 2023-10-03 14:07
@danvoyce In the link you shared above, I believe they are talking about Server side rendering and not server components. Server side rendering is provided by Next.js or similar frameworks but server components are a react specific feature which can not have any client side code in them which is probably why you're getting this error. This article goes helped me a lot with this concept. https://www.patterns.dev/posts/react-server-components

**Comment by JamesBender** [comment] 2023-11-16 18:24
I have a similar issue, except it's with Label, and it's complaining about useEffect. I want this to run on the server, so "use client" is not an option.

**Comment by benoitgrelard** [comment] 2024-03-05 10:48
Duplicate of #2430 2430

**Closed by benoitgrelard** 2024-03-05 10:48 UTC
