### ISSUE TITLE
[Tab] Keep tabs content mounted when switching between tabs

### ISSUE THREAD

**Issue by minedun6** [radix-ui/primitives#2359] opened 2023-08-22 17:34 UTC
Hello,
I need a way to keep tabs mounted even when switching between tabs.
I was looking through the documentation and I couldn't find the info regarding this feature.
Any help ?

**Comment by minedun6** [comment] 2023-08-22 17:41
I found the solution by snooping through the code, I used forceMount along with hidden and that did the trick.
Is there any other solution, preferably a much cleaner solution because it feels kinda of hacky.

**Comment by ojj1123** [comment] 2023-08-23 10:48
I wonder how you solve!
I posted the discussions https://github.com/radix-ui/primitives/discussions/2271 before.

**Comment by minedun6** [comment] 2023-08-25 09:43
Certainly,

`
{tabs.map((tab) => (
<Tabs.Content
         forceMount
         hidden={tab.id !== tabs[activeIndex].id}>
{/* content goes here */}
</Tabs.Content>
))}
`

**Comment by TinsFox** [comment] 2023-11-10 03:40
> Certainly,
> 
> ```js
> {tabs.map((tab) => (
> <Tabs.Content forceMount hidden={tab.id !== tabs[activeIndex].id}>
> {/* content goes here */}
> </Tabs.Content>
> ))}
> ```

It worked for me, and I'm looking forward to something better

**Comment by benoitgrelard** [comment] 2024-03-07 08:39
Duplicate of #1155

**Closed by benoitgrelard** 2024-03-07 08:39 UTC

**Comment by myudak** [comment] 2024-08-21 11:35
how to this with shadcn

**Comment by JonnyAxelsson** [comment] 2024-08-29 14:21
> how to this with shadcn

Tried it with shadcn and it works the same way only on the TabsContent component

**Comment by FrankChen021** [comment] 2024-11-17 15:43
For people who are looking for the solution in shadcn, just make some changes to the `TabsContent` component inside `@/components/ui/tabs.tsx` as follows:

```javascript
// @/components/ui/tabs.tsx
const TabsContent = React.forwardRef<
  React.ElementRef<typeof TabsPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TabsPrimitive.Content>
>(({ className, ...props }, ref) => (
  <TabsPrimitive.Content
    ref={ref}
    forceMount //<=======Add this line
    className={cn(
      "data-[state=inactive]:hidden", //<=========Add this line
      "mt-2 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
      className
    )}
    {...props}
  />
))
```

**Comment by acsmars** [comment] 2025-03-31 05:29
Thanks very much for the shadecn specific solution
