### ISSUE TITLE
Hydration Error with Radix UI in AccordionTrigger Component

### ISSUE THREAD

**Issue by miguel-leite-2000** [radix-ui/primitives#2604] opened 2023-12-19 17:10 UTC
I'm facing a hydration issue when using Radix UI's AccordionTrigger component in conjunction with Next.js. When rendering on the server, there are no apparent errors, but when trying to hydrate on the client side, a discrepancy error occurs between the initial HTML and what is being rendered on the client.

**Context:**
- **React version:** ^18
- **Next.js version:** 14.0.4
- **Radix UI version:** ^1.1.2

**Steps to Reproduce:**
1. Use the `AccordionTrigger` component within the `Accordion` component of Radix UI.
2. Server-side rendering of the page (SSR) using Next.js.
3. Try to hydrate the page on the client.

**Error Displayed:**

``` Error: Hydration failed because the initial UI does not match what was rendered on the server. ```
```
Warning: Expected server HTML to contain a matching <h3> in <h3>.
```

**Example Code:**

```jsx
// Componente AccordionDemo
<AccordionDemo />

// Componente AccordionTrigger
const AccordionTrigger = forwardRef<HTMLButtonElement, CustomAccordionTriggerProps>(
  ({ children, className, ...props }, forwardedRef) => (
    <Accordion.Header className="flex">
      <Accordion.Trigger
        className='group text-white text-xl font-semibold flex justify-between items-center w-full'
        {...props}
        ref={forwardedRef}
      >
        {children}
        <PlusIcon className="group-data-[state=open]:hidden" aria-hidden />
        <MinusIcon className="group-data-[state=closed]:hidden" aria-hidden />
      </Accordion.Trigger>
    </Accordion.Header>
  )
);
```

**Comments:**

- This issue occurs when attempting to hydrate on the client side.
- There are no errors during server rendering.
- Conditional styles such as `group-data-[state=open]` and `group-data-[state=closed]` are applied correctly during server-side rendering.

**Additional Information:**

- `@radix-ui/react-accordion`: ^1.1.2
- `@radix-ui/react-icons`: ^1.3.0
- `next`: 14.0.4
- `react`: ^18

Let's work together to solve this problem!

**Comment by remus00** [comment] 2024-01-19 09:40
Hi, I have the same problem with Shadcn Accordion, that are based on the radix ui, and i'm in next 14.0.4

**Comment by remus00** [comment] 2024-01-19 09:40
Did you solve it?

**Comment by miguel-leite-2000** [comment] 2024-03-03 20:40
> Did you solve it?

Yes @remus00

**Comment by benoitgrelard** [comment] 2024-03-05 11:18
We have a [sandbox in the repo](https://github.com/radix-ui/primitives/tree/main/ssr-testing) specifically to test SSR, and can't reproduce the issue. I will close the issue as it seems to hydrate fine so likely to be an issue with the particular lib (shadcn) or implementation.

But feel free to keep discussing if there's more to it.

**Closed by benoitgrelard** 2024-03-05 11:18 UTC
Labels: Resolution: Can't Reproduce, Package: react/accordion
