### ISSUE TITLE
[Tooltip] On a Button that opens a modal, Tooltip reappears when modal is closed

### ISSUE THREAD

**Issue by lin-jessica** [radix-ui/primitives#617] opened 2021-04-23 17:51 UTC
## Question

I've got a button with a Tooltip that opens a Modal when clicked. When the modal is closed, focus state returns to that button causing the Tooltip to reappear. What are my options for making this less weird for seeing-eye users?

Some more details reported on [Reach/ui](https://github.com/reach/reach-ui/issues/790)

**Comment by benoitgrelard** [comment] 2021-04-26 10:16
Hi there, yes this is something we have also faced in the Modulz app.
We have some ideas here but we haven't gotten around to it yet.
We will update you once we start working on it.

**Comment by jjenzz** [comment] 2021-04-26 12:08
For reference, here was the sandbox I had created a while back demoing things we had discussed https://codesandbox.io/embed/usefocusenter-forked-x6i0n

**Comment by rafgraph** [comment] 2021-06-10 16:02
I'm having a related issue when switching tabs or applications, the tooltip can reappear when switching back to the tab with the tooltip. This happens when the tooltip trigger still has focus but the tooltip is no longer shown, then when switching tabs/apps, the browser calls focus on the tooltip trigger when switching back, causing the tooltip to show again. Note that this happens on Chrome v91 MacOS, but not Safari MacOS as Safari doesn't blur-and-re-focus on tab/app switching.

One idea would be to show the tooltip when `focus` is caused by keyboard input, but not when `focus` is caused by mouse or touch input (just use hover and long press to trigger the tooltip from mouse and touch input). Something like [Event From](https://github.com/rafgraph/event-from) might help with this.

**Comment by benoitgrelard** [comment] 2021-06-10 17:56
I may not be understanding correctly, but I don't think that use-case is an issue.
ie. If the trigger was focused and tooltip was showing before you command+tab out of the browser, and you come back, the trigger is still focused so the tooltip should still show.

**Comment by rafgraph** [comment] 2021-06-10 19:00
The issue is that it also happens when the tooltip is not showing before switching tabs/apps (when the trigger still has focus).

https://user-images.githubusercontent.com/11911299/121581809-49153400-c9fc-11eb-9119-fa5b48cf4def.mov

**Comment by benoitgrelard** [comment] 2021-06-11 08:34
Ah yes I see, thanks for the extra video. That's kind of a different issue from the original one though, I would say less important/annoying too. Would you mind creating a separate issue for it so we can track the different things separately?

**Comment by rafgraph** [comment] 2021-06-11 13:49
I can create a new issue. I mentioned it here because I think they have the same underlying cause: the trigger gets re-focused resulting in showing the tooltip when it shouldn't be shown. In the original issue, closing the modal causes the re-focus, and in my example switching tabs/apps causes the re-focus.

I agree the tab/app switching edge case is less likely to be run into than the close modal case.

**Comment by benoitgrelard** [comment] 2021-06-11 15:09
Thanks for that @rafgraph, are you ok with me deleting the comments above now that we have the separate issue so we can keeps things nicely separate?

**Closed** 2022-04-05 11:17 UTC
Labels: Type: Enhancement, Resolution: Won't Fix, Package: react/tooltip

**Comment by GrandChieftain** [comment] 2023-08-16 15:38
I was able to fix this issue. Took some engineering on my part, but I wasn't going to accept taking a bug like that into production. You want to create a state variable and conditionally render the content of your tooltip based on that state (ex. {active && <Tooltip.Content>...<Tooltip.Content>}). Then on Tooltip.Root (or just Tooltip if you're using shadcn/ui like me), you want to use onOpenChange function to set the state variable as false (so the content doesn't render). This stop the annoying flickering that happens when you open and close the modal. The only time when you want to set this state back to true is when you hover over the trigger button, so on Tooltip.Trigger you'd use an onMouseEnter event to set the state variable as true. And you don't even have to worry about checking whether the modal is open/closed first (because you obviously want to prevent the tooltip from showing when it's open): it's like the trigger button disappears from the DOM, so hovering over it doesn't trigger the event.

I used something similar to deal with dialogs: this approach works, but there was still some tooltip flickering when opening the dialog, so you have to use an additional onClick event to set your state variable as false instead of just relying on onOpenChange because it doesn't register fast enough. I was also having an additional issue that the tooltip wouldn't show up on the first hover after you've closed the dialog. But I realized that, taking the code from shadcn/ui, the Dialog.Trigger component already has the asChild property passed into it, which is good, but you have to make sure that the child element is actually a button. I was only experiencing that issue because mine was an SVG. Just caught that now, so even I gained from making this comment. Hopefully, you guys don't have to waste the same amount of time that I did on this. Cheers.

**Comment by petercinibulk** [comment] 2023-09-03 19:34
@GrandChieftain Can you share a code snippet of your solution?

**Comment by GrandChieftain** [comment] 2023-09-03 20:31
@petercinibulk Yeah, I should've just did that, would've kept my response more concise. Tell me if it works for you. Pretty new to GitHub and in a rush, so sorry if I didn't frame this in the ideal way (as opposed to doing CodeSandbox or something). Also using Shadcn/ui: there might be a little bit of abstraction, but it's pretty much one-to-one to the original Radix UI variants.

My actual dropdown menu (with modal) follows this format:

const [active, setActive] = useState(true)

return (
  <TooltipProvider displayContent={active}>
          <DropdownMenu onOpenChange={() => setActive(false)}>
                  <DropdownMenuTrigger asChild onMouseEnter={() => setActive(true)} onClick={() => setActive(false)}>
                          // HTML button element
                  </DialogTrigger>
                  <DialogContent>
                          // dropdown menu items
                  </DialogContent>
          </DropdownMenu>
  </TooltipProvider>
)

And then I defined TooltipProvider.tsx as the following (I'll just copy and paste this one):

"use client"

import { ReactNode } from "react"
import {
    Tooltip,
    TooltipContent,
    TooltipProvider as TooltipContext,
    TooltipTrigger,
  } from "@/components/ui/tooltip"

export default function TooltipProvider({children, displayContent}: {children: ReactNode[], displayContent?: boolean}){
    if (typeof displayContent === 'boolean'){
        return (
            <TooltipContext>
                <Tooltip>
                    <TooltipTrigger>
                        {children[0]}
                    </TooltipTrigger>
                    {displayContent && <TooltipContent>
                        {children[1]}
                    </TooltipContent>}
                </Tooltip>
            </TooltipContext>
        )
    }
    else{
        return (
            <TooltipContext>
                <Tooltip>
                    <TooltipTrigger>
                        {children[0]}
                    </TooltipTrigger>
                    <TooltipContent>
                        {children[1]}
                    </TooltipContent>
                </Tooltip>
            </TooltipContext>
        )
    }
}

I'm new to web dev, so I doubt this is the most efficient solution; using ternary operators might be slightly faster, but I'm not really worried about performance. The drawbacks are minimal compared to that terrible UI glitch, so I hope this helps.

**Comment by GrandChieftain** [comment] 2023-09-03 20:45
@petercinibulk I tried sending what I had, but it didn't show properly, probably because I was just pasting code into where text is supposed to be. But the Add Code option doesn't seem to support line breaks. And GitHub doesn't support .tsx files either. I'll just send a CodeSandbox when I have the time, but definitely let me know if you're encountering any errors with this solution. As you can see, I'm new to web dev and posting on forums (whether it be GitHub or SO), but this worked for me.

**Comment by yaralahruthik** [comment] 2023-10-26 10:28
@asalcedo-ci This would disable the tooltip on keyboard focus! I tried putting onFocus, but that still brings annoying flicker back!

**Comment by wmonecke** [comment] 2023-11-01 23:48
While this gets solved I found this quick and dirty solution:

```
 const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setTimeout(() => {
      contentRef.current?.focus();
    }, 100);
  }, [open]);
  
  <DialogContent
        ref={contentRef}
        className={cn(
          'max-h-screen overflow-x-hidden overflow-y-scroll pt-8 lg:min-w-[840px]',
          className,
        )}
      >
//      ....
```

**Comment by michaelfortunato** [comment] 2024-04-20 00:24
> I was able to fix this issue. Took some engineering on my part, but I wasn't going to accept taking a bug like that into production. You want to create a state variable and conditionally render the content of your tooltip based on that state (ex. {active && <Tooltip.Content>...<Tooltip.Content>}). Then on Tooltip.Root (or just Tooltip if you're using shadcn/ui like me), you want to use onOpenChange function to set the state variable as false (so the content doesn't render). This stops the annoying flickering that happens when you open and close the modal. The only time when you want to set this state back to true is when you hover over the trigger button, so on Tooltip.Trigger you'd use an onMouseEnter event to set the state variable as true. And you don't even have to worry about checking whether the modal is open/closed first (because you obviously want to prevent the tooltip from showing when it's open): it's like the trigger button disappears from the DOM, so hovering over it doesn't trigger the event.
> 
> I used something similar to deal with dialogs: this approach works, but there was still some tooltip flickering when opening the dialog, so you have to use an additional onClick event to set your state variable as false instead of just relying on onOpenChange because it doesn't register fast enough. I was also having an additional issue that the tooltip wouldn't show up on the first hover after you've closed the dialog. But I realized that, taking the code from shadcn/ui, the Dialog.Trigger component already has the asChild property passed into it, which is good, but you have to make sure that the child element is actually a button. I was only experiencing that issue because mine was an SVG. Just caught that now, so even I gained something from making this comment. Hopefully, you guys don't have to waste the same amount of time that I did on this. Cheers.

Thanks! Even though this did not exactly work for me, it only required one small change to get it working, namely, onOpenChange should be set on the Dialog component. Here is the full code I used if anyone finds this thread and has the  same issue.

```tsx
function DialogWithTooltip() {
       const [isTooltipAllowed, setIsTooltipAllowed] = useState(true);
       return (<Dialog onOpenChange={() => setIsTooltipAllowed(false)}>
              <TooltipProvider>
                <Tooltip defaultOpen={false}>
                  <TooltipTrigger
                    asChild
                    onMouseEnter={() => setIsTooltipAllowed(true)}
                  >
                    <DialogTrigger asChild>
                      <Button size="icon" variant="ghost">
                        <InfoIcon width={24} height={24} />
                      </Button>
                    </DialogTrigger>
                  </TooltipTrigger>
                  {isTooltipAllowed && (
                    <TooltipContent>
                      <p>The tool tip text!</p>
                    </TooltipContent>
                  )}
                </Tooltip>
              </TooltipProvider>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Are you absolutely sure?</DialogTitle>
                  <DialogDescription>
                    This action cannot be undone. This will permanently delete
                    your account and remove your data from our servers.
                  </DialogDescription>
                </DialogHeader>
              </DialogContent>
            </Dialog>);
}
```
@ me if anyone is using this work around and its not working. Thanks

**Comment by Fingertips18** [comment] 2024-05-11 08:52
@michaelfortunato oh, so you are hiding the content itself and that didn't occur to me. Thanks!

**Comment by GrandChieftain** [comment] 2024-08-29 18:24
@michaelfortunato You're absolutely right: I had onOpenChange on the Dialog component in [my project](https://github.com/GrandChieftain/clubblit/blob/459e737cd8bc67b9dc27fd7a6f97d3215660ed2a/src/components/navigation/OrgSettings.tsx#L111), just added an `onClick={() => setActive(false)}` to the DialogTrigger because that visibly registered faster than onOpenChange. I don't know why I wrote a whole essay instead of just attaching some code, was definitely a noob 😅 Thank you so much for providing a clear solution!
