### ISSUE TITLE
Form submit event doesn't fire on enter when Checkboxis in focus

### ISSUE THREAD

**Issue by ziplb** [radix-ui/primitives#1595] opened 2022-08-03 13:20 UTC
### Current Behavior

If Checkbox element is in focus, then form submit eventdoes not fire on Enter.

### Expected behavior

Form submit event fires on Enter when focus is on Checkbox component.

### Reproducible example

You can use the code snippet from the main documentation of Checkbox component. You need to add a submit event handler to the form:
```jsx
<form onSubmit={() => console.log('submit')}>
...rest
```
Then you should click on the Checkbox so that it gets focus. After that, pressing enter will not cause the handler to be called. 
 
### Additional context

Most likely, this is due to the fact that the input itself doesn't receive focus, but the button responsible for styling the checkbox gets it(focus). The same issue is with RadioGroup component.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |@radix-ui/react-checkbox | 1.0.0        |
| React            | n/a     | 17.0.47 |
| Browser          | Google Chrome | 103.0.5060.134 |
| Assistive tech   |         |         |
| Node             | n/a     |  16.13.1 |
| npm/yarn         |  pnpm  | 7.1.6 |
| Operating System |  macOS Monterey   |   12.4      |

**Comment by benoitgrelard** [comment] 2022-08-03 20:48
Hi @ziplb,

I don't think that's a bug.
As far as I know, implicit submission of forms only happens with inputs and buttons.
Native checkbox/radio do not submit parent forms using the enter key.
I tweaked your sandbox to use native form components instead and it definitely doesn't submit.

I will close the issue as I don't believe this is a thing, but please keep discussing if I am wrong.

**Closed by benoitgrelard** 2022-08-03 20:48 UTC

**Comment by zgottlieb** [comment] 2022-10-03 21:07
> As far as I know, implicit submission of forms only happens with inputs and buttons. Native checkbox/radio do not submit parent forms using the enter key. 

@benoitgrelard, I've seen this mentioned elsewhere about HTML forms, though it's unclear if that's intended behavior or an actual bug in a prior implementation of the HTML Form spec.

I did a little more research and came across [this example from MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio#value), which I adapted into [this CodeSandbox](https://codesandbox.io/s/exciting-elgamal-bbq0m2). Judging by that, it does look like submitting a form on `Enter` from a radio button does in fact work.

I've been trying to get this working with the `RadioGroup` in Radix UI, and while I've managed to work around it by triggering a form submission `onKeyDown` on the `RadioGroup`, I'd prefer an option where it works more similarly to the MDN example.

**Comment by mstade** [comment] 2023-10-19 18:20
Running into this issue as well, is there a workaround available beyond catching the keydown event and submitting the form programmatically?

**Comment by Saadchr** [comment] 2023-11-06 21:48
I'm facing the same issue. It is very useful to be able to quickly submit a form by clicking on Enter

**Comment by ronaldruzicka** [comment] 2024-05-29 11:05
Hi, is there any chance to reopen this issue? 

We have the same problem with `radio`, `checkbox` and `select`. I created a [sandbox](https://codesandbox.io/p/devbox/frosty-aryabhata-rjjq28) where is a `FormRadix` and a `FormNative`. If you select inputs with keyboard and hit enter, in `FormNative` even if you are focused on `radio`, `checkbox` or `select` the form submits. 

On the other hand in `FormRadix` it doesn't. With `radio` and `checkbox` it does nothing, but when you are focused on `select` it opens. Native `select` element can be opened only with `Spacebar` not `Enter` ...is there any particular reason why it should be opened with `Enter` as well?

**Comment by david-arteaga** [comment] 2024-08-15 01:08
For what it's worth, I do think it's worth tackling this discrepancy between native html elements and Radix elements.

When you do include a `<button type"submit">` in a form, which I'd say is by far the most common case when using `<form>`s, the behavior across browsers is consistent (`Enter` on `checkbox`, `radio`, `select` does submit the form).
And the radix "equivalent" components don't match this behavior.

I think many developers expect Radix primitives to behave the same (or at least as close as possible) to native HTML elements, and this discrepancy does introduce friction and was certainly a surprise for me when I started using Radix.

**Comment by timbo-tj** [comment] 2024-11-29 02:39
Also caught by this one. Checkbox is a agree to terms one at the end of the form - which would be common to a lot of forms - and we cant submit the form with enter..!
