### ISSUE TITLE
[ScrollArea] Hardcoded div styles prevent text ellipsis from functioning reactively

### ISSUE THREAD

**Issue by Nepec** [radix-ui/primitives#1374] opened 2022-05-05 19:43 UTC
### Current Behavior

In the `ScrollAreaViewport` component the styles applied to the hard-coded `div`
```
<div ref={context.onContentChange} style={{ minWidth: '100%', display: 'table' }}>
    {children}
</div>
 ```
 don't allow a text ellipsis placed inside the viewport to behave responsively and resize along with its container. In particular it's the `display: table` which doesn't allow the would-be container to shrink.
This becomes a problem when more complex components than the one in my example are used as horizontal scrolling comes into place.
[Problem video example](https://streamable.com/p28klk)

### Expected behavior

[Expected behavior example](https://streamable.com/1zc5hl)

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/scrollarea-text-ellipsis-cy4wvm?file=/src/App.js)

### Suggested solution

Make the styles overwritable

### Your environment

| Software                | Name(s) | Version |
| ------------------  | --------------------------- | ------------------- |
| Radix Package(s)    | @radix-ui/react-scroll-area | 0.1.4               |
| React                     | react                                  | 18.1.0             |
| Browser                 | firefox                                | 100.0              |
| Browser                 | Chrome                             | 101.0.4951.54 |
| Node                     | node                                  | 17.3.1             |
| npm/yarn              | yarn                                   | 1.22.18           |
| Operating System | WSL2 - Ubuntu                  | 20.04              |

**Comment by benoitgrelard** [comment] 2022-05-06 08:09
Duplicate of #926

**Closed by benoitgrelard** 2022-05-06 08:09 UTC
Labels: Resolution: Duplicate, Package: react/scroll-area
