### ISSUE TITLE
DropDownMenu.Trigger fires the first "asChild (as button)" item's function with keyboard activation.

### ISSUE THREAD

**Issue by rlacorne** [radix-ui/primitives#1397] opened 2022-05-13 19:06 UTC
### Current Behavior

When setting asChild to a DropDownMenu item, with the child being a button, using keyboard enter key on the trigger will fire that child's onClick function instead of opening the menu. 

### Expected behavior

Pressing the enter key on the trigger should open the menu.

### Reproducible example

Use keyboard to navigate on the trigger, then press enter key.

[CodeSandbox Template](https://codesandbox.io/s/epic-sara-rubxj7?file=/App.js)

Sample of the code that causes the issue :

```js
          <DropdownMenuItem asChild>
            <button onClick={() => alert("this will fire on keyboard")}>
              This is a button
            </button>
          </DropdownMenuItem>
```

### Suggested solution

DropDownMenu items should be either anchors or buttons at all time, and built with those in mind. asChild seems to cause a lot of issues in this component and could be removed by having correct and accessible default semantics on the menu item itself. It is important that onClick events are never bound to a div, as users can have specific needs requiring them to style, announce and present buttons, anchors and possible interactivity in specific ways. 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |     latest    |
| Browser          |     Chrome    |     100    |
| Assistive tech   |    keyboard navigation     |         |

**Comment by benoitgrelard** [comment] 2022-05-16 08:08
Hi @rlacorne,
This is a duplicate of #1268. Essentially this is because of the focus management, this is because focus is moved during keydown so the enter keyup is firing on your button which triggers the button click.

A simple way to prevent this if you need `asChild` would be to use a div instead of a button (like the item we provide) because the component converts it to a role="menuitem", so it will be losing button semantics anyway.

In other words:

> DropDownMenu items should be either anchors or buttons at all time, and built with those in mind. asChild seems to cause a lot of issues in this component and could be removed by having correct and accessible default semantics on the menu item itself. It is important that onClick events are never bound to a div, as users can have specific needs requiring them to style, announce and present buttons, anchors and possible interactivity in specific ways.

It doesn't have to be as we handle the accessibility for your anyway, so relying on semantics isn't necessary.

**Closed by benoitgrelard** 2022-05-16 08:08 UTC
Labels: Package: react/dropdown-menu, Resolution: Solution Provided

**Comment by BrianHung** [comment] 2022-06-07 21:20
> Essentially this is because of the focus management, this is because focus is moved during keydown so the enter keyup is firing on your button which triggers the button click.

Is there a way to prevent this event from propagating, maybe stopPropagation during the capture phase? Just spitballing here as I encountered the scenario with using a button as the child.
