### ISSUE TITLE
[Dialog][AlertDialog] Encapsulation issue when nesting them

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#769] opened 2021-07-05 19:36 UTC
### Current Behavior

When nesting `AlertDialog` and `Dialog` they control each other.

### Expected behavior

They should only control their own respective content.

### Reproducible example

https://codesandbox.io/s/tender-smoke-4rz00?file=/src/App.js

### Suggested solution

Isolate different contexts should do the trick.

### Additional context

This is similar to #681, same exact problem I think.

**Comment by jjenzz** [comment] 2021-09-15 12:18
Closing as duplicate of https://github.com/radix-ui/primitives/issues/681

**Closed by jjenzz** 2021-09-15 12:18 UTC

**Comment by benoitgrelard** [comment] 2021-09-15 13:38
Oh yeah good point, that's another problematic combination.
