### ISSUE TITLE
Tooltip doesn't position self properly if div has a drop shadow

### ISSUE THREAD

**Issue by Zavien1** [radix-ui/primitives#2018] opened 2023-03-11 17:15 UTC
### Current Behavior

Adding a drop shadow to a parent div makes tooltip position itself incorrectly 
<img width="665" alt="Screen Shot 2023-03-11 at 9 14 00 AM" src="https://user-images.githubusercontent.com/29804724/224502310-aadf34c5-80c1-412a-98fa-90d804e86647.png">

<img width="670" alt="Screen Shot 2023-03-11 at 9 14 30 AM" src="https://user-images.githubusercontent.com/29804724/224502332-e846a0a5-7eb2-4fce-b81d-a6784e8da566.png">

### Expected behavior

Dropshadow should not affect tool tip position

### Suggested solution

No clue

### Your environment

React + Tailwind 

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by joaom00** [comment] 2023-03-11 17:53
Do you have a reproducible example?

**Comment by atomiks** [comment] 2023-03-12 17:37
Radix is using `v0` of Floating UI and is pulling in a version of `@floating-ui/dom` from June 2022, while there have been several fixes since v1 got released in July.

https://github.com/radix-ui/primitives/blob/72018163e1fdb79b51d322d471c8fc7d14df2b59/packages/react/popper/package.json#L20

There aren't any breaking changes between the v0 version used and the latest version, so they can upgrade to `@floating-ui/react-dom^1.0.0` with no effort.  cc: @benoitgrelard 

If you override `@floating-ui/react-dom` + `dom` and `core` to the latest versions manually in your project, is the issue fixed? What browser? This should be the relevant line:

https://github.com/floating-ui/floating-ui/blob/02c127ad9d10800e0ef29e5df9bb458612e737bf/packages/dom/src/utils/is.ts#L60

**Comment by benoitgrelard** [comment] 2023-03-13 09:12
Yes, I was going to ask too: @Zavien1 are you using the `Tooltip.Portal` part?

**Comment by dcyoung** [comment] 2023-05-08 17:14
Encountering this issue as well, any resolution?

**Comment by benoitgrelard** [comment] 2023-05-17 11:44
Hey @atomiks,

This is definitely when using `filter: drop-shadow()` as opposed to `box-shadow`, you can see in the 2nd screenshot, there's a bit of shadow on the second popover, plus `box-shadow` wouldn't create a new containing block.

With that said, the solution is obviously to use `Tooltip.Portal` as you probably wouldn't want that same shadow on the tooltip content anyway.

That being said, relating to the bug, I have checked all of this locally and here are my findings:
- Regardless of which version of `@floating-ui/react-dom` I use, the issue is still present. I have tried:
  - current: `0.7.3`
  - `1.3.0`
  - `2.0.0`
- The issue is only present with `fixed` strategy (which we use). `absolute` strategy is fine even in old `0.7.3`.

I have reproduced the scenario in this simple sandbox using the basics of `@floating-ui/dom` as I believe it's a low-level issue anyway in the core positioning logic:

https://codesandbox.io/s/floating-ui-fixed-strategy-bug-f4hey0

Let me know if I should open a bug on your side!

✌️

**Comment by benoitgrelard** [comment] 2023-05-17 11:44
@dcyoung make sure you use `Tooltip.Portal`.

**Comment by benoitgrelard** [comment] 2023-05-22 07:33
Upstream fix: Upstream fix: https://github.com/floating-ui/floating-ui/pull/2334

**Closed** 2023-05-22 10:49 UTC
Labels: Package: react/tooltip, Dependency: floating-ui

**Comment by dcyoung** [comment] 2023-05-29 18:14
I'm still encountering this issue with the latest radix-ui primitives. Does the update still need to trickle down via an upcoming release of `@floating-ui/react-dom`, or should it be in effect already?
