### ISSUE TITLE
feat: Make release notes or changelog

### ISSUE THREAD

**Issue by A7med3bdulBaset** [radix-ui/primitives#2508] opened 2023-11-05 14:52 UTC
### Overview

I like to keep my dependencies up-to-date with the latest updates. One thing frustrating to me about Radix-ui is It doesn't provide any kind of release notes or changelog. When upgrading I have to look at the commits log or the github diff to see what's new. especially changes are sometimes breaking.

**Comment by mverissimo** [comment] 2023-11-06 12:20
They are published on the website: https://www.radix-ui.com/primitives/docs/overview/releases

**Comment by brendon1555** [comment] 2023-11-13 00:58
> They are published on the website: https://www.radix-ui.com/primitives/docs/overview/releases

That page isn't up to date any more

**Comment by A7med3bdulBaset** [comment] 2023-11-14 20:27
> They are published on the website: https://www.radix-ui.com/primitives/docs/overview/releases

The goal of GitHub releases is notifying/publishing in the timeline.

**Comment by benoitgrelard** [comment] 2024-02-29 11:01
Apologies, it looks like we missed the changelog for that latest public release, I will fix this now.
In the meantime, closing as duplicate of #2415

**Closed** 2024-02-29 11:02 UTC

**Comment by A7med3bdulBaset** [comment] 2024-02-29 14:33
Why not publish a release on Github so we can "watch releases" in order to receive notifications of the new releases. It could be done by a CI.

**Comment by benoitgrelard** [comment] 2024-02-29 14:35
Because there's a lot more that goes into a release, we like to document changes, create new examples, update each page to show the new versions, etc.

**Comment by A7med3bdulBaset** [comment] 2024-02-29 14:36
one more benefit is packages bots like renovate or dependabot attach the release notes and changelog.md in the updating PR
