### ISSUE TITLE
using hovercard, on mobile view, pressing the hovercard giving error message on chrome console "unable to preventDefault inside passive event listener invocation."

### ISSUE THREAD

**Issue by roniaxe** [radix-ui/primitives#2108] opened 2023-04-24 19:24 UTC
### Current Behavior

I am using hover card, working without any issues on desktop, however, moving into a mobile view, you have to click the hover card, but clicking it, creates the above error message, and the hover content does not show up.

![image](https://user-images.githubusercontent.com/19142347/234094886-61e93ea6-5603-4fda-8575-46a4425ca780.png)

### Expected behavior

I expect the hover card content to show up on click while in mobile view, just like hovering over in desktop shows up the content

### Reproducible example

This issue is happening even on the demo of that project, in this url:
https://tailwindcss-radix.vercel.app/

and the Github repo of that demo is:
https://github.com/ecklf/tailwindcss-radix/blob/main/demo/components/hover-card.tsx

### Suggested solution

If you can fix this issue, to make the hover card work (with a click) and show the content on mobile view, that will be a good solution.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-hover-card      |   1.0.5      |
| React            | 18     |     Latest    |
| Browser          |    Brave     |        Latest |
| Assistive tech   |         |         |
| Node             | Latest     |         |
| npm/yarn         |   yarn      |    1.22.19     |
| Operating System |  Windows 10 64x    |         |

**Comment by joaom00** [comment] 2023-04-25 02:18
Hey @roniaxe, I think it's by design that the hovercard doesn't open on click since the trigger must be an anchor so when the user clicks on the link it will be taken to another page so it doesn't make much sense to show the content when clicked. However, I believe you have reported a valid bug regarding the error that appears in the console.

**Comment by roniaxe** [comment] 2023-04-25 12:27
Hey @joaom00, Thanks for your reply! 
So in mobile view hover card is not an option ? Do you have any idea or workaround of how I can use the hover card to be kind of functional if on a mobile view ?

**Comment by joaom00** [comment] 2023-04-25 19:53
Although the hovercard opens when the link is focused, and looks like this should be prevented from what I've read of the code, but this is not happening and causing the console error, you can control the open state, with `open` and `onOpenChange` props, and handle to open whenever you want, but it seems weird to want to open the hovercard with a click on the mobile. What is your use case btw?

**Comment by benoitgrelard** [comment] 2023-04-27 08:57
> 

@joaom00 is correct here. `HoverCard` won't show on touch devices exactly as explained, same thing for tooltips for the same reasons. If you want similar'ish behaviour, you should probably use `Popover` instead.

I also haven't been able to reproduce the issue on the link you posted using the iOS simulator, or a real device so I will close the issue.

**Closed by benoitgrelard** 2023-04-27 08:57 UTC
