### ISSUE TITLE
Hydration issue with Alert Dialog primitive

### ISSUE THREAD

**Issue by AveryBuehler** [radix-ui/primitives#2008] opened 2023-03-08 05:42 UTC
I'm playing around with the Alert Dialog and I'm getting the following errors using Next.js `13.2.3` and AlertDialog `1.0.2`:
```
Warning: Expected server HTML to contain a matching <div> in <div>.
```
```
Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
```
```
Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>. 
```
```
Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```

The only difference between the documented example and my code is that I do not have an `AlertDialog.Trigger` component because I am setting `defaultOpen` to true on `AlertDialog.Root`. See below.

```js
 <AlertDialog.Root defaultOpen={true}>
      <AlertDialog.Portal>
        <AlertDialog.Overlay className="bg-blackA9 data-[state=open]:animate-overlayShow fixed inset-0" />
        <AlertDialog.Content className="data-[state=open]:animate-contentShow fixed top-[50%] left-[50%] max-h-[85vh] w-[90vw] max-w-[500px] translate-x-[-50%] translate-y-[-50%] rounded-[6px] bg-white p-[25px] shadow-[hsl(206_22%_7%_/_35%)_0px_10px_38px_-10px,_hsl(206_22%_7%_/_20%)_0px_10px_20px_-15px] focus:outline-none">
          <AlertDialog.Title className="text-mauve12 m-0 text-[17px] font-medium">
            Are you absolutely sure?
          </AlertDialog.Title>
          <AlertDialog.Description className="text-mauve11 mt-4 mb-5 text-[15px] leading-normal">
            This action cannot be undone. This will permanently delete your
            account and remove your data from our servers.
          </AlertDialog.Description>
          <div className="flex justify-end gap-[25px]">
            <AlertDialog.Cancel asChild>
              <button className="text-mauve11 bg-mauve4 hover:bg-mauve5 focus:shadow-mauve7 inline-flex h-[35px] items-center justify-center rounded-[4px] px-[15px] font-medium leading-none outline-none focus:shadow-[0_0_0_2px]">
                Cancel
              </button>
            </AlertDialog.Cancel>
            <AlertDialog.Action asChild>
              <button className="text-red11 bg-red4 hover:bg-red5 focus:shadow-red7 inline-flex h-[35px] items-center justify-center rounded-[4px] px-[15px] font-medium leading-none outline-none focus:shadow-[0_0_0_2px]">
                Yes, delete account
              </button>
            </AlertDialog.Action>
          </div>
        </AlertDialog.Content>
      </AlertDialog.Portal>
    </AlertDialog.Root>
```

Can someone provide any insight as to why I'm getting these errors? Thank you.

**Comment by joaom00** [comment] 2023-03-08 13:01
Duplicate of https://github.com/radix-ui/primitives/issues/1386

**Closed** 2023-03-08 13:13 UTC
Labels: Resolution: Duplicate
