### ISSUE TITLE
[Dialog] Closing controlled dialog does not return focus properly

### ISSUE THREAD

**Issue by pacocoursey** [radix-ui/primitives#419] opened 2021-02-01 21:46 UTC
### Current Behavior

When closing the Dialog via <kbd>Escape</kbd>, focus correctly restores to the trigger. However, if you activate and close the Dialog via a keybind, for example, closing the Dialog does not seem to restore focus anywhere. Even global event listeners on `window` do not work.

Here's an example:
- Open and close via click and Escape, works fine
- Open via ⌘K, listeners work while it's open
- Close via ⌘K, listeners stop working entirely
- Click on the body, listeners start working again

https://user-images.githubusercontent.com/34928425/106521620-bd165d00-649b-11eb-8c81-0718829016bb.mov

### Expected behavior

Focus should be restored to the body (or the trigger? not sure) in a way such that global window listeners still work. I'm not even sure how it's possible that it doesn't work right now.

### Reproducible example

https://codesandbox.io/s/infallible-curie-8gkof?file=/src/App.tsx

### Suggested solution

Change the way focus is restored on unmount

### Additional context

N/A

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |      dialog   |      0.0.5   |
| React            | n/a     |         |
| Browser          |     n/a    |         |
| Assistive tech   |    n/a     |         |
| Node             | n/a     |         |
| npm/yarn         |     n/a    |         |
| Operating System |   n/a      |         |

**Comment by benoitgrelard** [comment] 2021-02-02 09:48
Hi @pacocoursey, thanks for reporting this.

There are 2 things to look at here:

**1. The focus behaviour**

This is by design. The way the focus behaviour works is that it will return focus to where the `document.activeElement` was before. So if you activated it from the trigger, it will return there. In this case, when you are activating it straight away from anywhere, `document.activeElement` is `document.body` so it will return there.

But you can test that out by focusing the trigger first, then doing your shortcut, and you'll see it will return to the trigger.
I think these types of use cases are already a bit more fringe in terms of what should happen but I feel like, even as a keyboard user it makes sense for the focus to be returned where I was before invoking this `Dialog` via keyboard.

In any case, if for some reason you want to override this behaviour you totally can. Most of these things in our components can be changed by preventing the default behaviour and executing something else instead. Here that would be by doing this:

```jsx
<DialogContent
  onCloseAutoFocus={(event) => {
    event.preventDefault();
    refToSomethingYouWantToFocus.current?.focus(); // could be a ref to trigger if that's what you want
  }}
>
```

**2. The global key listener weirdness**

Now, with regards to the above and the consequence you see here. I believe you stumbled on a browser bug.
As far as I can tell, the same code works completely fine in Firefox and Safari but doesn't in Chrome (even though `document.activeElement` is `document.body` after closing it). I'm with you, I am not sure how that even is possible…

<img width="418" alt="Screenshot 2021-02-02 at 09 48 24" src="https://user-images.githubusercontent.com/1539897/106582356-d0790500-653b-11eb-9504-e04a6b5f9233.png">

**Comment by raunofreiberg** [comment] 2021-02-02 17:43
Hey @benoitgrelard,

Thanks for the elaborate and helpful answer!

Regarding #2:

Are you sure the issue is not somehow related to the dialog of Radix?

I replaced it with a dialog from Reach UI and opening via keyboard, then dismissing via <kbd>Escape> and re-opening works again.

[Here's the sandbox](https://codesandbox.io/s/intelligent-leaf-uv9k4?file=/src/App.tsx)

**Comment by benoitgrelard** [comment] 2021-02-02 18:20
hmmm… interesting 🤔  There might be more to it then.
I actually see one difference when monitoring `focusin`/`focusout` events on both examples.

In the case of reach, when closing via shortcut, I see no focus events at all raised.
In our case, I see a `focusin` and a `focusout`.

So perhaps there is something there? But still I don't understand why it would stop responding to keyboard events though, the `activeElement` is still `document.body` in all of the cases…

**Comment by benoitgrelard** [comment] 2021-02-02 18:28
I'm going to investigate this a little more, thanks for bringing this up @raunofreiberg!

**Comment by benoitgrelard** [comment] 2021-02-02 23:42
Hey! I found what sent Chrome into this weird state, however I still have no clue why Chrome is getting in such a state in the first place. Regardless we have a fix that prevents the specific series of events to happen. See #422.

I'll update this issue once it's released in the next cycle.

**Closed** 2021-02-03 12:09 UTC

**Comment by raunofreiberg** [comment] 2021-02-03 17:34
Thank you so much @benoitgrelard! ❤️

**Comment by benoitgrelard** [comment] 2021-02-08 11:31
Hi @raunofreiberg it'll be released sometime early this week.

**Comment by benoitgrelard** [comment] 2021-02-10 15:11
Hi @pacocoursey @raunofreiberg, I've just cut a new release of all primitives.
Can you try `@radix-ui/react-dialog@0.0.6` and confirm it's working as you expect?

Thanks!

**Comment by pacocoursey** [comment] 2021-02-10 17:52
Confirmed that it's working now, thanks!
