### ISSUE TITLE
[Tooltip] tooltip appears on browser tab switch

### ISSUE THREAD

**Issue by misha-erm** [radix-ui/primitives#2665] opened 2024-01-25 11:41 UTC
### Current Behavior

The tooltip becomes visible after browser tab switch

https://github.com/radix-ui/primitives/assets/8783498/08a1a5e1-a2ff-45a6-a7ec-1951377c5860

### Expected behavior

Tooltip shouldn't become visible if it was hidden already (e.g. clicked on a trigger)

### Reproducible example

It can be reproduced in Radix playground https://www.radix-ui.com/primitives/docs/components/tooltip

### Suggested solution

Maybe detect somehow focus events coming from 'visibilitychange'...

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-tooltip     |     1.0.6    |
| React            | n/a     |     18.2.0    |
| Browser          |   Brave      |     1.61.104    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |    MacOS     |      Sonoma 14.3   |

**Comment by benoitgrelard** [comment] 2024-03-05 10:31
Duplicate of #1800

**Closed by benoitgrelard** 2024-03-05 10:31 UTC
Labels: Resolution: Duplicate, Package: react/tooltip
