### ISSUE TITLE
DropdownMenu SubContent  not close

### ISSUE THREAD

**Issue by Soya-xy** [radix-ui/primitives#2652] opened 2024-01-16 08:14 UTC
## Bug report
When there are multiple DropdownMenuSubs, the mouse plays them back and forth, and the SubContent is sometimes not closed
### Reproducible example

https://github.com/radix-ui/primitives/assets/56671014/b717f55f-002c-4f9e-8fce-4c5183f81c73
```jsx
const SortBy = () => {
  const [open, setOpen] = useState(false);
  const menu = [
    {
      name: "Featured",
    },
    {
      name: "Release Date",
      sub: [
        {
          name: "Old - New",
        },
        {
          name: "New - Old",
        }
      ]
    },
    {
      name: "Volatility",
      sub: [
        {
          name: "Low - High",
        },
        {
          name: "High - Low",
        }
      ]
    },
    {
      name: "RTP",
      sub: [
        {
          name: "Low - High",
        },
        {
          name: "High - Low",
        }
      ]
    },
    {
      name: "Maximum Win",
      sub: [
        {
          name: "Low - High",
        },
        {
          name: "High - Low",
        }
      ]
    }
  ]
  return (
    <DropdownMenu.Root onOpenChange={(e) => setOpen(e)} >
      <DropdownMenu.Trigger asChild>
        <button className="flex items-center" aria-label="Customise options">
          Featured {open ? <ChevronUpIcon /> : <ChevronDownIcon />}
        </button>
      </DropdownMenu.Trigger>

      <DropdownMenu.Portal>
        <DropdownMenu.Content className="DropdownMenuContent" sideOffset={5}>
          {menu.map((item, index) => {
            return <Fragment  key={index}>
              {!item.sub ?
                <DropdownMenu.Item className="DropdownMenuItem">
                  <p>{item.name}</p>
                </DropdownMenu.Item>
                : (
                  <DropdownMenu.Sub>
                    <DropdownMenu.SubTrigger className="!flex !items-center !justify-between !pl-[20px] !pr-[5px] w-full DropdownMenuItem">
                      <p>{item.name}</p>
                      <div className="RightSlot">
                        <ChevronRightIcon />
                      </div>
                    </DropdownMenu.SubTrigger>
                    <DropdownMenu.Portal>
                      <DropdownMenu.SubContent
                        className="DropdownMenuSubContent"
                        sideOffset={2}
                        alignOffset={-5}
                      >
                        {item.sub && item.sub.map((subItem, subIndex) => {
                          return <Fragment key={subIndex}>
                            <DropdownMenu.Item className="DropdownMenuItem" >
                              <p>{subItem.name}</p>
                            </DropdownMenu.Item>
                            {subIndex !== item.sub.length - 1 &&
                              <DropdownMenu.Separator className="DropdownMenuSeparator" />
                            }
                          </Fragment>
                        })}
                      </DropdownMenu.SubContent>
                    </DropdownMenu.Portal>
                  </DropdownMenu.Sub>
                )
              }
              {index !== menu.length - 1 &&
                <DropdownMenu.Separator className="DropdownMenuSeparator" />
              }
            </Fragment>
          })}

        </DropdownMenu.Content>
      </DropdownMenu.Portal>
    </DropdownMenu.Root>
  )
}
  
  
```

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |

| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment] 2024-03-06 11:38
@Soya-xy the codesandbox is empty.
This is likely an issue with your CSS or your particular setup.

On top of our docs example, you can see another working example here in our storybook: https://601857eb614bae0021c9b9dd-evgfcrkbbq.chromatic.com/?path=/story/components-dropdownmenu--submenus

https://github.com/radix-ui/primitives/assets/1539897/2e7bf559-0519-40af-a237-7c8aa0857103

I will close the issue as I cannot reproduce your problem, but if you have a sandbox which shows the issue consistently I'm happy to take a look.

**Closed by benoitgrelard** 2024-03-06 11:38 UTC
