### ISSUE TITLE
[DropdownMenu] Item hover and focus styles are merged on hover state

### ISSUE THREAD

**Issue by colepeters** [radix-ui/primitives#956] opened 2021-11-04 16:02 UTC
### Current Behavior

I've defined distinct hover and focus styles for my DropdownMenu.Item component. When I hover over one of these items, the resulting style is a merge of my hover _and_ focus styles. If I then switch to using the arrow keys, the focused item only displays the focus styles.

### Expected behavior

Hover styles should be rendered on hover, focus styles should be rendered on focus. The two should not be merged.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/morning-sun-tyibr?file=/src/App.js)

### Suggested solution

I'm guessing this is a side effect of the focus management for this component? As in, it seems the focus state is being triggered programatically when hovering — which I presume to be a feature, not a bug. However, I can't seem to find any documentation or explanation of this, so I'm not sure. Which means I'm also not sure what a potential solution might be 🤔

### Additional context

I managed to create the styles I needed by overriding the forced focus styles within my hover styles with `!important`s, but it makes me feel dirty 😅

There also seems to be a growing consensus among UI designers that hover and focus states should have distinct styles, so this does present a bit of a challenge for achieving that.

Having said that, perhaps there are more critical accessibility concerns that are being solved by focus states activating on hover for these items, so I'm happy to be enlightened on this if I'm barking up the wrong tree!

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-dropdown-menu       |  0.1.1       |
| React            | n/a     |   17.0.1      |
| Browser          |  Chrome, Safari       |  Latest       |
| Assistive tech   |  n/a       |  n/a       |
| Node             | n/a     |   14.x      |
| npm/yarn         |   npm      | 7.x        |
| Operating System |   macOS      | 11.6        |

**Comment by benoitgrelard** [comment] 2021-11-05 11:31
HI @colepeters, thanks for raising this.

You are right in assuming that this is a feature and not a bug.
This is in fact by design and there is a very good reason for it in terms of accessibility.
That's something a lot of dropdown implementations get wrong to be honest.

The reason is that if you can have 2 "highlighted" styles triggered by 2 different modes (focus/hover) you can end up in situations where 2 items appear highlighted which becomes very confusing for the user as to which item is currently highlighted. It's hard to understand where it will go if I press arrow down.

That really ought to be an impossible state, because only 1 item can be the currently highlighted one.
In fact, from the stand point of the dropdown, there really is only 1 state, that's "highlighted". The fact that it's using focus, or anything else is more of an implementation detail. For example, we may have used `aria-activedescendant` instead of roving focus for the implementation.

If anything it makes me wonder whether we should actually abstract that state like we do with other states with a `data-state` attribute or similar…

> There also seems to be a growing consensus among UI designers that hover and focus states should have distinct styles, so this does present a bit of a challenge for achieving that.

I would agree with that for things like buttons, etc but I struggle to see how that would apply here without creating more confusion. Especially given it only applies to a multi-modal use anyway (pointer + keyboard).

Let me know if that explanation makes sense to you.

**Comment by colepeters** [comment] 2021-11-05 17:27
Thanks @benoitgrelard, this is some great insight, and makes total sense. I'm also realizing this mirrors exactly the behaviour of native dropdown UIs, where there's only a single hover/focus state which is managed by both keyboard and pointer interactions.

It's funny how you can work in web UI development for ages and never realize the little patterns you've gotten stuck into that actually don't make sense — as you say, so many dropdown implementations get this wrong, and I'm certainly guilty of doing that myself. Having considered these points has been really eye-opening, so thank you!

The point you made about abstracting this state via a data attribute also makes sense to me. The merger of the hover/focus styles was a surprise to me when using this component for the first time, so perhaps even just making this behaviour clearer in the documentation would be a help. But I can also see establishing a pattern for setting these styles via data attributes could be more consistent with the component's implementation (as opposed to writing focus styles which 'magically' get applied on hover). But perhaps this is a subtle point that I'm overthinking.

If you'd like to close this issue (as it doesn't require 'fixing'), by all means feel free. Thanks again!

**Comment by benoitgrelard** [comment] 2021-11-08 10:40
@jjenzz @andy-hook, I wonder if we should abstract that state somehow, writing this definitely made me think of it as it's really an implementation detail. But I'm worried we're gonna expose ourself more and more to `data-state` clashes too.

**Comment by jjenzz** [comment] 2021-11-08 12:05
I would be on board with a `data-active` attribute or something (similar to `data-disabled`) as I have also wondered in the past why we move focus like this. It makes sense from a "visual" perspective that two things should not be highlighted at the same time, but doesn't make sense from an "input" perspective to me. What I mean is, pointer input tends not to move focus.

**Comment by benoitgrelard** [comment] 2021-11-08 13:49
Ah yeah that's a good point, we do that for disabled too.
That sounds like a good plan to me, would definitely makes things clearer and rely less on implementation.

**Comment by colepeters** [comment] 2021-11-08 17:25
For what it's worth, from the standpoint of a new user of this library, `data-active` makes a lot of sense to me, as does leaving the option open for state variable attributes like `data-state=open`, should someone wish to style an open submenu trigger distinctly. Really appreciate all the thinking that goes into these components!

**Comment by benoitgrelard** [comment] 2022-03-31 12:44
I am closing this issue now as I have captured the request for the enhancement in a new issue: #1289

**Closed by benoitgrelard** 2022-03-31 12:44 UTC
Labels: enhancement
