### ISSUE TITLE
[DropdownMenu] DropdownMenu.Item with `as="a"` doesn't work as expected

### ISSUE THREAD

**Issue by smhutch** [radix-ui/primitives#556] opened 2021-03-15 10:03 UTC
### Current Behavior

When using `DropdownMenu.Item` with `as="a"`, the link cannot be navigated to unless an `onSelect` callback is passed which internally calls `preventDefault()`

```jsx
<>
<DropdownMenu.Item as="a" href="https://www.example.com">
  Link won't work, it just closes the dropdown
</DropdownMenu.Item>
<DropdownMenu.Item as="a" href="https://www.example.com" onSelect={(e) => e.preventDefault}>
   Works, but feels complicated
</DropdownMenu.Item>
</>
```

### Expected behavior

Support DropdownMenu item links with only an `as` prop:

```jsx
<DropdownMenu.Item as="a" href="https://www.example.com">
  Example link
</DropdownMenu.Item>
```

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/radix-dropdown-with-link-1x16v?file=/src/App.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-dropdown-menu       |   0.0.10      |
| React            | 17     |         |
| Browser          |  FF       |         |
| Assistive tech   |  n/a       |         |
| Node             | 14.     |         |
| npm/yarn         |  yarn      |         |
| Operating System | macOs  |      11.2.1   |

**Comment by benoitgrelard** [comment] 2021-03-15 10:47
Hey @smhutch, thanks for reporting the issue.

I can reproduce is with the version you are using, however good news, I cannot reproduce it in our `main` branch so it looks like it was resolved already and will be part of the next release cycle.

@jjenzz, I think it was probably fixed by this one: #548

**Comment by smhutch** [comment] 2021-03-15 11:12
Awesome, thank you @benoitgrelard & @jjenzz

**Comment by benoitgrelard** [comment] 2021-05-13 12:44
After reading [this](https://discord.com/channels/752614004387610674/803656530259738674/842379565694189589) and trying it, I realised it seems this issue is back so I'm reopening it.

**Comment by jjenzz** [comment] 2021-09-15 12:04
This was fixed by https://github.com/radix-ui/primitives/pull/818 and available in the Beta release.

**Closed by jjenzz** 2021-09-15 12:04 UTC
