### ISSUE TITLE
Popover Content cant be scrolled in a Dialog.

### ISSUE THREAD

**Issue by nmhieu1896** [radix-ui/primitives#2028] opened 2023-03-17 02:53 UTC
## Bug report
If a popover content is set as overflow, it's not working inside a dialog
This is a demo for it. Two popover with overflow, the one outside the dialog is scrollable but the one inside is not.

### Reproducible example
https://codesandbox.io/s/hungry-faraday-2ilw12?file=/src/App.js

P/s: If there's some workaround for this, please teach me. Thanks

**Comment by joaom00** [comment] 2023-03-17 03:15
Duplicate of #1159 

In the meantime, you can remove the `Portal` part from `Popover`.

**Comment by nmhieu1896** [comment] 2023-03-17 04:15
Niceeeeee, Cant believe I spend a day working around without noticing portal. 
Thank you so much!

**Closed** 2023-03-17 05:49 UTC

**Comment by xidoke** [comment] 2025-01-08 10:59
why shadcn don't fix that now?

**Comment by pushpak-angularminds** [comment] 2025-02-16 16:48
https://github.com/nmhieu1896 - same, i also spent my whole sunday and finally came up with this two level format seelctor.

![Image](https://github.com/user-attachments/assets/47707e72-bba1-4cea-9f6a-0f2d77a74264)

![Image](https://github.com/user-attachments/assets/2afadfc2-a334-4dc9-99a0-fe3dd6499f45)

`const formats = [
  {
    value: "text",
    label: "Text",
    subFormats: [
      { value: "text-plain", label: "Plain Text" },
      { value: "text-uppercase", label: "UPPERCASE" },
      { value: "text-lowercase", label: "lowercase" },
      { value: "text-capitalize", label: "Capitalize Each Word" },
      { value: "text-ssn", label: "SSN (XXX-XX-XXXX)" },
      { value: "text-ein", label: "EIN (XX-XXXXXXX)" },
      { value: "text-policy-number", label: "Policy Number" },
      { value: "text-license", label: "License Number" }
    ]
  },
  {
    value: "number",
    label: "Number",
    subFormats: [
      { value: "number-plain", label: "Plain" },
      { value: "number-decimal-1", label: "1 Decimal Place" },
      { value: "number-decimal-2", label: "2 Decimal Places" },
      { value: "number-decimal-4", label: "4 Decimal Places" },
      { value: "number-percentage", label: "Percentage" },
    ]
  },
  {
    value: "phone",
    label: "Phone",
    subFormats: [
      { value: "phone-intl", label: "International (+XX XXX XXX XXXX)" },
      { value: "phone-us", label: "US (XXX-XXX-XXXX)" },
      { value: "phone-uk", label: "UK (+44 XXXX XXXXXX)" },
      { value: "phone-in", label: "India (+91 XXXXX XXXXX)" },
      { value: "phone-au", label: "Australia (+61 XXXX XXX XXX)" },
      { value: "phone-jp", label: "Japan (+81 XX XXXX XXXX)" },
      { value: "phone-br", label: "Brazil (+55 XX XXXXX-XXXX)" },
      { value: "phone-de", label: "Germany (+49 XXXX XXXXXXX)" },
      { value: "phone-fr", label: "France (+33 X XX XX XX XX)" },
      { value: "phone-it", label: "Italy (+39 XXX XXX XXXX)" },
      { value: "phone-cn", label: "China (+86 XXX XXXX XXXX)" },
      { value: "phone-ru", label: "Russia (+7 XXX XXX-XX-XX)" },
      { value: "phone-za", label: "South Africa (+27 XX XXX XXXX)" },
      { value: "phone-mx", label: "Mexico (+52 XXX XXX XXXX)" },
      { value: "phone-sa", label: "Saudi Arabia (+966 X XXX XXXX)" },
      { value: "phone-ng", label: "Nigeria (+234 XXX XXX XXXX)" },
      { value: "phone-es", label: "Spain (+34 XXX XXX XXX)" }
    ],
  },
  {
    value: "date",
    label: "Date",
    subFormats: [
      // Standard International Formats
      { value: "date-mm/dd/yyyy", label: "MM/DD/YYYY (US)" },
      { value: "date-dd/mm/yyyy", label: "DD/MM/YYYY (EU, Asia)" },
      { value: "date-yyyy-mm-dd", label: "YYYY-MM-DD (ISO 8601)" },

      // Month and Year Only
      { value: "date-mm/yyyy", label: "MM/YYYY" },
      { value: "date-mmm/yyyy", label: "MMM/YYYY (e.g., Jan/2025)" },
      { value: "date-yyyy/mm", label: "YYYY/MM (Japanese)" },

      // Text Month Formats
      { value: "date-dd-mmm-yyyy", label: "DD-MMM-YYYY (e.g., 01-Jan-2025)" },
      { value: "date-mmm-dd-yyyy", label: "MMM DD, YYYY (e.g., Jan 01, 2025)" },
      { value: "date-full", label: "Full Date (e.g., Monday, January 1, 2025)" },

      // Different Separators
      { value: "date-dd.mm.yyyy", label: "DD.MM.YYYY (European)" },
      { value: "date-dd-mm-yyyy", label: "DD-MM-YYYY (UK, India)" },
      { value: "date-yyyy.mm.dd", label: "YYYY.MM.DD (Korean)" },

      // Short Formats
      { value: "date-d/m/yy", label: "D/M/YY (e.g., 1/1/25)" },
      { value: "date-dd/mm/yy", label: "DD/MM/YY (e.g., 01/01/25)" },
      { value: "date-yy/mm/dd", label: "YY/MM/DD (e.g., 25/01/01)" },

      // Time-Based Formats
      { value: "date-yyyy-mm-dd-hh-mm", label: "YYYY-MM-DD HH:MM (24h)" },
      { value: "date-yyyy-mm-dd-hh-mm-ss", label: "YYYY-MM-DD HH:MM:SS" },
      { value: "date-mm/dd/yyyy-hh-mm-am", label: "MM/DD/YYYY HH:MM AM/PM (12h)" },

      // Specialized Formats
      { value: "date-quarter-yyyy", label: "Q YYYY (e.g., Q1 2025)" },
      { value: "date-week-yyyy", label: "Week YYYY (e.g., Week 01 2025)" },
      { value: "date-mmm-yyyy-week", label: "MMM YYYY (Week W) (e.g., Jan 2025 (Week 1))" },

      // Relative Formats
      { value: "date-relative-days", label: "X days ago/from now" },
      { value: "date-relative-weeks", label: "X weeks ago/from now" },
      { value: "date-relative-months", label: "X months ago/from now" },

      // Buddhist Calendar
      { value: "date-buddhist-yyyy", label: "Buddhist Year (YYYY+543)" },
      { value: "date-buddhist-full", label: "Buddhist Full Date" },

      // Islamic Calendar
      { value: "date-hijri", label: "Hijri Date" },

      // Fiscal/Academic Year
      { value: "date-fiscal-yyyy", label: "FY YYYY" },
      { value: "date-academic-yyyy", label: "AY YYYY-YYYY" },

      // Season-based
      { value: "date-season-yyyy", label: "Season YYYY (e.g., Spring 2025)" }
    ]
  },
  {
    value: "currency",
    label: "Currency",
    subFormats: [
      { value: "currency-usd", label: "USD ($) - United States" },
      { value: "currency-eur", label: "EUR (€) - European Union" },
      { value: "currency-gbp", label: "GBP (£) - United Kingdom" },
      { value: "currency-jpy", label: "JPY (¥) - Japan" },
      { value: "currency-inr", label: "INR (₹) - India" },
      { value: "currency-aud", label: "AUD (A$) - Australia" },
      { value: "currency-cad", label: "CAD (C$) - Canada" },
      { value: "currency-chf", label: "CHF (Fr.) - Switzerland" },
      { value: "currency-cny", label: "CNY (¥) - China" },
      { value: "currency-brl", label: "BRL (R$) - Brazil" },
      { value: "currency-rub", label: "RUB (₽) - Russia" },
      { value: "currency-zar", label: "ZAR (R) - South Africa" },
      { value: "currency-sgd", label: "SGD (S$) - Singapore" },
      { value: "currency-krw", label: "KRW (₩) - South Korea" },
      { value: "currency-mxn", label: "MXN ($) - Mexico" },
    ],
  },
  {
    value: "percentage",
    label: "Percentage",
    subFormats: [
      { value: "percentage-whole", label: "Whole (25%)" },
      { value: "percentage-decimal", label: "Decimal (25.5%)" },
      { value: "percentage-fraction", label: "Fraction (¼)" }
    ]
  },
  {
    value: "zip",
    label: "ZIP",
    subFormats: [
      { value: "zip-us", label: "US (XXXXX or XXXXX-XXXX)" },
      { value: "zip-ca", label: "Canada (A1A 1A1)" },
      { value: "zip-uk", label: "UK (A1 1AA or AA1 1AA)" },
      { value: "zip-au", label: "Australia (XXXX)" },
      { value: "zip-in", label: "India (XXXXXX)" },
      { value: "zip-jp", label: "Japan (XXX-XXXX)" },
      { value: "zip-de", label: "Germany (XXXXX)" },
      { value: "zip-fr", label: "France (XXXXX)" },
      { value: "zip-br", label: "Brazil (XXXXX-XXX)" },
      { value: "zip-it", label: "Italy (XXXXX)" }
    ]
  },
]


import React from 'react';
import * as Popover from '@radix-ui/react-popover';
import { ChevronLeft, ChevronRight } from "lucide-react"
import { Button } from "@/components/ui/button";
import { IconTextSize } from "@tabler/icons-react";

interface SubFormat {
  value: string;
  label: string;
}

interface Format {
  value: string;
  label: string;
  subFormats: SubFormat[];
}

interface FormatSelectorProps {
  value: string
  onValueChange: (value: string) => void
}


export function FormatSelector({ value, onValueChange }: FormatSelectorProps) {
  const [isOpen, setIsOpen] = React.useState(false);
  const [selectedMainFormat, setSelectedMainFormat] = React.useState<Format | null>(null);

  const selectedFormat = React.useMemo(() => {
    if (!value) return null;
    for (const format of formats) {
      const subFormat = format?.subFormats?.find(sf => sf.value === value);
      if (subFormat) {
        return {
          main: format,
          sub: subFormat
        };
      }
    }
    return null;
  }, [value]);

  const handleMainFormatSelect = (format: Format) => {
    setSelectedMainFormat(format);
  };

  const handleSubFormatSelect = (subFormatValue: string) => {
    onValueChange(subFormatValue);
    setSelectedMainFormat(null);
    setIsOpen(false);
  };

  return (
    <Popover.Root open={isOpen} onOpenChange={setIsOpen}>
      <Popover.Trigger asChild>
        <Button
          variant="outline"
          role="combobox"
          className='hover:bg-slate-100'
        >
          <IconTextSize stroke={2} />
        </Button>
        {/* <Button
          variant="outline"
          className="w-[280px] justify-between"
          role="combobox"
        >
          <div className="flex items-center">
            <IconTextSize className="w-4 h-4 mr-2" />
            <span>{selectedFormat?.sub.label || "Select Format"}</span>
          </div>
          <IconTextSize stroke={2} />
        </Button> */}
      </Popover.Trigger>

      {/* <Popover.Portal> */}
      <Popover.Content
        className="z-50 min-w-[200px] max-w-[280px] rounded-md border bg-popover text-popover-foreground shadow-md animate-in data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2"
        align="start"
        sideOffset={5}
      >
        <div className="flex flex-col">
          {selectedMainFormat && (
            <button
              className="flex w-full items-center px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground border-b sticky top-0 bg-popover"
              onClick={() => setSelectedMainFormat(null)}
            >
              <ChevronLeft className="w-4 h-4 mr-1" />
              Back to formats
            </button>
          )}

          <div className=" max-h-[280px] min-w-[200px]  overflow-y-auto ">
            {selectedMainFormat ? (
              <div className="p-1">
                {selectedMainFormat.subFormats.map((subFormat) => (
                  <button
                    key={subFormat.value}
                    className="w-full px-4 py-2 text-sm text-left rounded hover:bg-accent hover:text-accent-foreground"
                    onClick={() => handleSubFormatSelect(subFormat.value)}
                  >
                    {subFormat.label}
                  </button>
                ))}
              </div>
            ) : (
              <div className="p-1">
                {formats.map((format) => (
                  <button
                    key={format.value}
                    className="flex w-full items-center justify-between px-4 py-2 text-sm rounded hover:bg-accent hover:text-accent-foreground"
                    onClick={() => handleMainFormatSelect(format)}
                  >
                    <span>{format.label}</span>
                    <ChevronRight className="w-4 h-4 mr-1" />
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </Popover.Content>
      {/* </Popover.Portal> */}
    </Popover.Root>
  );
}

`

**Comment by Pushpak-bhoite** [comment] 2025-02-16 17:41
> Niceeeeee, Cant believe I spend a day working around without noticing portal. Thank you so much!

 same brother, i also spent my whole my sunday and finally came up with this two level format selector.

![Image](https://github.com/user-attachments/assets/47707e72-bba1-4cea-9f6a-0f2d77a74264)

![Image](https://github.com/user-attachments/assets/2afadfc2-a334-4dc9-99a0-fe3dd6499f45)

`const formats = [
  {
    value: "text",
    label: "Text",
    subFormats: [
      { value: "text-plain", label: "Plain Text" },
      { value: "text-uppercase", label: "UPPERCASE" },
      { value: "text-lowercase", label: "lowercase" },
      { value: "text-capitalize", label: "Capitalize Each Word" },
      { value: "text-ssn", label: "SSN (XXX-XX-XXXX)" },
      { value: "text-ein", label: "EIN (XX-XXXXXXX)" },
      { value: "text-policy-number", label: "Policy Number" },
      { value: "text-license", label: "License Number" }
    ]
  },
  {
    value: "number",
    label: "Number",
    subFormats: [
      { value: "number-plain", label: "Plain" },
      { value: "number-decimal-1", label: "1 Decimal Place" },
      { value: "number-decimal-2", label: "2 Decimal Places" },
      { value: "number-decimal-4", label: "4 Decimal Places" },
      { value: "number-percentage", label: "Percentage" },
    ]
  },
  {
    value: "phone",
    label: "Phone",
    subFormats: [
      { value: "phone-intl", label: "International (+XX XXX XXX XXXX)" },
      { value: "phone-us", label: "US (XXX-XXX-XXXX)" },
      { value: "phone-uk", label: "UK (+44 XXXX XXXXXX)" },
      { value: "phone-in", label: "India (+91 XXXXX XXXXX)" },
      { value: "phone-au", label: "Australia (+61 XXXX XXX XXX)" },
      { value: "phone-jp", label: "Japan (+81 XX XXXX XXXX)" },
      { value: "phone-br", label: "Brazil (+55 XX XXXXX-XXXX)" },
      { value: "phone-de", label: "Germany (+49 XXXX XXXXXXX)" },
      { value: "phone-fr", label: "France (+33 X XX XX XX XX)" },
      { value: "phone-it", label: "Italy (+39 XXX XXX XXXX)" },
      { value: "phone-cn", label: "China (+86 XXX XXXX XXXX)" },
      { value: "phone-ru", label: "Russia (+7 XXX XXX-XX-XX)" },
      { value: "phone-za", label: "South Africa (+27 XX XXX XXXX)" },
      { value: "phone-mx", label: "Mexico (+52 XXX XXX XXXX)" },
      { value: "phone-sa", label: "Saudi Arabia (+966 X XXX XXXX)" },
      { value: "phone-ng", label: "Nigeria (+234 XXX XXX XXXX)" },
      { value: "phone-es", label: "Spain (+34 XXX XXX XXX)" }
    ],
  },
  {
    value: "date",
    label: "Date",
    subFormats: [
      // Standard International Formats
      { value: "date-mm/dd/yyyy", label: "MM/DD/YYYY (US)" },
      { value: "date-dd/mm/yyyy", label: "DD/MM/YYYY (EU, Asia)" },
      { value: "date-yyyy-mm-dd", label: "YYYY-MM-DD (ISO 8601)" },

      // Month and Year Only
      { value: "date-mm/yyyy", label: "MM/YYYY" },
      { value: "date-mmm/yyyy", label: "MMM/YYYY (e.g., Jan/2025)" },
      { value: "date-yyyy/mm", label: "YYYY/MM (Japanese)" },

      // Text Month Formats
      { value: "date-dd-mmm-yyyy", label: "DD-MMM-YYYY (e.g., 01-Jan-2025)" },
      { value: "date-mmm-dd-yyyy", label: "MMM DD, YYYY (e.g., Jan 01, 2025)" },
      { value: "date-full", label: "Full Date (e.g., Monday, January 1, 2025)" },

      // Different Separators
      { value: "date-dd.mm.yyyy", label: "DD.MM.YYYY (European)" },
      { value: "date-dd-mm-yyyy", label: "DD-MM-YYYY (UK, India)" },
      { value: "date-yyyy.mm.dd", label: "YYYY.MM.DD (Korean)" },

      // Short Formats
      { value: "date-d/m/yy", label: "D/M/YY (e.g., 1/1/25)" },
      { value: "date-dd/mm/yy", label: "DD/MM/YY (e.g., 01/01/25)" },
      { value: "date-yy/mm/dd", label: "YY/MM/DD (e.g., 25/01/01)" },

      // Time-Based Formats
      { value: "date-yyyy-mm-dd-hh-mm", label: "YYYY-MM-DD HH:MM (24h)" },
      { value: "date-yyyy-mm-dd-hh-mm-ss", label: "YYYY-MM-DD HH:MM:SS" },
      { value: "date-mm/dd/yyyy-hh-mm-am", label: "MM/DD/YYYY HH:MM AM/PM (12h)" },

      // Specialized Formats
      { value: "date-quarter-yyyy", label: "Q YYYY (e.g., Q1 2025)" },
      { value: "date-week-yyyy", label: "Week YYYY (e.g., Week 01 2025)" },
      { value: "date-mmm-yyyy-week", label: "MMM YYYY (Week W) (e.g., Jan 2025 (Week 1))" },

      // Relative Formats
      { value: "date-relative-days", label: "X days ago/from now" },
      { value: "date-relative-weeks", label: "X weeks ago/from now" },
      { value: "date-relative-months", label: "X months ago/from now" },

      // Buddhist Calendar
      { value: "date-buddhist-yyyy", label: "Buddhist Year (YYYY+543)" },
      { value: "date-buddhist-full", label: "Buddhist Full Date" },

      // Islamic Calendar
      { value: "date-hijri", label: "Hijri Date" },

      // Fiscal/Academic Year
      { value: "date-fiscal-yyyy", label: "FY YYYY" },
      { value: "date-academic-yyyy", label: "AY YYYY-YYYY" },

      // Season-based
      { value: "date-season-yyyy", label: "Season YYYY (e.g., Spring 2025)" }
    ]
  },
  {
    value: "currency",
    label: "Currency",
    subFormats: [
      { value: "currency-usd", label: "USD ($) - United States" },
      { value: "currency-eur", label: "EUR (€) - European Union" },
      { value: "currency-gbp", label: "GBP (£) - United Kingdom" },
      { value: "currency-jpy", label: "JPY (¥) - Japan" },
      { value: "currency-inr", label: "INR (₹) - India" },
      { value: "currency-aud", label: "AUD (A$) - Australia" },
      { value: "currency-cad", label: "CAD (C$) - Canada" },
      { value: "currency-chf", label: "CHF (Fr.) - Switzerland" },
      { value: "currency-cny", label: "CNY (¥) - China" },
      { value: "currency-brl", label: "BRL (R$) - Brazil" },
      { value: "currency-rub", label: "RUB (₽) - Russia" },
      { value: "currency-zar", label: "ZAR (R) - South Africa" },
      { value: "currency-sgd", label: "SGD (S$) - Singapore" },
      { value: "currency-krw", label: "KRW (₩) - South Korea" },
      { value: "currency-mxn", label: "MXN ($) - Mexico" },
    ],
  },
  {
    value: "percentage",
    label: "Percentage",
    subFormats: [
      { value: "percentage-whole", label: "Whole (25%)" },
      { value: "percentage-decimal", label: "Decimal (25.5%)" },
      { value: "percentage-fraction", label: "Fraction (¼)" }
    ]
  },
  {
    value: "zip",
    label: "ZIP",
    subFormats: [
      { value: "zip-us", label: "US (XXXXX or XXXXX-XXXX)" },
      { value: "zip-ca", label: "Canada (A1A 1A1)" },
      { value: "zip-uk", label: "UK (A1 1AA or AA1 1AA)" },
      { value: "zip-au", label: "Australia (XXXX)" },
      { value: "zip-in", label: "India (XXXXXX)" },
      { value: "zip-jp", label: "Japan (XXX-XXXX)" },
      { value: "zip-de", label: "Germany (XXXXX)" },
      { value: "zip-fr", label: "France (XXXXX)" },
      { value: "zip-br", label: "Brazil (XXXXX-XXX)" },
      { value: "zip-it", label: "Italy (XXXXX)" }
    ]
  },
]


import React from 'react';
import * as Popover from '@radix-ui/react-popover';
import { ChevronLeft, ChevronRight } from "lucide-react"
import { Button } from "@/components/ui/button";
import { IconTextSize } from "@tabler/icons-react";

interface SubFormat {
  value: string;
  label: string;
}

interface Format {
  value: string;
  label: string;
  subFormats: SubFormat[];
}

interface FormatSelectorProps {
  value: string
  onValueChange: (value: string) => void
}


export function FormatSelector({ value, onValueChange }: FormatSelectorProps) {
  const [isOpen, setIsOpen] = React.useState(false);
  const [selectedMainFormat, setSelectedMainFormat] = React.useState<Format | null>(null);

  const selectedFormat = React.useMemo(() => {
    if (!value) return null;
    for (const format of formats) {
      const subFormat = format?.subFormats?.find(sf => sf.value === value);
      if (subFormat) {
        return {
          main: format,
          sub: subFormat
        };
      }
    }
    return null;
  }, [value]);

  const handleMainFormatSelect = (format: Format) => {
    setSelectedMainFormat(format);
  };

  const handleSubFormatSelect = (subFormatValue: string) => {
    onValueChange(subFormatValue);
    setSelectedMainFormat(null);
    setIsOpen(false);
  };

  return (
    <Popover.Root open={isOpen} onOpenChange={setIsOpen}>
      <Popover.Trigger asChild>
        <Button
          variant="outline"
          role="combobox"
          className='hover:bg-slate-100'
        >
          <IconTextSize stroke={2} />
        </Button>
        {/* <Button
          variant="outline"
          className="w-[280px] justify-between"
          role="combobox"
        >
          <div className="flex items-center">
            <IconTextSize className="w-4 h-4 mr-2" />
            <span>{selectedFormat?.sub.label || "Select Format"}</span>
          </div>
          <IconTextSize stroke={2} />
        </Button> */}
      </Popover.Trigger>

      {/* <Popover.Portal> */}
      <Popover.Content
        className="z-50 min-w-[200px] max-w-[280px] rounded-md border bg-popover text-popover-foreground shadow-md animate-in data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2"
        align="start"
        sideOffset={5}
      >
        <div className="flex flex-col">
          {selectedMainFormat && (
            <button
              className="flex w-full items-center px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground border-b sticky top-0 bg-popover"
              onClick={() => setSelectedMainFormat(null)}
            >
              <ChevronLeft className="w-4 h-4 mr-1" />
              Back to formats
            </button>
          )}

          <div className=" max-h-[280px] min-w-[200px]  overflow-y-auto ">
            {selectedMainFormat ? (
              <div className="p-1">
                {selectedMainFormat.subFormats.map((subFormat) => (
                  <button
                    key={subFormat.value}
                    className="w-full px-4 py-2 text-sm text-left rounded hover:bg-accent hover:text-accent-foreground"
                    onClick={() => handleSubFormatSelect(subFormat.value)}
                  >
                    {subFormat.label}
                  </button>
                ))}
              </div>
            ) : (
              <div className="p-1">
                {formats.map((format) => (
                  <button
                    key={format.value}
                    className="flex w-full items-center justify-between px-4 py-2 text-sm rounded hover:bg-accent hover:text-accent-foreground"
                    onClick={() => handleMainFormatSelect(format)}
                  >
                    <span>{format.label}</span>
                    <ChevronRight className="w-4 h-4 mr-1" />
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </Popover.Content>
      {/* </Popover.Portal> */}
    </Popover.Root>
  );
}

`
