### ISSUE TITLE
Changelog/docs about major release?

### ISSUE THREAD

**Issue by wottpal** [radix-ui/primitives#2465] opened 2023-10-18 13:34 UTC
Hey there, it seems to be a `@radix-ui/react-select` v2.0.0 in the npm registry (https://www.npmjs.com/package/@radix-ui/react-select?activeTab=versions) but neither here in the repository, on the documentation website, or anywhere else I'm able to find some kind of documentation about potentially breaking changes etc.

Would be happy if someone could share something / update accordingly.

![CleanShot 2023-10-18 at 15 32 58@2x](https://github.com/radix-ui/primitives/assets/3930150/06c5bbaf-5b44-4b5f-a10b-ab08f1549356)

**Comment by joaom00** [comment] 2023-10-18 16:36
Hey @wottpal,

the major change to select primitive was:

- [[Select] Use "" value to reset to placeholder](https://github.com/radix-ui/primitives/pull/2174)

Changes for all primitives:

- The types of the Portal component have been changed. (This broke some users' applications, although it was not marked as a major change. [See this comment for context](https://github.com/radix-ui/primitives/issues/2410#issuecomment-1736936484)) https://github.com/radix-ui/primitives/pull/2178

- Added new prop for primitives based on `Popper`:
   - `updatePositionStrategy: 'optimized' | 'always'` https://github.com/radix-ui/primitives/pull/2092

The rest are some fixes https://github.com/radix-ui/primitives/compare/333eaf790a294c3af6092f2dcf870f27092d2a57...c31c97274ff357aea99afe6c01c1c8c58b6356e0

**Comment by benoitgrelard** [comment] 2024-02-29 11:02
Apologies, it looks like we missed the changelog for that latest public release, I will fix this now.
In the meantime, closing as duplicate of #2415

**Closed** 2024-02-29 12:12 UTC
