### ISSUE TITLE
DropdownMenu is ignoring viewport boundaries

### ISSUE THREAD

**Issue by paralin** [radix-ui/primitives#2599] opened 2023-12-18 23:43 UTC
### Current Behavior

<img width="492" alt="image" src="https://github.com/radix-ui/primitives/assets/534887/d78b356b-89b7-4826-8bfe-70ceaac47d02">

In the above screenshot I show a radix dropdown taken from the example in the docs. It works properly except the sub-menu is going out of the viewport boundaries and is therefore clipped.

### Expected behavior

With collisionDetection enabled I expect the sub-menu to appear on top of the parent menu so as to not go out of the collision boundaries (the viewport).

### Reproducible example

See the [CodeSandbox](https://codesandbox.io/p/sandbox/radix-dropdown-issue-dnccfr) reproduction.

### Suggested solution

I suggest that the sub-menu overlay on top of the menu below it in the case of not enough space.

**Comment by paralin** [comment] 2024-01-17 20:08
I have not found a solution for this yet.

cc @benoitgrelard - tagging since you worked on / wrote the dropdown (thanks!)

**Comment by benoitgrelard** [comment] 2024-03-06 11:52
This is duplicate of #1749, refer to the discussion happening there.

**Closed** 2024-03-06 11:52 UTC
Labels: Resolution: Duplicate, Package: react/dropdown-menu
