### ISSUE TITLE
Hide Accordion Content without Unmounting

### ISSUE THREAD

**Issue by avin-kavish** [radix-ui/primitives#2446] opened 2023-10-11 05:07 UTC
### Overview

Add an option to hide the accordion content without unmounting it when the accordion closes.

### Who does this impact? Who is this for?

Mounting components is an expensive operation and in large accordions the performance impact is visible. I have an accordion that takes 50ms+ to render when all items are opened at once. Leads to sub-optimal UX.

It also negates the benefits of memoization. Using memoized components the entire accordion only takes ~2ms to render on subsequent re-renders, but closing and opening a single item takes 10ms+ due to the content being unmounted.

**Comment by gijzy** [comment] 2023-12-26 14:05
Is there already a solution for this?

**Comment by klingat** [comment] 2024-02-02 04:32
I am also wondering about this!

**Comment by MantasPu** [comment] 2024-02-15 16:47
I'm just going to leave this here 🚀
NextJS + Stitches including sever side rendering with keeping mounted Accordion Content 
https://codesandbox.io/p/devbox/stitches-radix-accordion-ryr2ld

**Comment by benoitgrelard** [comment] 2024-03-05 11:34
Duplicate of #1155

**Closed by benoitgrelard** 2024-03-05 11:34 UTC
Labels: Resolution: Duplicate, Package: react/accordion

**Comment by leachtucker** [comment] 2026-01-08 19:35
For those that come across this; utilizing `forceMount` and `hidden` worked well for my use-case (form with collapsible input sections–inputs needed to stay in the DOM)
