### ISSUE TITLE
Dialog overlay breaks ScrollArea when used within a Popover

### ISSUE THREAD

**Issue by pedromcunha** [radix-ui/primitives#1717] opened 2022-10-13 16:40 UTC
### Current Behavior

First off, this is a fantastic library, thank you for maintaining it and developing it. I have an application which uses Dialog's, these Dialogs sometimes contain Popover with a ScrollArea to help with customizing the scroll bar. I'm noticing that the Dialog overlay is preventing scrolling. Removing the overlay fixes this but I want to have both the overlay and scroll area working.

### Expected behavior

The Dialog overlay shouldn't prevent scrolling in a ScrollArea.

### Reproducible example

Here's a reproducible example: https://codesandbox.io/s/vibrant-perlman-dw8not?file=/App.js:0-3731

### Your environment

Mac OSX, Latest Chrome (v106)

**Comment by pedromcunha** [comment] 2022-10-13 17:06
Also curious observation here: if you scroll while hovering over the scrollbar it scrolls the content. Not sure if that's useful but feels like it could be.

**Comment by benoitgrelard** [comment] 2022-10-14 08:36
Hey @pedromcunha,

We already have an issue tracking this: #1159
I will close yours as a duplicate.

Duplicate of #1159

**Closed by benoitgrelard** 2022-10-14 08:36 UTC
Labels: Resolution: Duplicate
