### ISSUE TITLE
[DropdownMenu] Using `<button>` for the first menu item (with `asChild`) breaks opening the menu with "Enter"

### ISSUE THREAD

**Issue by benface** [radix-ui/primitives#1655] opened 2022-09-08 19:00 UTC
### Current Behavior

[CodeSandbox here (fork of the example in the documentation)](https://codesandbox.io/s/delicate-frost-n4007n); search for `<button` in `App.s` to see the change I made.

1. Use the keyboard to focus on the dropdown button.
2. Press the "Enter" key to open the dropdown menu.

Result: The menu doesn't open (or rather, I think it opens and closes instantly). Note that it still works with "Space".

### Expected behavior

Pressing "Enter" when the dropdown button is focused should open the menu, and not close it instantly. It works in [the example from the documentation](https://codesandbox.io/s/y9cuiu).

### Environment

I was able to reproduce the issue in all the browsers I have on my Mac (Safari, Chrome, Edge, and Firefox).

**Comment by benoitgrelard** [comment] 2022-09-09 13:14
Duplicate of #1397

**Closed** 2022-09-09 13:15 UTC
Labels: Resolution: Duplicate, Package: react/dropdown-menu
