### ISSUE TITLE
Select does not respond to hover events with @radix-ui/react-focus-scope@1.0.4

### ISSUE THREAD

**Issue by shekharkhedekar** [radix-ui/primitives#2448] opened 2023-10-11 16:48 UTC
## Bug report

On `1.0.3`, all is well. On `1.0.4`, a `Select` within a `Dialog` does not respond to hover events when opened, so you don't see items get highlighted. These are portaled in our case.

### Current Behavior
A `Select` within a `Dialog` does not respond to hover events (video below taken with `@radix-ui/react-focus-scope@1.0.4`)

https://github.com/radix-ui/primitives/assets/8353746/58fea220-c09b-44ce-b2c1-645ca6160b6b

### Expected behavior
A `Select` within a `Dialog` responds correctly to hover events (video below taken with `@radix-ui/react-focus-scope@1.0.3`)

https://github.com/radix-ui/primitives/assets/8353746/e4ddd8c5-15dd-442b-b9e0-9ba2aa8363af

### Reproducible example

_I'll work on this_

### Suggested solution

Get back to `1.0.3` behavior

### Additional context

n/a

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   `@radix-ui/react-dialog`| `1.0.4`               |
| Radix Package(s) |   `@radix-ui/react-focus-scope`| `1.0.4`               |
| Radix Package(s) |   `@radix-ui/react-select`| `1.2.2`               |
| React            | n/a     |   `18.2.0`      |
| Browser          |     Chrome    |   `117.0.5938.132`      |
| Assistive tech   |     n/a    |         |
| Node             | n/a     |  `18.12.1`       |
| npm/yarn         |     npm    |  `8.19.2`       |
| Operating System |   MacOS      |  `14.0`       |

**Comment by joaom00** [comment] 2023-10-11 18:45
Probably related to https://github.com/radix-ui/primitives/issues/1088. Make sure you only have the latest version of `DismissableLayer` installed

**Comment by Nradar** [comment] 2023-10-11 19:56
Have the same issue after updating the dialog, dropdown menu, and select primitive, both hover styling not working in a dialog.

**Comment by joaom00** [comment] 2023-10-11 19:57
@Nradar Make sure you only have one version of `DismissableLayer` installed

**Comment by Nradar** [comment] 2023-10-11 20:03
> @Nradar Make sure you only have one version of `DismissableLayer` installed

I searched but cant find DismissableLayer installed. Do I need to install it manually?

**Comment by AlexGalays** [comment] 2023-10-16 18:06
forcing the version of `DismissableLayer` via `resolutions` fixed it for me.

**Comment by Nradar** [comment] 2023-10-16 18:09
> Have the same issue after updating the dialog, dropdown menu, and select primitive, both hover styling not working in a dialog.

Updating all radix primitive fixed for me, as the DismissableLayer to be only one version

**Comment by benoitgrelard** [comment] 2024-03-06 14:54
Solution provided (Duplicate of #1088)

**Closed by benoitgrelard** 2024-03-06 14:54 UTC

**Comment by QAQmmttyyy** [comment] 2024-12-18 14:29
fixed for me
