### ISSUE TITLE
Accordion At the first click the animation is not smooth. 

### ISSUE THREAD

**Issue by thierryc** [radix-ui/primitives#1482] opened 2022-06-20 10:56 UTC
## Bug report

Accordion (on the home page).

At the first click, on safari, the animation is not smooth. 
At the second click, the animation is perfectly smooth.

A nearly imperceptible blink effect is visible... **Only on safari.** 

### Current Behavior

https://user-images.githubusercontent.com/197471/174584639-2dd23f72-a37b-48ec-bb61-2c559a5ea9c2.mov

The first time on safari, the animation is not smooth as it is at the second time.

### Expected behavior

Smooth animation

### Reproducible example

https://www.radix-ui.com 

or 

https://www.radix-ui.com/docs/primitives/components/accordion

### Your environment

Safari Version 15.5 (17613.2.7.1.8) MacOS Monterey 12.4

**Comment by benoitgrelard** [comment] 2022-06-20 11:09
Hi, this is a duplicate of #1265 so I'll close it now.

**Closed by benoitgrelard** 2022-06-20 11:09 UTC
