### ISSUE TITLE
Update release notes for primitives and colors

### ISSUE THREAD

**Issue by CHR-onicles** [radix-ui/primitives#2435] opened 2023-10-08 23:23 UTC
## Documentation

Hi, I've noticed updated versions from dependabot (in my projects) and commits in this repo, but I don't see it reflecting in the [actual release notes](https://radix-ui.com/docs/primitives/overview/releases). As someone who needs to review release notes before updating packages, this has held me back for a few weeks. I'll appreciate you addressing this as soon as you can.

### Relevant Radix Component(s)

- React Select
- React dialog
- React scroll area

### Examples from other doc sites
N/A

**Comment by toonverbeek** [comment] 2023-10-09 09:38
Would love to see the changelog updated as well. Just ran a minor update on our repo which includes several radix packages. Updating these packages broke our build with the following type error:

`Type error: Property 'className' does not exist on type 'SheetPortalProps'.`

I traced this error back to the [`shadcn/ui`](https://ui.shadcn.com/docs/components/sheet) implementation of `Sheet`: 

```
...
const SheetPortal = ({
  className,
  ...props
}: SheetPrimitive.DialogPortalProps) => (
  <SheetPrimitive.Portal className={cn(className)} {...props} />
);

```

Regardless of the `shadcn/ui` implementation, it would be great to see the release notes updated.

**Comment by raphaelbadia** [comment] 2023-10-11 09:24
Related: https://github.com/radix-ui/primitives/issues/2423 
For the shadcn/ui, just remove the className as they did [here](https://github.com/shadcn-ui/ui/pull/1606)

**Comment by benoitgrelard** [comment] 2024-02-29 11:02
Apologies, it looks like we missed the changelog for that latest public release, I will fix this now.
In the meantime, closing as duplicate of #2415

**Closed** 2024-02-29 12:12 UTC
