### ISSUE TITLE
[NavigationMenu] Menu closes when mouseenter + instantaneous click

### ISSUE THREAD

**Issue by thgh** [radix-ui/primitives#2326] opened 2023-08-06 15:54 UTC
### Current Behavior

1. Click Learn
2. Learn menu opens
3. Click Overview
4. Overview menu is shortly visible and then closes

### Expected behavior

1. Click Learn
2. Learn menu opens
3. Click Overview
4. Overview menu opens

### Reproducible example

https://www.radix-ui.com/docs/primitives/components/navigation-menu

### Suggested solution

The initial delay that "ignores" the first toggle, should be re-applied when a new menu item is opened.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |      Chrome   |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by thgh** [comment] 2023-08-29 08:04
Oh thanks for the context, it's the same underlying issue indeed. I don't want to disable hover, both should trigger the menu.

**Comment by josephkruse** [comment] 2023-08-29 13:32
It doesn't disable hover just disables clicks for 1 seconds after hover.

https://codesandbox.io/p/sandbox/peaceful-nobel-gmlbyy?file=%2FApp.tsx

**Comment by thgh** [comment] 2023-08-30 09:03
Thanks, I refactored it to this workaround for now:

```tsx
function Item () {
  const fix = useTriggerFix()
  
  ...
        <NavigationMenu.Trigger {...fix}>
  ...
}

function useTriggerFix() {
  const disable = useRef<any>()
  return {
    onClick: (e) => disable.current && e.preventDefault(),
    onPointerEnter: () => {
      clearTimeout(disable.current)
      disable.current = setTimeout(() => (disable.current = false), 1000)
    },
  }
}
```

**Comment by kachkaev** [comment] 2023-11-12 19:17
Yeah seems like it’s a duplicate of https://github.com/radix-ui/primitives/issues/1630. A workaround can be found here: https://github.com/radix-ui/primitives/issues/1630#issuecomment-1545995075.

**Comment by benoitgrelard** [comment] 2024-03-08 14:45
Duplicate of #1630

**Closed by benoitgrelard** 2024-03-08 14:45 UTC
Labels: Package: react/navigation-menu
