### ISSUE TITLE
[Dropdown Menu] Show Dropdown Menu Content only when you click and release the trigger button

### ISSUE THREAD

**Issue by unknown503** [radix-ui/primitives#2626] opened 2023-12-05 23:59 UTC
Hello, I was wondering if currently it is possible for the **DropdownMenu.Trigger** component to show the Dropdown content only when you click and release the trigger button. 

The problem I have is on mobile, if a user is for example trying to scroll down and presses (without releasing) the trigger button, it opens the dropdown menu even though the user was not trying to do so.

From what I have testes, this issue is also present as of now on the [Dropdown Menu radix example](https://www.radix-ui.com/primitives/docs/components/dropdown-menu). This also happens on desktop, but is not a clear issue as it is on mobile. 

So I wanted to know if you guys have been able to get around this issue somehow. I am trying to achieve a similar behavior of how [Alert Dialog](https://www.radix-ui.com/primitives/docs/components/alert-dialog) or [Dialog](https://www.radix-ui.com/primitives/docs/components/dialog) trigger work (they are pretty similar components, but in order to show the modal window, you have to click and release the button and that very same behavior is what I want on my Dropdown menu).

Let me know if you have a solution please, for code examples you can check the links of the radix documentation I shared.

**Comment by benoitgrelard** [comment] 2024-03-05 12:07
Duplicate of #1912

**Closed by benoitgrelard** 2024-03-05 12:07 UTC
Labels: Resolution: Duplicate, Package: react/dropdown-menu
