### ISSUE TITLE
[DropdownMenu] First menu item is selected when trigger is clicked on mobile device

### ISSUE THREAD

**Issue by hyper-sam** [radix-ui/primitives#1620] opened 2022-08-16 09:46 UTC
### Current Behavior

If user clicks bottom part of trigger button then menu content flashes on screen and first item is selected.
This issue is at least present on Android 12 with Firefox 103.2.0. It can be also reproduced on desktop version of Chrome (Version 104.0.5112.79, macOS 12.5) when mobile device simulation is on (dev tools).

![output](https://user-images.githubusercontent.com/111335602/184848576-243d02bf-9e12-4a73-b18f-4232b83091a8.gif)

### Expected behavior

If user clicks bottom part of trigger button it should just open the menu content.

### Reproducible example

https://www.radix-ui.com/docs/primitives/components/dropdown-menu

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dropdown-menu     |    1.0.0     |
| Browser          |   Firefox      |    103.2.0     |
| Operating System |    Android     |  12       |

**Comment by benoitgrelard** [comment] 2022-09-06 10:03
I can confirm this is an issue on touch devices, including iOS.
I think this will be addressed by #657 as we do in `Select`.

**Comment by NicoToff** [comment] 2024-05-01 21:28
I can't reproduce this on Android or emulation on desktop, I assume this is fixed and can be closed?

**Closed as completed** 2024-05-03 09:03 UTC
Labels: Type: Bug, Package: react/dropdown-menu
