### ISSUE TITLE
Accessibility issue - Focus trap in modal is not working when the focus element is removed from the DOM

### ISSUE THREAD

**Issue by eitanavgil** [radix-ui/primitives#2026] opened 2023-03-16 13:18 UTC
## Bug report
Modals should trap focus and keep the focus inside. If the focus is on something that is removed from the DOM the focus does not stay inside the modal, but is moving to the body and the modal is kept open while navigation is outside of it. 

### Current Behavior

See video [here](https://share.cleanshot.com/HlC43xZT)

### Expected behavior
Modals should keep focus in it no matter what. 

### Reproducible example

[https://wk3r6u-5173.csb.app/](https://wk3r6u-5173.csb.app/)

### Suggested solution

Whatever happens - keep the focus on the modal 

### Your environment
| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dialog |         |
| React            | n/a     | 17.0.2 |
| Browser          | chrome |         |
| Assistive tech   | keyboard tabbing |         |
| Node             | n/a     | 14 |
| npm/yarn         | yarn |         |
| Operating System | osx |         |

**Comment by benoitgrelard** [comment] 2023-03-16 14:08
Duplicate of #1498

**Closed by benoitgrelard** 2023-03-16 14:08 UTC
