### ISSUE TITLE
`Popover.Trigger` causes re-open  of `Popover.Content` instead of close on iOS

### ISSUE THREAD

**Issue by lunelson** [radix-ui/primitives#674] opened 2021-05-31 13:23 UTC
### Current Behavior

On iOS, the `Popover` component cannot be closed by clicking the `Popover.Trigger`: somehow more than one event is received, so `Popover.Content` closes and immediately opens again.

### Expected behavior

Clicking the Popover trigger when the panel is open, should close it.

### Reproducible example

The following is from the actual docs page: https://radix-ui.com/primitives/docs/components/popover

https://user-images.githubusercontent.com/1242864/120199426-840cb000-c223-11eb-9d0e-020dbd85bdfa.mp4

### Suggested solution

I'm guessing this might have to do with the order in which events are fired in iOS, and perhaps how the "click outside" is being tracked, such that a "close" event is being tracked before the button trigger is received, so that the button click is interpreted as an "open" command

**Comment by benoitgrelard** [comment] 2021-05-31 14:01
Hey, thanks for reporting this.
I am closing it as it's a duplicate of #631

**Closed by benoitgrelard** 2021-05-31 14:01 UTC

**Comment by mwx27** [comment] 2023-01-16 23:24
Hello, this bug is still alive on Safari. Could you fixe it?

**Comment by benoitgrelard** [comment] 2023-04-13 11:13
> Hello, this bug is still alive on Safari. Could you fix it?

I don't see it here: https://www.radix-ui.com/docs/primitives/components/popover
