### ISSUE TITLE
[Popover + Tooltip] Tooltip with exit animation shows when focusing popover content with another Tooltip

### ISSUE THREAD

**Issue by hipstersmoothie** [radix-ui/primitives#1073] opened 2022-01-08 09:21 UTC
### Current Behavior

- hover over tooltipped popover trigger
- trigger popover that's first focusable item has a tooltip too
- Tooltip in popover shows

https://user-images.githubusercontent.com/1192452/148638791-3d9a1056-b949-4445-ac6e-653ceaf73e59.mp4

### Expected behavior

The second tooltip doesn't show

### Reproducible example

https://codesandbox.io/s/nice-kirch-ygqqf?file=/Tooltip.js

### Suggested solution

You could immediately hide the first tooltip in this situation, but it would be nice to still have the exit animation

**Comment by hipstersmoothie** [comment] 2022-01-09 23:48
This seems to happen even if the the popover trigger doesn't have a tooltip

**Comment by benoitgrelard** [comment] 2022-01-10 10:36
Closing this as a duplicate of #937.

The issue is actually due to some code we have that tries to detect when the trigger moves so it closes the tooltip.
The issue here is that because you have one inside a popover that gets dynamically positioned, it ends up closing it as it's repositioned.

We are aware of the issue, you can find more explanations/details on this discussion here: https://github.com/radix-ui/primitives/discussions/1041

**Closed by benoitgrelard** 2022-01-10 10:36 UTC
