### ISSUE TITLE
[Select] Allow setting `form` prop

### ISSUE THREAD

**Issue by cmd-johnson** [radix-ui/primitives#2975] opened 2024-06-24 13:02 UTC
## Feature request

Native `<select>`s (and all other input elements) have a `form` prop that lets us override which form the input belongs to. As far as I can tell, the `@radix-ui/react-select` primitives don't support this property right now.

### Overview

When using native `<select>` elements, you can render a select element outside of a `<form>` and later set the element's form using the form's id:
```html
<select name="selectOutsideOfForm" form="exampleForm">
  <option value="a" selected>A</option>
  <option value="b">B</option>
</select>
<form id="exampleForm">
  <button>Submit</button>
</form>
```
Clicking the submit button includes the `selectOutsideOfForm` value in the resulting submission.

Similarly you can exclude a `<select>` from a form by setting it's `form` attribute to an invalid form id:
```html
<form id="exampleForm">
  <select name="selectInsideOfForm" form="">
    <option value="a" selected>A</option>
    <option value="b">B</option>
  </select>
  <button>Submit</button>
</form>
```
Clicking the submit button now doesn't include the `selectInsideOfForm` element in the form.

### Who does this impact? Who is this for?

Supporting the `form` attribute would enable use-cases such as
- rendering a native `<select>` element using SSR and then replace it with a radix `<Select>` element after hydration, allowing users to use the app before it is hydrated (or even with JS disabled)
- allowing more ways to structure forms by rendering `<Select>` elements outside of a `<form>` element

### Additional context

[MDN reference for the `<select>` `form` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#form)

From looking through radix's code, I'd expect the implementation to work somewhat along these lines:
- adding a new `form` prop to the `Select.Root` component
- adding a new `form` property to the `SelectContextValue` type
- passing the `form` prop value to the `<SelectProvider>`
- set the `form` attribute of the `Primitive.button` element inside the `Select.Trigger` to the `form` value from `useSelectContext`
- set the `form` attribute of the `BubbleSelect` component to the `form` value from `useSelectContext`
- change the logic of determining `isFormControl` inside of the `Select.Root` component to check for the trigger's `form` (which will the browser sets to the actual form element reference at runtime) instead of using `trigger.closest("form")`.
  - **This might be a breaking change**, but should only impact users that are passing a `form` prop directly to a `Select.Trigger` component. This is currently valid because the trigger element re-uses the native `HTMLButtonProps` type. Changing the trigger's `form` prop directly would lead to issues with the `isFormControl` logic, so an implementation would ideally omit the `form` prop from the `SelectTriggerProps` type, so the form prop can only be set through `Select.Root`.

I think that's it, though. I'd be happy to submit a PR for this if requested.

**Comment by jacobparis** [comment] 2024-07-21 15:21
I am also looking for this feature

My userland solution is to force the `<select>` if the user provides a form attribute and then inject the attribute, just showing here for anyone else who stumbles on this issue before a fix lands

```ts
export function Selectbox({
	options,
	form,
	...props
}: React.ComponentProps<typeof SelectRoot> & {
	form?: string;
	options: Array<{ label: string; value: string }>;
}) {
	const triggerRef = useRef<HTMLButtonElement>(null);
	// if the user provides a form attribute, wrap Select in a <form>
	// that triggers Radix to generate a real <select>
	const WrapperComponent = form ? 'form' : 'div';

	// Radix doesn't support a proper form attribute so this whole thing is a workaround
	useEffect(() => {
		let timeout: number;
		if (form !== undefined) {
			timeout = window.setTimeout(() => {
				// Radix puts the <select> as a sibling of the trigger
				const select = triggerRef.current?.nextSibling;
				if (select && select instanceof HTMLSelectElement) {
					// empty form attribute opts out of form submission
					select.setAttribute('form', form || '');
				}
			}, 1);
		}

		return function cleanup() {
			clearTimeout(timeout);
		};
	}, [form]);

	return (
		<WrapperComponent>
			<Select {...props}>
				<SelectTrigger ref={triggerRef}>
					<SelectValue />
				</SelectTrigger>

				<SelectContent>
					<SelectGroup>
						{options.map((option) => (
							<SelectItem key={option.value} value={option.value}>
								{option.label}
							</SelectItem>
						))}
					</SelectGroup>
				</SelectContent>
			</Select>
		</WrapperComponent>
	);
}
```

**Comment by chaance** [comment] 2024-09-27 21:37
Duplicate of https://github.com/radix-ui/primitives/issues/2530

**Closed by chaance** 2024-09-27 21:37 UTC
