### ISSUE TITLE
Submenu doesn't adjust their position when there is no space available

### ISSUE THREAD

**Issue by raviteja83** [radix-ui/primitives#1192] opened 2022-02-24 13:54 UTC
### Current Behavior
Submenu's get cropped instead of rearranging when there is not enough space for it to be completey shown.

### Expected behavior
Submenu should auto adjust it's position when there is not enough space where it is supposed to open

### Reproducible example

Easily reproducible on radix docs for dropdown menu.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/6763261/155536957-60d45bcf-7638-439d-8220-bf0e269aa07c.png">

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment] 2022-02-25 08:53
Hi @raviteja83 

Yeah we are aware of this.
Here are a few related issues: #945, #973, #557.

I will close it as a duplicate of #945 for now.

**Closed by benoitgrelard** 2022-02-25 08:53 UTC
