### ISSUE TITLE
[DropdownMenu] reopens when trigger is press on mobile

### ISSUE THREAD

**Issue by norman-ags** [radix-ui/primitives#631] opened 2021-05-03 12:21 UTC
### Current Behavior

When the dropdown menu is open, pressing the trigger button closes and reopens the dropdown menu
https://streamable.com/vuqvg4

### Expected behavior

Expect the dropdown menu to be closed when trigger is pressed

### Reproducible example

https://radix-ui.com/primitives/docs/components/dropdown-menu#basic-example

**Comment by norman-ags** [comment] 2021-05-03 12:31
Also happens on:
Popover: https://streamable.com/agxgyo
Alert dialog: https://streamable.com/8pyy5k

**Comment by rafgraph** [comment] 2021-06-10 14:29
I'm having this issue too. Is there a suggested workaround? Currently, for me, this bug makes the Dropdown Menu, Alert Dialog and Popover components unusable in projects that need to support touch devices (all of my projects do). Thanks.

**Comment by benoitgrelard** [comment] 2021-06-10 14:50
Some people on Discord had a workaround: https://discord.com/channels/752614004387610674/803656530259738674/851795049984950294.

I have looked at it but it's a complex thing to resolve right now so I haven't managed to fix it yet. I don't think it will be in next upcoming release, but should be in the following one.

**Comment by rafgraph** [comment] 2021-06-11 14:40
There's also an issue with Safari on MacOS (and iOS/iPadOS) that I think is related to this `DismissableLayer` issue (if not I can create a new one). Clicking the trigger re-opens the Dialog and Alert components, when it should close them.


https://user-images.githubusercontent.com/11911299/121703875-3bfe5080-caa1-11eb-9d8a-6b454fda6667.mov


https://user-images.githubusercontent.com/11911299/121703883-3dc81400-caa1-11eb-9902-6789fb855ebf.mov

**Comment by benoitgrelard** [comment] 2021-06-11 15:10
Thanks, that is probably related.

**Comment by jjenzz** [comment] 2021-07-02 14:15
I've split the different component reports into separate tickets as I was able to find a solution for `DropdownMenu` but the other components are triggered by different events and require further investigation into the root cause.

**Closed** 2021-07-06 14:33 UTC
Labels: bug
