### ISSUE TITLE
[Select] Touch event on Select UI component triggers events on other interactive UI elements

### ISSUE THREAD

**Issue by bogy0** [radix-ui/primitives#2083] opened 2023-04-15 09:40 UTC
### Current Behavior
When using the Select UI component on a touch device, if there is another interactive UI element under the Select dropdown, touching a Select item can also trigger events on the other element. This behavior is not observed on desktop browsers.

https://user-images.githubusercontent.com/5119480/232205583-87e8290c-ff0f-4467-83c4-e9f6ae03a214.mp4

### Expected behavior
Touching a Select item should only trigger events related to the Select UI component, and not other interactive UI elements under the dropdown.

### Reproducible example
1. Open the [Radix UI Select docs page](https://www.radix-ui.com/docs/primitives/components/select) on a touch device.
2. Touch a Select item to open the dropdown.
3. While the dropdown is open, touch a Select item that's above the `styles.css` tab.
4. The Select item selected, and also the `styles.css` tab will be active. This behavior can be problematic and confusing for users interacting with the UI, especially if they unintentionally trigger events on other elements.

### Suggested solution
One solution could be to add an event listener to the Select component that prevents the propagation of touch events to other interactive UI elements under the dropdown. This would ensure that only the Select UI component is triggered when a Select item is touched.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | React, but probably core  | latest |
| React            | n/a     |         |
| Browser          | Chrome on Android, iOS Safari latest, but reproducible also on Desktop Chrome if touch enabled in responsive mode  | latest |
| Assistive tech   | Touch enabled |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System | Android 13, iOS 16, Windows 11,  |         |

**Comment by benoitgrelard** [comment] 2023-04-15 09:53
Duplicate of #1658

**Closed by benoitgrelard** 2023-04-15 09:53 UTC
