### ISSUE TITLE
[Tooltip] Tooltip content is not positioned correctly when used in a `foreignObject` in SVG within Safari, if zoom level not 100%.

### ISSUE THREAD

**Issue by tkalmi** [radix-ui/primitives#1961] opened 2023-02-15 18:19 UTC
## Bug report
Hey,

I'm trying to use Radix UI's Tooltip primitive (v1.0.3) within an SVG chart. Some of the chart's data points are rendered within `<foreignObject>` elements and act as triggers for tooltips. On Chrome & Firefox, the tooltip content is positioned where expected, no matter the browser's zoom level. However, on Safari, the content's placement gets increasingly off as browser zoom level drifts away from 100%. Please see the CodeSandbox link for a simplified example.

### Current Behavior

On Safari (16.2), the Tooltip content's position changes if the browser zoom level changes. 

### Expected behavior

I'm expecting the Tooltip Content to maintain a constant distance to the Trigger despite the browser's zoom level. This is how it works on Chrome (Version 109.0.5414.119 (Official Build) (arm64)) and Firefox (110.0b9 (64-bit)).

On Safari, after a few zoom outs:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/14164217/219117176-08af7fea-49cb-46df-971f-99fa33a9b94d.png">

On Chrome, after a few zoom outs:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/14164217/219117251-af2f3ff2-7296-4144-be59-f129c4009499.png">

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/ecstatic-proskuriakova-c8oune?file=/src/App.tsx:339-607)

Test on Safari, and try changing the browser zoom level. Pay attention to the tooltip content's position (the tooltip is set to be always open).

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-tooltip        | 1.0.3        |
| React            | n/a     |  17.0.1       |
| Browser          | Safari        |  16.2       |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |  macOS       |  13.1       |

**Comment by benoitgrelard** [comment] 2023-02-16 11:42
Hi @tkalmi,

The primary use-case `Tooltip` as designed for is for displaying "tips" for "tools" in UIs.
I am unsure of what the accessibility story is within SVG foreign objects…

However, purely when it comes to positioning, this probably will be an issue with the underlying library we use (floating-ui) so might be worth opening an issue there and referencing this one.

@atomiks, are you aware of any positioning issues within SVG foreign objects in Safari?

**Comment by atomiks** [comment] 2023-02-16 12:04
Confirmed the position is [wrong in Floating UI's latest version as well](https://codesandbox.io/s/intelligent-wright-9hften?file=/src/App.tsx), so an issue made at [its repo](https://github.com/floating-ui/floating-ui/issues) is best indeed 👍 

Seems like an esoteric case that hasn't been checked/tested for before, don't know what the cause is without looking into it deeply.

**Comment by benoitgrelard** [comment] 2023-02-16 12:30
Thanks for checking @atomiks! @tkalmi Feel free to open an issue on `floating-ui` and we can keep this open until there's a fix.

**Comment by atomiks** [comment] 2023-02-18 15:14
This is a Safari bug (assuming Chrome & Firefox are matching the spec) with `foreignObject` nodes and their descendants.

```js
<foreignObject
  width={24 * 2}
  height={24 * 2}
  style={{background: 'red', fontSize: 14}}
  x={100 - 24}
  y={200 - 24}
  ref={(node) => {
    console.log(node?.getBoundingClientRect());
  }}
/>
```

You can see the values are wrong when zooming in/out in Safari, as they should remain constant (within rounding error).

Given the low impact nature of this bug (unlikely to occur for most users, and an uncommon use case), I don't see value in attempting to workaround it; I think filing a ticket to WebKit makes the most sense.

**Comment by benoitgrelard** [comment] 2023-02-20 17:16
> Given the low impact nature of this bug (unlikely to occur for most users, and an uncommon use case), I don't see value in attempting to workaround it; I think filing a ticket to WebKit makes the most sense.

I would agree with that too.

@tkalmi, feel free to file a WebKit ticket and post it here.
In the meantime I will close this issue.

**Closed by benoitgrelard** 2023-02-20 17:16 UTC
Labels: Dependency: floating-ui

**Comment by tkalmi** [comment] 2023-02-22 09:30
Thanks everybody!
