### ISSUE TITLE
Dialog onKeyDown opens and immedietly closes

### ISSUE THREAD

**Issue by atomcorp** [radix-ui/primitives#2453] opened 2023-10-13 12:36 UTC
## Bug report

Firstly thanks for the great library! 

Not sure if this is a bug. It's something Radix is doing, but it might be unavoidable. I have a workaround, just posting an issue incase it's something work checking out.

### Current Behavior

https://github.com/radix-ui/primitives/assets/3504434/22798f9a-27f8-4318-b11c-8642d00ad561

Focusing and and triggering an onKeyDown event on an element with role="button" to open a Dialog, will also trigger the close button. This doesn't happen with keydown on an actual button element or when not using Radix Dialog and doing something similar. A workaround is adding e.preventDefault().  

### Expected behavior

It should not trigger the button it's focusing on.

### Reproducible example

https://codepen.io/atomcorp/pen/RwEOQWW?editors=0111

### Suggested solution

-

### Additional context

The reason I can't just use a button is for styling purposes - I need the text to flow in a paragraph 🙄.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     react-dialog    |   1.0.5      |
| React            | n/a     |    18.2.0     |
| Browser          |         |     Chrome    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment] 2024-03-07 10:29
Duplicate of #1794, please see my comment there.

**Closed by benoitgrelard** 2024-03-07 10:29 UTC
