### ISSUE TITLE
[NavigationMenu] Menu should close when navigating to a Link 

### ISSUE THREAD

**Issue by fscgustavo** [radix-ui/primitives#1364] opened 2022-05-02 18:50 UTC
### Current Behavior

The menu root remains open even if the route changes. 

There was a merged solution that fixes this problem, but for some reason, it still does not work on the next projects. Have I made a mistake?

![navigation_link](https://user-images.githubusercontent.com/48841071/166306208-ba1e3af3-4a77-4e63-9f88-f0ef876e46a2.gif)

### Expected behavior

The menu root should close after a click on the navigation link

### Reproducible example

Visit the `day` route to see the menu

/day/any_term

[Stackblitz Template](https://stackblitz.com/edit/nextjs-lt13ab?file=pages%2Fday%2F[slug].jsx)

**Comment by benoitgrelard** [comment] 2022-05-03 09:11
Hi @fscgustavo, this is a duplicate of #1301.
It was already addressed in #1347.
If you don't want to wait for the stable release, you can update to the latest rc to get the new behaviour.

**Closed by benoitgrelard** 2022-05-03 09:11 UTC

**Comment by fscgustavo** [comment] 2022-05-03 12:05
@benoitgrelard The `0.1.3-rc.10` version is being used on the template

https://stackblitz.com/edit/nextjs-lt13ab?file=package-lock.json
