### ISSUE TITLE
[Navigation Menu] Safe triangles for submenus

### ISSUE THREAD

**Issue by bk-tho** [radix-ui/primitives#2437] opened 2023-10-09 12:57 UTC
### Overview

In our app, we have a navigation menu that looks something like this. It's implemented with Radix [Navigation Menu](https://www.radix-ui.com/primitives/docs/components/navigation-menu):
![Bildschirmfoto 2023-10-09 um 14 49 36](https://github.com/radix-ui/primitives/assets/87074833/f63f7f9c-91b2-41db-bece-001e41e6b39e)

When hovering a menu item, the appropriate submenu appears. Moving the mouse over to the submenu items must be done with caution, especially for menu items that are far to the right. A direct movement does not achieve the desired outcome (`MenuItem 5` will be hovered first, causing its submenu to appear):
![Bildschirmfoto 2023-10-09 um 14 50 32](https://github.com/radix-ui/primitives/assets/87074833/bd51f8c6-6a20-4ea8-be31-e0d0d7d72e32)

The red arrow visualizes the currently necessary mouse movement:
![Bildschirmfoto 2023-10-09 um 14 50 53](https://github.com/radix-ui/primitives/assets/87074833/2e2157d5-3eed-4aee-a3e8-475b7e0ff4f0)

We think that it would be beneficial to implement "safe triangles" similar to e.g. the Dropdown Menu. As long as the mouse stays within the triangle, no submenu other than the one that's currently active is triggered:
![Bildschirmfoto 2023-10-09 um 14 51 28](https://github.com/radix-ui/primitives/assets/87074833/9c871831-9728-484c-bb04-6546f2b534c5)

### Examples in other libraries

The Radix Dropdown Menu implements such behavior.

### Who does this impact? Who is this for?

While this is motivated by our specific use case, I believe that this is generally desirable.

### Additional context

- [Better Context Menus With Safe Triangles (Smashing Magazine)](https://www.smashingmagazine.com/2023/08/better-context-menus-safe-triangles/), including a [section about the Radix Dropdown Menu](https://www.smashingmagazine.com/2023/08/better-context-menus-safe-triangles/#radix-navigation-component)

**Comment by benoitgrelard** [comment] 2024-03-05 14:47
Duplicate of #1549

**Closed by benoitgrelard** 2024-03-05 14:47 UTC
Labels: Resolution: Duplicate, Package: react/navigation-menu
