### ISSUE TITLE
[Select] Can't differentiate if select trigger was focused from mouse or keyboard

### ISSUE THREAD

**Issue by dlacaille** [radix-ui/primitives#1803] opened 2022-11-25 21:22 UTC
### Current Behavior

There is currently no way to prevent highlighting a `<Select.Trigger>` when using the mouse.

![image](https://user-images.githubusercontent.com/6683854/204056475-55eb3644-0a86-439a-89e5-1b335b8ffc02.png)

### Expected behavior

Using `:focus-visible` we should be able to only show a `<Select.Trigger>` element as focused when it is actually selected using the keyboard. Currently radix programmatically focuses the element, which prevents the browser from differentiating a keyboard focus from a mouse focus. 

### Reproducible example

[Code Sandbox](https://codesandbox.io/s/nifty-alex-5jfiri?file=/App.js)

This is a slightly modified version of the Radix UI Select example where I changed the `:focus` selector to `.SelectTrigger:focus-visible` to show that the mouse still triggers the browser's `:focus-visible` property.

### Suggested solution

In other radix-ui components such as `<Select.Item>` we can use `[data-highlighted]`, but it is not available for this component.

### Additional context

An old issue resolved by the data-highlighted attribute:
https://github.com/radix-ui/primitives/issues/1164

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-select    |    1.1.2     |
| React            | n/a     |   @radix-ui/react-select      |
| Browser          |     Firefox    |   107.0      |
| Assistive tech   |   n/a      |     n/a    |
| Node             | n/a     |     n/a    |
| npm/yarn         |    n/a     |    n/a     |
| Operating System |     MacOS    |     Ventura 13.0.1    |

**Comment by shimbarks** [comment] 2023-01-23 08:18
I'm facing the same issue with @radix-ui/react-dropdown-menu.

**Comment by benoitgrelard** [comment] 2023-01-23 09:21
Hey @dlacaille,

> Currently radix programmatically focuses the element, which prevents the browser from differentiating a keyboard focus from a mouse focus.

As you correctly put it, unfortunately the browser doesn't expose a primitive for us to tell it whether it's a keyboard or pointer focus. This is really the issue here. `:focus-visible` in browsers work based on a bunch of heuristics (not even necessarily aligned in each browsers) and AFAIK they all treat programmatic focus as `:focus` so there isn't anything we can do here.

> In other radix-ui components such as <Select.Item> we can use [data-highlighted], but it is not available for this component.

This was introduced for a different reason that has nothing to do with focus-visible. The reason is because we didn't want users to rely on `:focus` to style the highlighted state of items as it's really an implementation detail. In the future we may for example move away from using focus and instead use `aria-activedescendant`.

I will close the issue as there isn't much we can do about this technically but feel free to discuss here if you have ideas you think we could explore!

**Closed by benoitgrelard** 2023-01-23 09:21 UTC

**Comment by holdenmatt** [comment] 2023-01-25 18:21
Just started using Radix and loving it so far (thank you!).

The one issue that's annoying me (relative to other frameworks I've used) is there seems to be no way to make focus rings appear only for keyboard (not mouse) input.

For example, React Aria does this by default: https://react-spectrum.adobe.com/react-aria/FocusRing.html

Mantine makes it a theme option, and keyboard-only by default: https://mantine.dev/theming/theme-object/#focusring

This flexibility is really nice from a design perspective, as you can have prominent focus rings to aid keyboard navigation without requiring them to appear for every mouse click. Many sites do this (such as this Github comment box :) ).

Adding an option for this would also make it easier to incrementally adopt Radix alongside other component libraries. For example, I'd like to use Radix for Dropdown/Select components but already have other Mantine components in my project, and want to make focus ring behavior consistent across them.

(thanks for considering!)

**Comment by rolanday** [comment] 2023-12-24 08:58
This issue drove me nuts and caused me to abandon radix (and shadcn) for react-aria/rac, but I recently picked up another project that has radix and thankfully came across this post, which works well in conjunction w/ focus-visible.

```
<DropdownMenuContent onCloseAutoFocus={(e) => e.preventDefault()}>
```

credit: [Thomas Stock](https://stackoverflow.com/users/72859/thomas-stock)
https://stackoverflow.com/questions/77227586/shadcn-focus-visible-after-click-outside-still-stands

**Comment by benface** [comment] 2023-12-24 16:31
That's not a very accessible solution @rolanday. The trigger _should_ be focused on close, but it shouldn't be "visibly focused".

**Comment by rolanday** [comment] 2023-12-24 17:16
#benface, agreed, which is precisely why I've moved to react-aria for my main work (i.e., I'm unwilling to compromise on accessibility). That said, hiding the focus outline full stop, which is a common pattern from ppl trying to resolve this radix issue is also not accessible (I'm calling it a radix issue because despite above comment, this issue is not present in other UI frameworks so it's solvable despite browser limitations).

The focus ring not appearing on deselect via mouse interactions is table stakes. If you know of an accessible workaround , please please do share -- simply stating that the workarounds to address the issue is not useful. Thanks.

**Comment by benface** [comment] 2023-12-24 22:39
@rolanday – I actually do know and use a workaround, which I should have posted here before (thanks for asking me). I am using the [`focus-visible` polyfill](https://github.com/WICG/focus-visible), which [doesn't trigger on programmatic focus](https://github.com/WICG/focus-visible/issues/88). So I style the focus ring with `.focus-visible` instead of `:focus-visible`.

**Comment by benface** [comment] 2023-12-24 22:42
@benoitgrelard – This issue should be re-opened. It's a real problem, which I believe you'll be able to fix with the new [`focusvisible` option of `.focus()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#focusvisible).

**Comment by rolanday** [comment] 2023-12-25 00:47
@benface , this is very helpful! Thanks you :-)

+1 for request to reopen and +100 that this is a real problem. To be frank, I'm surprised radix-ui and derivatives like shadcn-ui are so popular if devs need to always hide the focus ring in order to ensure proper mouse/touch behavior at the expense of keyboard interaction/accessibility.

**Comment by rolanday** [comment] 2023-12-25 06:25
@benface , thanks again for the pointer -- works well. Super appreciate.

**Comment by benface** [comment] 2024-03-06 22:24
I'm not sure how Headless UI does it, but it doesn't have this issue: https://headlessui.com/react/listbox

**Comment by hwride** [comment] 2024-03-12 11:47
Completely understand this is open source, but just to gauge interest, this is also somewhat of a blocker for our use of Radix Select.

**Comment by felipedeboni** [comment] 2024-07-10 15:15
I was frustrated with this behavior to say the least. As @benface pointed out, @rolanday's solution was not very accessible. While using a polyfill is an option, it's not ideal for those of us who prefer to avoid adding more JS and CSS to the frontend.

I've found a solution that prevents autofocus only when the user uses a mouse. When using the keyboard, the focus-visible property will still work. This approach should save at least 1KB when gzipped,  CSS will be a bit smaller, and it avoids adding several event listeners the polyfill would add.

Here's a snippet: 

```tsx
const Content = forwardRef<HTMLDivElement, DropdownMenuContentProps>(
  ({ onPointerDownOutside, onCloseAutoFocus, ...props }, ref) => {
    const isCloseFromMouse = useRef<boolean>(false);

    const handlePointerDownOutside = useCallback(
      (e: unknown) => {
        isCloseFromMouse.current = true;
        // @ts-expect-error - they don't export the PointerDownOutsideEvent
        onPointerDownOutside?.(e);
      },
      [onPointerDownOutside]
    );

    const handleCloseAutoFocus = useCallback(
      (e: Event) => {
        if (onCloseAutoFocus) {
          return onCloseAutoFocus(e);
        }

        if (!isCloseFromMouse.current) {
          return;
        }

        e.preventDefault();
        isCloseFromMouse.current = false;
      },
      [onCloseAutoFocus]
    );

    return (
      <Portal>
        <RadixContent
          ref={ref}
          {...props}
          onPointerDownOutside={handlePointerDownOutside}
          onCloseAutoFocus={handleCloseAutoFocus}
        />
      </Portal>
    );
  }
);

Content.displayName = 'DropdownMenu.Content';
```

**Comment by zommerberg** [comment] 2024-07-20 10:06
This should be reopened.

**Comment by michalzarsm** [comment] 2024-08-08 21:56
Why this issue keeps getting closed without actually fixing the issue?
I just encountered it while using shadcn/ui, had to use the prevent default method.

**Comment by CarlosLleraMartin** [comment] 2024-08-30 12:34
> I was frustrated with this behavior to say the least. As @benface pointed out, @rolanday's solution was not very accessible. While using a polyfill is an option, it's not ideal for those of us who prefer to avoid adding more JS and CSS to the frontend.
> 
> I've found a solution that prevents autofocus only when the user uses a mouse. When using the keyboard, the focus-visible property will still work. This approach should save at least 1KB when gzipped, CSS will be a bit smaller, and it avoids adding several event listeners the polyfill would add.
> 
> Here's a snippet:
> 
> ```tsx
> const Content = forwardRef<HTMLDivElement, DropdownMenuContentProps>(
>   ({ onPointerDownOutside, onCloseAutoFocus, ...props }, ref) => {
>     const isCloseFromMouse = useRef<boolean>(false);
> 
>     const handlePointerDownOutside = useCallback(
>       (e: unknown) => {
>         isCloseFromMouse.current = true;
>         // @ts-expect-error - they don't export the PointerDownOutsideEvent
>         onPointerDownOutside?.(e);
>       },
>       [onPointerDownOutside]
>     );
> 
>     const handleCloseAutoFocus = useCallback(
>       (e: Event) => {
>         if (onCloseAutoFocus) {
>           return onCloseAutoFocus(e);
>         }
> 
>         if (!isCloseFromMouse.current) {
>           return;
>         }
> 
>         e.preventDefault();
>         isCloseFromMouse.current = false;
>       },
>       [onCloseAutoFocus]
>     );
> 
>     return (
>       <Portal>
>         <RadixContent
>           ref={ref}
>           {...props}
>           onPointerDownOutside={handlePointerDownOutside}
>           onCloseAutoFocus={handleCloseAutoFocus}
>         />
>       </Portal>
>     );
>   }
> );
> 
> Content.displayName = 'DropdownMenu.Content';
> ```

@felipedeboni thanks for the snippet! It works well in our scenario and I think it's a fair workaround to achieve that behavior.

By the way JFYI, you can avoid disabling the TS check by getting the actual type of the `event` parameter of `onPointerDownOutside` with the following ugly construct:

```ts
type PointerDownOutsideEvent = Parameters<NonNullable<DropdownMenuContentProps['onPointerDownOutside']>>[0];
```

**Comment by zommerberg** [comment] 2024-08-30 12:58
@CarlosLleraMartin  @felipedeboni 

Sadly i think even that solution is not perfect. It only prevents the outline when clicked outside. Yet if an item is selected via a mouse it will still trigger the outline which is annoying, it should be there only when the items is selected via keyboard. 

Sadly I wasn't able to find a good way to implement that.

**Comment by yekta** [comment] 2024-11-06 08:55
> @CarlosLleraMartin @felipedeboni
> 
> Sadly i think even that solution is not perfect. It only prevents the outline when clicked outside. Yet if an item is selected via a mouse it will still trigger the outline which is annoying, it should be there only when the items is selected via keyboard.
> 
> Unfortunately I wasn't able to find a good way to implement that.
> 
> Radix seems abandoned now so I switched to react-aria-components and I am using radix only for select few specific elements which I will probably replace in the future anyway.

Although it is not perfect, you can improve it by passing the `handlePointerDownOutside` to `onPointerDown` as well. That will make it so that it works when item is selected with mouse as well.

Like this:

```tsx
// ....
<SelectPrimitive.Content
          onPointerDown={handlePointerDownOutside}
          onPointerDownOutside={handlePointerDownOutside}
// ....
```

**Comment by yekta** [comment] 2024-11-06 09:02
> @CarlosLleraMartin @felipedeboni
> 
> Sadly i think even that solution is not perfect. It only prevents the outline when clicked outside. Yet if an item is selected via a mouse it will still trigger the outline which is annoying, it should be there only when the items is selected via keyboard.
> 
> Unfortunately I wasn't able to find a good way to implement that.
> 
> Radix seems abandoned now so I switched to react-aria-components and I am using radix only for select few specific elements which I will probably replace in the future anyway.

Although it is not perfect you can create a `handlePointerDown` function as well which would make it so that the outline won't show up when you select an item with mouse as well:

```tsx
// ...
const handlePointerDownOutside = React.useCallback(
  (e: unknown) => {
    isCloseFromMouse.current = true;
    // @ts-expect-error - they don't export the PointerDownOutsideEvent
    onPointerDownOutside?.(e);
  },
  [onPointerDownOutside]
);
const handlePointerDown = React.useCallback(
  (e: unknown) => {
    isCloseFromMouse.current = true;
    // @ts-expect-error - they don't export the PointerDownOutsideEvent
    onPointerDown?.(e);
  },
  [onPointerDownOutside]
);
// ...
```
And 
```tsx
// ...
<SelectPrimitive.Content
    onPointerDown={handlePointerDown}
    onPointerDownOutside={handlePointerDownOutside}
// ...

**Comment by bnjmnt4n** [comment] 2025-02-28 11:42
There are a few similar issues to this, for different components: https://github.com/radix-ui/primitives/issues/2397, https://github.com/radix-ui/primitives/issues/2545, https://github.com/radix-ui/primitives/issues/2953.

Other component libraries like Headless UI and React ARIA also have this issue, but they've worked around it by adding custom classes or attributes to be used to indicate whether the interaction was keyboard initiated to allow the equivalent `focus-visible` styling:
- [Headless UI](https://github.com/tailwindlabs/headlessui/pull/2347) adds the `data-headlessui-focus-visible` attribute to `document.documentElement` when events are triggered by the keyboard
- [React Aria](https://github.com/adobe/react-spectrum/issues/1247) adds the `data-focus-visible` attribute to the current elemet being focused when triggered by the keyboard

Until `HTMLElement#focus({ focusVisible: true })` is standardized, it would be great if Radix UI can implement a similar hook for styling.

**Comment by thaiscdaraujo** [comment] 2025-05-08 09:15
I was experiencing this issue when hovering over dropdown items. When opening the dropdown via mouse click, the `focus-visible` accessibility ring would still apply.

One workaround that helped me for now (even if not 100% perfect) was using this CSS selector to ensure the `focus-visible` style is only applied when navigating via keyboard, not when hovering with the mouse:

```css
/* This can be applied to Trigger, Item, or any focusable element */
&:focus-visible:not(:hover) {
  /* your focus styles */
}
