### ISSUE TITLE
[Dialog+Tooltip]: Tooltip inside `Primitive`.Title auto-opens when dialog opens

### ISSUE THREAD

**Issue by mykola-kolomoyets** [radix-ui/primitives#2593] opened 2023-12-15 08:30 UTC
### Current Behavior

1. Create the Dialog component has Tooltip inside `Dialog.Title` or `Popover.Title` or inside `Dialog.Content`/`Popover.Content`, but as not last element (Tooltip is between two `Dialog`/`Popover` primitives elements)
2. Open the dialog by clicking on trigger
3. DIalog opens, tooltip opens too

### Expected behavior

1. Same
2. Same
3. Dialog opens, tooltip is NOT opened, and openes on focus,hover, touch only.

### Reproducible example

[CodeSandbox Here](https://codesandbox.io/p/sandbox/radix-dialog-plus-tooltip-rd9fyt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq6cpjeo00063b6m76auyn0b%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq6cpjeo00023b6mq1yxzlzy%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq6cpjeo00033b6mg39x6y7w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq6cpjfu000i3b6mrtj4kjdl%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq6cpjeo00053b6mr2qcwtu7%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq6cpjeo00023b6mq1yxzlzy%2522%253A%257B%2522id%2522%253A%2522clq6cpjeo00023b6mq1yxzlzy%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq6cpjeo00053b6mr2qcwtu7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq6cpjeo00043b6mt7ogmkzg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq6cpjeo00053b6mr2qcwtu7%2522%252C%2522activeTabId%2522%253A%2522clq6cpjeo00043b6mt7ogmkzg%2522%257D%252C%2522clq6cpjeo00033b6mg39x6y7w%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq6cpjeo00033b6mg39x6y7w%2522%257D%252C%2522clq6cpjfu000i3b6mrtj4kjdl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_ONBOARDING%2522%252C%2522id%2522%253A%2522sandbox-onboarding%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522id%2522%253A%2522clq6cpjfu000i3b6mrtj4kjdl%2522%252C%2522activeTabId%2522%253A%2522sandbox-onboarding%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Suggested solution

PR in progress

### Additional context

- It happens with inside Popover too.
- Setting `defaultOpen` or setting `open` and `onOpenChange` by `useState` do not help with this issue.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     Dialog, Popover, Tooltip    |    1.0.7     |
| React            | n/a     |    ^18.2.0     |
| Browser          |    Chrome     |     v120.0.6099.10(arm64)    |
| Assistive tech   |     -    |   -   |
| Node             | n/a     |     >=16.0.0    |
| npm/yarn         |    n/a     |     >=7.10.0    |
| Operating System |    MacOS, Windows     |     MacOS v14 and newer, Windows 10    |

**Comment by mykola-kolomoyets** [comment] 2023-12-15 10:17
UPD: Tooltip works fine once we put the `Tooltip.Root` after `Dialog.Close`. Otherwise it will open automatically with dialog open.

**Comment by mykola-kolomoyets** [comment] 2023-12-15 10:19
like: 

Here it works fine
```tsx
<Tooltip.Provider>
        <Dialog.Root>
          <Dialog.Trigger>Open dialog with tooltip</Dialog.Trigger>
          <Dialog.Content>
            <Dialog.Title>Dialog title </Dialog.Title>
            <Dialog.Description>Dialog description</Dialog.Description>
            <Dialog.Close>Close dialog</Dialog.Close>
            // It works here
            <Tooltip.Root>
              <Tooltip.Trigger>Hover or Focus me</Tooltip.Trigger>
              <Tooltip.Portal>
                <Tooltip.Content sideOffset={5}>
                  Nicely done!
                  <Tooltip.Arrow offset={10} />
                </Tooltip.Content>
              </Tooltip.Portal>
            </Tooltip.Root>
          </Dialog.Content>
        </Dialog.Root>
      </Tooltip.Provider>
```

Here it opens by dialog open
```tsx
<Tooltip.Provider>
        <Dialog.Root>
          <Dialog.Trigger>Open dialog with tooltip</Dialog.Trigger>
          <Dialog.Content>
            <Dialog.Title>Dialog title </Dialog.Title>
            // Here it opens by dialog open
             <Tooltip.Root>
              <Tooltip.Trigger>Hover or Focus me</Tooltip.Trigger>
              <Tooltip.Portal>
                <Tooltip.Content sideOffset={5}>
                  Nicely done!
                  <Tooltip.Arrow offset={10} />
                </Tooltip.Content>
              </Tooltip.Portal>
            </Tooltip.Root>
            <Dialog.Description>Dialog description</Dialog.Description>
            <Dialog.Close>Close dialog</Dialog.Close>
          </Dialog.Content>
        </Dialog.Root>
      </Tooltip.Provider>
```

**Comment by mykola-kolomoyets** [comment] 2023-12-15 12:05
UPD: Situation i the same for HoverCard as well

**Comment by oyal** [comment] 2024-01-24 05:51
I am facing the same issue.

**Comment by BennyKok** [comment] 2024-02-04 10:24
I have the same problem, and seems like adding `autoFocus tabIndex={0}` somewhere so that i got the focus first fixed it
```tsx
<DialogTitle autoFocus tabIndex={0}>
    Workflow Dependencies
</DialogTitle>
```

**Comment by benoitgrelard** [comment] 2024-03-05 10:28
Duplicate of #2248

**Closed by benoitgrelard** 2024-03-05 10:28 UTC
