### ISSUE TITLE
[Select] Select inside a Dialog causes react-remove-scroll-bar to throws an error

### ISSUE THREAD

**Issue by petrlr14** [radix-ui/primitives#1670] opened 2022-09-16 23:16 UTC
### Current Behavior

Hi, using a Select inside a Dialog throws the following error: `react-remove-scroll-bar: cannot calculate scrollbar size because it is removed (overflow:hidden on body`. I can see why is happening, but I don't know if there's any workaround for this problem.

![Screen Shot 2022-09-16 at 17 05 58](https://user-images.githubusercontent.com/31825365/190828829-44132faa-f2ab-4736-b98a-e3669c62c761.png)

### Expected behavior

To not throw an error on nested portals

### Reproducible example

I found an example online that works, but upgrading to Select `1.0.0` causes the same problem
[Working example](https://codesandbox.io/s/radix-select-inside-radix-dialog-5lwgym)
[Not working example](https://codesandbox.io/s/radix-select-inside-radix-dialog-forked-jrgqqu?file=/SelectDemo.js)

### Additional context

I'm using Next.js on my local machine, but in the codesandbox it's using client side rendering.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dialog, @radix-ui/react-select     |       1.0.0  |
| React            | n/a     |   18.2.0      |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |      16.17.0   |
| npm/yarn         |         |   8.15.0      |
| Operating System |    MacOS Monterrey     |    12.6     |

**Comment by wilsonfaustino** [comment] 2022-09-17 00:27
Facing the same issue here.

**Comment by rafael-hc** [comment] 2022-09-17 15:45
Facing the same issue here.

**Comment by benoitgrelard** [comment] 2022-09-20 09:09
Duplicate of #1593
Also see #1594

**Closed by benoitgrelard** 2022-09-20 09:09 UTC
