### ISSUE TITLE
Dropdown focuses trigger button when closed - results in unwanted tooltip appearing 

### ISSUE THREAD

**Issue by piscopancer** [radix-ui/primitives#2727] opened 2024-02-26 20:10 UTC
https://github.com/radix-ui/primitives/assets/109352196/86e7bdad-a9a3-4ca4-abe5-dc8ef395a94b

here in this short video I have to click twice to remove the tooltip after the button is programatically selected again by the `Dropdown`. Here is the code:

**I am leaving it as is so as you get the full picture**

```tsx
'use client'

import Switch from '@/components/switch'
import { Tooltip } from '@/components/tooltip'
import { classes } from '@/utils'
import * as Dropdown from '@radix-ui/react-dropdown-menu'
import Link from 'next/link'
import { TbInfoSquareRounded, TbSettings } from 'react-icons/tb'

export default function Settings() {
  return (
    <Dropdown.Root>
      <Dropdown.Content className='z-[1]'>
        <>
          <ul className='flex flex-col rounded-xl border-2 border-zinc-800 bg-zinc-900 px-4 py-2 max-md:w-screen md:w-[32ch]'>
            <li>
              <Link href={'/info'} className='flex items-center rounded-2xl bg-zinc-800 px-4 py-2'>
                <TbInfoSquareRounded />
                <span className='ml-auto'>О МКРС</span>
              </Link>
            </li>
            <li>
              <span>Аниме девочки</span>
              <span>Включение может снизить скорость поиска: браузер сначала грузит гифки, только потом слово.</span>
              <Switch props={{}} />
            </li>
          </ul>
          <Dropdown.Arrow className='fill-zinc-800' />
        </>
      </Dropdown.Content>
      <Tooltip content='Настройки' sideOffset={6}>
        <Dropdown.Trigger className={classes('flex items-center justify-center rounded-full p-3 px-4 py-2 text-zinc-200 hover:bg-zinc-800')}>
          <TbSettings className='h-6' />
        </Dropdown.Trigger>
      </Tooltip>
    </Dropdown.Root>
  )
}
```

I understand that the tooltip appears because the button is **"tabbed"** by the dropdown component and I want to **prevent this tooltip from appearing while the button is focused**. How can I do it?

**Comment by benoitgrelard** [comment] 2024-03-05 10:24
Duplicate of #2593

**Closed by benoitgrelard** 2024-03-05 10:24 UTC

**Comment by ShadowOfTheSpace** [comment] 2024-11-04 18:45
Add `onCloseAutoFocus={(e) => e.preventDefault()}` to the `Dialog.Content` and `Dialog.Trigger` will be not focused when `Dialog` is closed.
