### ISSUE TITLE
[Tooltip] Keep tooltip open when hovering over it

### ISSUE THREAD

**Issue by cseas** [radix-ui/primitives#704] opened 2021-06-11 08:04 UTC
## Feature request

https://radix-ui.com/primitives/docs/components/tooltip

### Overview

Right now the Tooltip closes if we try to move our mouse over the content of the toolip. The opening and closing is purely based on the parent element to which the tooltip is attached. It'd be nice to have the tooltip stay open when hovering the mouse over its contents. Useful in a scenario when we want to select something from the tooltip or point to a specific thing inside the tooltip during a presentation.

### Examples in other libraries

This can achieved with the `interactive` prop in Material UI Tooltip:
https://material-ui.com/components/tooltips/#interactive

### Who does this impact? Who is this for?

Users of the project developed using this primitive.

### Additional context

Maybe if the Popover can be configured to open on hover and close when mouse is not over it or the parent element then that might work too:
https://radix-ui.com/primitives/docs/components/popover

**Comment by benoitgrelard** [comment] 2021-06-11 08:13
Hi @cseas, thanks for the suggestion.

I am closing it as it is a duplicate of #620.
Feel free to reopen if I misunderstood.

**Closed by benoitgrelard** 2021-06-11 08:13 UTC

**Comment by cseas** [comment] 2021-06-11 08:15
Thanks! Didn't notice that one. I'll add comments to that issue.
