### ISSUE TITLE
Too much recursion error, Select in Dialog in Firefox

### ISSUE THREAD

**Issue by Fillipee** [radix-ui/primitives#2505] opened 2023-11-01 20:29 UTC
### Current Behavior

I am using Shadcn's UI components which is using Radix UI. When having Select in Dialog this error shows. Weird is that this error shows ONLY on Firefox. 

![image](https://github.com/radix-ui/primitives/assets/84898571/e7412fa2-5988-4e2e-a0dc-c20e8a5dbc9e)

I was able to solve this issue by giving the DialogContent an ID and then in the SelectPortal I did this:
`<SelectPrimitive.Portal container={document.getElementById("test")}>`
This worked but the select options were not overlaping the dialog.
![image](https://github.com/radix-ui/primitives/assets/84898571/10cacc25-1b26-4f64-a37e-e715faf4d2b6)

### Expected behavior

There should not be any error and  the options should be overlapping the dialog.

### Additional context

I also tried the solution from this  issue #2390 
` "resolutions": {
    "@radix-ui/react-focus-scope": "1.0.4"
  }`
But that didn't work either.

These are my dependencies
![image](https://github.com/radix-ui/primitives/assets/84898571/0813ee5c-bf6e-48ea-a26c-f6622d86cb38)

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |    Firefox    |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by kotAPI** [comment] 2023-11-03 05:56
hmm, can you post the snippet you used? could be something related to state/unnecessary component re-renders, were you able to reproduce this?

**Comment by Saltys-Git** [comment] 2023-11-07 21:59
same happening for me only in Firefox. Chrome is normal.

`<Select
                  onValueChange={(e) => {
                    console.log("result", e);
                    setOrderInformationFormData((prev) => {
                      prev.orderType = e;
                      return { ...prev };
                    });
                  }}
                  value={orderInformationFormData.orderType}
                >
                  <SelectTrigger className="col-span-3" id="orderType">
                    <SelectValue placeholder="Select Table" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value={"collect"}>Collection</SelectItem>
                    <SelectItem value={"delivery"}>Delivery</SelectItem>
                    <SelectItem value={"inHouse"}>In House</SelectItem>
                  </SelectContent>
                </Select>`

**Comment by Ferraresir** [comment] 2023-11-08 23:25
same problem here, maybe you arrived in the same way, I was having problems with types on sheet v1.0.5 so i read that 1.0.4 didn't have that problem. That's when I started getting this error. so i update back to version 1.0.5 and  problem solved just need to handle the types errors.
and yes in chrome works just fine, not with firefox.

**Comment by hojjat-afsharan** [comment] 2023-11-14 15:25
also had the same issue on Firefox, downgrading @radix-ui/react-dialog from 1.0.5 to 1.0.4 fixed the issue as @Ferraresir  already mentioned. Btw I couldn't find why this issue is happening?

**Comment by HoliSimo** [comment] 2023-11-22 09:51
I have the same problem only with firefox.

These are my packages:
`"@radix-ui/react-accordion": "^1.1.0",
"@radix-ui/react-avatar": "^1.0.1",
"@radix-ui/react-checkbox": "^1.0.3",
"@radix-ui/react-collapsible": "^1.0.2",
"@radix-ui/react-dialog": "^1.0.2",
"@radix-ui/react-popover": "^1.0.4",
"@radix-ui/react-radio-group": "^1.1.2",
"@radix-ui/react-select": "^1.2.1",
"@radix-ui/react-tabs": "^1.0.3",
"@radix-ui/react-tooltip": "^1.0.5",
"@radix-ui/react-visually-hidden": "^1.0.1",`

The recursion error happen when I open a select and I go hover to the options.
I tried to update everything but it seems to not solve the problem.

**Comment by HoliSimo** [comment] 2023-11-22 09:53
Same problem for me, these are my packages.

```
"@radix-ui/react-accordion": "^1.1.0",
"@radix-ui/react-avatar": "^1.0.1",
"@radix-ui/react-checkbox": "^1.0.3",
"@radix-ui/react-collapsible": "^1.0.2",
"@radix-ui/react-dialog": "^1.0.2",
"@radix-ui/react-popover": "^1.0.4",
"@radix-ui/react-radio-group": "^1.1.2",
"@radix-ui/react-select": "^1.2.1",
"@radix-ui/react-tabs": "^1.0.3",
"@radix-ui/react-tooltip": "^1.0.5",
"@radix-ui/react-visually-hidden": "^1.0.1",
```

It happens when I go hover on options of the select. I tried to switch versions but it doesn't seem to solve the problem.

**Comment by benoitgrelard** [comment] 2024-03-05 10:41
Duplicate of #2390

**Closed by benoitgrelard** 2024-03-05 10:41 UTC
Labels: Resolution: Duplicate, Package: react/select

**Comment by shimulsql** [comment] 2024-08-27 11:53
same problem, when I try to open a modal from dropdown it happens

**Comment by roenschr** [comment] 2025-03-27 19:22
Does anybody have a solution for this? Is there a way to disable the focus functionality of the select component? But how?

**Comment by phil-hudson** [comment] 2025-04-03 00:37
+1 any solution?

**Comment by Seb0927** [comment] 2025-04-14 20:22
This was enough for me: https://github.com/radix-ui/primitives/issues/2390#issuecomment-2654031275

**Comment by maximemoreillon** [comment] 2025-04-19 01:25
I am currently having the same issue

**Comment by Seb0927** [comment] 2025-04-19 05:24
For anyone having this problem, this answer solved it:
https://github.com/radix-ui/primitives/issues/2390#issuecomment-2742640712
