### ISSUE TITLE
[DropdownMenu][Tooltip] combination fails to open menu

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#848] opened 2021-09-08 15:18 UTC
### Current Behavior

Menu won't open

### Expected behavior

both tooltip and menu should work

### Reproducible example

https://codesandbox.io/s/wandering-architecture-d8uw7?file=/src/App.tsx

### Additional context

Seems to be related to refs for me because I can see the menu isn't being positioned, so probably can't measure the trigger somehow.

**Comment by benoitgrelard** [comment] 2021-09-08 16:27
After some digging, we think this is because of nested contexts (in this case `Popper`).
Similar to this issue raised already for `ContextMenu`: #681

**Comment by jjenzz** [comment] 2021-09-15 12:17
Closing as duplicate of https://github.com/radix-ui/primitives/issues/681

**Closed by jjenzz** 2021-09-15 12:17 UTC
Labels: bug
