### ISSUE TITLE
Incorrect component names used in ScrollArea docs

### ISSUE THREAD

**Issue by smhutch** [radix-ui/primitives#637] opened 2021-05-05 12:42 UTC
### Current Behavior

The [ScrollArea](https://radix-ui.com/primitives/docs/components/scroll-area) docs use `ScrollArea.ScrollTrack` and `ScrollArea.ScrollThumb` in the example implementations. This both  a TypeScript error (Property 'ScrollTrack' does not exist on type), and a runtime error because these are both undefined on `ScollArea`

### Expected behavior

N/A

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/radix-scroll-area-report-x70n9?file=/src/App.tsx)

### Suggested solution

Replace `ScrollTrack` with `Track`, and `ScrollThumb` with `Thumb` in the docs.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |      scroll-area   |       0.0.12  |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment] 2021-05-05 14:44
Hey @smhutch, thanks for the report.
The issue is actually with the docs which live at https://github.com/radix-ui/website, so I'll close this issue here and will fix it there.

**Closed by benoitgrelard** 2021-05-05 14:44 UTC

**Comment by benoitgrelard** [comment] 2021-05-05 14:57
Fixed here: https://github.com/radix-ui/website/pull/150
