### ISSUE TITLE
[Select] Dropdown size doesn't fit trigger if used with a leading icon

### ISSUE THREAD

**Issue by steschwa** [radix-ui/primitives#1706] opened 2022-10-10 05:59 UTC
## Bug report

The current docs for `<Select>` have an example where `<Select.Icon>` is used on the right side of the trigger. If some however decides to swap it to the left side, the dropdown shrinks and does not fill the full width of the trigger.

### Current Behavior

![CleanShot 2022-10-10 at 07 52 37](https://user-images.githubusercontent.com/24265130/194805453-4dc8196d-ba81-4589-82b0-5f9234af3773.gif)

### Expected behavior

Independent where the icon is placed the opened dropdown should always fit the width of the trigger. This is the current behavior if a leading icon is used.

![CleanShot 2022-10-10 at 07 51 31](https://user-images.githubusercontent.com/24265130/194805424-530b3810-dae6-4f2a-8020-c0f0b1c302da.gif)

### Reproducible example

https://codesandbox.io/s/wonderful-sun-nt3o7g?file=/App.js

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  Select       |   v1.2.8      |
| React            |    |      v18.2.0   |
| Browser          |         |   Chrome      |

**Comment by benoitgrelard** [comment] 2022-10-10 08:32
Hey @steschwa,

This is expected because our position algorithm optimises for aligning the text in the trigger with the text in options.
Your first example looks like a RTL (right-to-left) layout but without using `dir` (or just a really contrived example).

If you use `dir="rtl"` it would handle things correctly like so:


https://user-images.githubusercontent.com/1539897/194826362-e84b3c12-2e01-49f9-a51e-c6064c155c38.mp4

I will close the issue as "expected behaviour" but please keep discussing if you think there's more to it.

✌️

**Closed by benoitgrelard** 2022-10-10 08:32 UTC
Labels: Resolution: Expected Behaviour, Package: react/select
