### ISSUE TITLE
NavigationMenuContent height doesn't always fit the height of its children

### ISSUE THREAD

**Issue by faithoyebode** [radix-ui/primitives#1356] opened 2022-04-29 11:21 UTC
## Bug report
This element which is a dropdown should always fit the height of it's children. However, after hovering a menu with whose NavigationMenuContent has a larger height and another menu is hovered next whose NavigationMenuContent has a smaller height than the previous one,  the dropdown retains the larger height of the NavigationMenuContent and overrides the smaller height
### Current Behavior
I discovered this css variable (--radix-navigation-menu-viewport-height) is responsible for setting the height. I've been having difficulty changing the value because the element  on which the height is set is a div created internally in the NavigationMenuPrimitive.Content element and it serves as a parent for the dropdown container

[bug-video.zip](https://github.com/radix-ui/primitives/files/8590369/bug-video.zip)

### Expected behavior

The NavigationMenuContent of each menu should always fit the height of its own children irrespective of the NavigationMenuContent that was displayed before or after

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |      @radix-ui/react-navigation-menu   |   ^0.1.2      |
| React            | n/a     |       ^17.0.2  |
| Browser          |      Chrome   |         |
| Assistive tech   |         |         |
| Node             | n/a     |    v16.13.0     |
| npm/yarn         |     yarn    |     1.22.17    |
| Operating System |    Winndows  |       10  |

**Comment by andy-hook** [comment] 2022-04-29 12:10
Hi @faithoyebode , I'm unable to reproduce this on my side. Would you be able to provide a code sandbox illustrating your use case and the described issue?

**Comment by faithoyebode** [comment] 2022-04-29 17:10
Hi @andy-hook . Thanks for the reply. I've been able to create a code sandbox illustrating the issue. 

Here is the link https://codesandbox.io/s/nostalgic-mcnulty-6u8dcw?file=/src/Header.tsx

If you hover on "shop products" and "skin concerns", you will see that the dropdown fits the height of its content.

However, as soon as you hover on "our story" whose dropdown has a bigger height than the previous two and try hovering on "skin concerns" and "shop products",  you will discover that their dropdown will now be bigger i.e. takes the height of that of "our story" dropdown. This shouldn't happen. Expected behavior is that the height of the dropdown should always fit their content.

**Comment by faithoyebode** [comment] 2022-04-29 17:10
Hi @andy-hook . Thanks for the reply. I've been able to create a code sandbox illustrating the issue. 

Here is the link https://codesandbox.io/s/nostalgic-mcnulty-6u8dcw?file=/src/Header.tsx

If you hover on "shop products" and "skin concerns", you will see that the dropdown fits the height of its content.

However, as soon as you hover on "our story" whose dropdown has a bigger height than the previous two and try hovering on "skin concerns" and "shop products",  you will discover that their dropdown will now be bigger i.e. takes the height of that of "our story" dropdown. This shouldn't happen. Expected behavior is that the height of the dropdown should always fit their content.

**Comment by andy-hook** [comment] 2022-04-29 18:02
@faithoyebode Thanks for putting that together 🙏  the problem is due to the css applied to `DropdownInsert`, in your example you are using relative percentages e.g. `height: 100%` but this is a problem because `Viewport` determines it’s own size based on that of the active `Content` (in your case `DropdownInsert`).

What this is effectively doing is telling the children to match their parent and at the same time the parent is trying to match its children.

Without height set:
https://codesandbox.io/s/misty-framework-zn03ts?file=/src/Header.tsx:4905-4919

Slightly simpler example:
https://codesandbox.io/s/eager-panini-1eszgf?file=/App.js  

The best approach is to not set the height on `Content` but instead let document flow them into their natural size, `Viewport` can then read them correctly and adjust in response.

I hope this makes sense, I’m going to close this for now but feel free to follow up if that wasn’t clear or you have other questions.

**Closed by andy-hook** 2022-04-29 18:02 UTC
Labels: Resolution: Needs Investigation, Package: react/navigation-menu

**Comment by faithoyebode** [comment] 2022-04-29 19:06
Thank you for the solution @andy-hook.
