### ISSUE TITLE
[Select] Clicking the selected item also triggers a click on the element immediately below it.

### ISSUE THREAD

**Issue by piotrkulpinski** [radix-ui/primitives#2165] opened 2023-05-26 08:49 UTC
## Bug report

On mobile, when clicking the item in the list, the click event is not canceled immediately and the element directly below it is clicked as well.

### Current Behavior

https://github.com/radix-ui/primitives/assets/358412/e5021105-7423-418b-8239-290583e787a3

### Expected behavior

To close the dialog and not click anything else

### Additional context

This happens for both `item-aligned` and `popper` position selected

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-select        |  1.2.1       |
| React            | n/a     | 18.2.0        |
| Browser          | Chrome        | 113        |
| Node             | n/a     | 18.13.0        |
| pnpm         |  n/a  |  8.5.1       |
| Operating System | MacOS        |  13.0.1       |

**Comment by benoitgrelard** [comment] 2023-05-26 10:16
Duplicate of #1658

**Closed by benoitgrelard** 2023-05-26 10:16 UTC
