### ISSUE TITLE
<DialogClose> doesn't trigger `onSubmit` for button with `type=submit`

### ISSUE THREAD

**Issue by kevin-nguyen-mirvac** [radix-ui/primitives#1109] opened 2022-01-22 07:01 UTC
## Bug report
- When using `<DialogClose>` on form submission, the dialog is unmounted before the `onSumbit` event can take place. This returns an error saying that
```
Form submission canceled because the form is not connected
```

### Current Behavior
- When using <DialogClose> on form submission, the dialog is unmounted before the form can take place

### Expected behavior

- Either have a way to handle this use case or DialogClose should execute the `onSubmit` handler when used within a form

### Reproducible example

[I've successfully replicated the issue here](https://codesandbox.io/s/elegant-voice-gn24p?file=/src/App.jsx:0-1909)

### Suggested solution

- Wondering if you guys support this use case. The code example in the `Dialog` documentation suggest that the `DialogClose` does submit the event since the button used is `Save profile`.
- I've tried abstracting the `Root` open event but it's hard to pass this state into the `Content`.

### Additional context

- In the meantime, I'm not closing the dialog.

### Your environment

- The codesandbox shows the exact issues but I'll add my local build here

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-dialog       | ^0.1.5         |
| React            | n/a     |  "^17.0.2"       |
| Browser          |         |Chrome         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |   yarn      |  1.22.17       |
| Operating System |  Arch Linux       |         |

**Comment by benoitgrelard** [comment] 2022-01-24 08:51
Hi @kevin-nguyen-mirvac,

I don't think the reproduction sandbox is up to date, I can't see anything in it.
That said I think I have a grasp of what you're talking about.

I don't think it's a radix specific issue though, and that would happen with any form that gets unmounted by clicking on the submit button.

This for example would show the same issue:
```tsx
export default function App() {
  const [open, setOpen] = React.useState(true);
  return open ? (
    <form onSubmit={() => console.log('submit')}>
      <input type="text" />
      <button type="submit" onClick={() => setOpen(false)}>
        Submit
      </button>
    </form>
  ) : null;
}
```

With that in mind, all you need to do with the dialog, is the same as what you'd need to do in this case.
That is: don't close on click of the submit button, and instead close, in the `onSubmit` handler.

For this you will need to:
- control the `open` state of the `Dialog` via the `open` and `onOpenChange` props.
- either use a regular submit button that you style or if you use the `DialogClose` you'll need to prevent our behaviour by calling `event.preventDefault()` in the `onClick` handler.

> Note: at the moment `Dialog.Close` is simply a button that updates the state and nothing more. That said our recommendation would always be to rely on the parts we give you, as these could see more things getting added to them down the line for accessibility, etc.

**Comment by jjenzz** [comment] 2022-01-24 16:20
@kevin-nguyen-mirvac closing this for now but feel free to keep the discussion going here is we can help further 🙂

**Closed by jjenzz** 2022-01-24 16:20 UTC

**Comment by benoitgrelard** [comment] 2022-02-14 14:16
@DanielBailey-web I think you are confusing `Dialog` and `AlertDialog`.
`Dialog` has `Dialog.Close`, `AlertDialog` has `AlertDialog.Cancel` and `AlertDialog.Action`.

**Comment by dnecklesportfolio** [comment] 2023-11-11 18:28
+1 I am having the same error with the same component.
The form would work on it's own successfully, but when I put it within Radix Dialog component, 
the console.log statement within the handleButtonClick function wouldn't run. 

and I also get the same error  `form submission is canceled because the form is not connected`

```typescript
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Counter } from "../components/Counter";
import TestFieldInput from "../components/TestFieldInput";
import * as Dialog from "@radix-ui/react-dialog";
import { Cross2Icon } from "@radix-ui/react-icons";
import React, { useState } from "react";

interface MyData {
  // Define the properties you expect in the JSON response
  key: string;
  value: number;
}

export const Dashboard: NextPage = () => {
  const [open, setOpen] = React.useState(false);
  const [inputText, setInputText] = useState("");
  const [userID, setuserID] = useState("clnz8jzpg00067z3yx42l0w60");

  const handleButtonClick = async (e: React.FormEvent<HTMLFormElement>) => {
    console.log("<handlebuttonclick></handlebuttonclick>");
    setOpen(false);
    e.preventDefault();
    try {
      const res = await fetch("/api/posts", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ userID: userID, message: inputText }),
      });
      const data: string = (await res.json()) as string; // Specify the type
      console.log("Bulletin Post created:", data);
    } catch (error) {
      console.error("Request failed:", error);
    }
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Counter />

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <div>
              <div className="scrollbar h-48 gap-4 overflow-scroll rounded-xl bg-white/10 p-4 text-white">
                <div className="flex space-x-16">
                  <h3 className="text-2xl font-bold">Notice Board</h3>

                  <Dialog.Root open={open} onOpenChange={setOpen}>
                    <Dialog.Trigger asChild>
                      <button className="Button violet">Add New Post</button>
                    </Dialog.Trigger>
                    <Dialog.Portal>
                      <Dialog.Overlay className="DialogOverlay" />
                      <Dialog.Content className="DialogContent">
                        <Dialog.Title className="DialogTitle">
                          Add Bulletin Post
                        </Dialog.Title>
                        <Dialog.Description className="DialogDescription">
                          Add a new bulletin post here. Click save when
                          you&apos;re done.
                        </Dialog.Description>

                        <div className="m-10 h-48 flex-col items-center justify-center">
                          <form onSubmit={handleButtonClick}>
                            <textarea
                              className="h-32 w-full rounded-md border p-2"
                              placeholder="Enter your text..."
                              value={inputText}
                              onChange={(
                                e: React.ChangeEvent<HTMLTextAreaElement>
                              ) => setInputText(e.target.value)}
                            ></textarea>

                            <div
                              style={{
                                display: "flex",
                                marginTop: 25,
                                justifyContent: "flex-end",
                              }}
                            >
                              <Dialog.Close asChild>
                                <button
                                  className="Button rounder-r bg-blue-600 p-2 text-white shadow duration-300 hover:bg-blue-700" type="submit">
                                  Submit
                                </button>
                              </Dialog.Close>
                            </div>
                            <Dialog.Close asChild>
                              <button className="IconButton" aria-label="Close">
                                <Cross2Icon />
                              </button>
                            </Dialog.Close>
                          </form>
                        </div>

                        {/* <fieldset className="Fieldset">
                          <label className="Label" htmlFor="name">
                            Name
                          </label>
                          <input
                            className="Input"
                            id="name"
                            defaultValue="Pedro Duarte"
                          />
                        </fieldset>
                        <fieldset className="Fieldset">
                          <label className="Label" htmlFor="username">
                            Username
                          </label>
                          <input
                            className="Input"
                            id="username"
                            defaultValue="@peduarte"
                          />
                        </fieldset> */}
                      </Dialog.Content>
                    </Dialog.Portal>
                  </Dialog.Root>
                </div>

                <p className="text-lg">
                  Welcome to the AlgoWorkout App! We are currently in Alpha and
                  will be continuing to update things. Click here to be
                  redirected to our active github page. Welcome to the
                  AlgoWorkout App! We are currently in Alpha and will be
                  continuing to update things. Click here to be redirected to
                  our active github page. Welcome to the AlgoWorkout App! We are
                  currently in Alpha and will be continuing to update things.
                  Click here to be redirected to our active github page. Welcome
                  to the AlgoWorkout App! We are currently in Alpha and will be
                  continuing to update things. Click here to be redirected to
                  our active github page. Welcome to the AlgoWorkout App! We are
                  currently in Alpha and will be continuing to update things.
                  Click here to be redirected to our active github page. Welcome
                  to the AlgoWorkout App! We are currently in Alpha and will be
                  continuing to update things. Click here to be redirected to
                  our active github page.
                </p>
              </div>
            </div>
            {/* <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            ></Link> */}
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="./api/auth/signout"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Log out →</h3>
              <div className="text-lg">Log out from this application!</div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

```

**Comment by dnecklesportfolio** [comment] 2023-11-11 19:11
> Hi @kevin-nguyen-mirvac,
> 
> I don't think the reproduction sandbox is up to date, I can't see anything in it. That said I think I have a grasp of what you're talking about.
> 
> I don't think it's a radix specific issue though, and that would happen with any form that gets unmounted by clicking on the submit button.
> 
> This for example would show the same issue:
> 
> ```tsx
> export default function App() {
>   const [open, setOpen] = React.useState(true);
>   return open ? (
>     <form onSubmit={() => console.log('submit')}>
>       <input type="text" />
>       <button type="submit" onClick={() => setOpen(false)}>
>         Submit
>       </button>
>     </form>
>   ) : null;
> }
> ```
> 
> With that in mind, all you need to do with the dialog, is the same as what you'd need to do in this case. That is: don't close on click of the submit button, and instead close, in the `onSubmit` handler.
> 
> For this you will need to:
> 
> * control the `open` state of the `Dialog` via the `open` and `onOpenChange` props.
> * either use a regular submit button that you style or if you use the `DialogClose` you'll need to prevent our behaviour by calling `event.preventDefault()` in the `onClick` handler.
> 
> > Note: at the moment `Dialog.Close` is simply a button that updates the state and nothing more. That said our recommendation would always be to rely on the parts we give you, as these could see more things getting added to them down the line for accessibility, etc.

Odd, I am doing the two suggested fixes but it still isn't working
