### ISSUE TITLE
[Popper] Collision avoidance won't switch from horizontal to vertical axis (or vice versa)

### ISSUE THREAD

**Issue by mrdavidjcole** [radix-ui/primitives#973] opened 2021-11-11 16:41 UTC
## Bug report

Note: I did see a similar issue, https://github.com/radix-ui/primitives/issues/557, but I think this is slightly different. Of course feel free to close as a dupe if you feel they're fundamentally the same though.

### Current Behavior

Collision avoidance for `Tooltip` (the component on which I first noticed this, but it seems to be rooted in `popper`) will switch between right/left and top/bottom, but seems to never switch its axis, like from right-to-top or right-to-bottom. This can be useful in width-constrained iframes for instance.

### Expected behavior

If a `Tooltip` with `avoidCollisions={true}` has `side="right"` but finds itself in a situation where there's not enough space on the right, and also not enough space on the left, but there _is_ enough space to the top or bottom, it should choose top or bottom.

### Reproducible example

https://glitch.com/edit/#!/radix-tooltip-collision-axis-switching

And the source for the iframe within that: 
https://glitch.com/edit/#!/iframe-for-radix-tooltip-collision-axis-switching

(I used Glitch here because I couldn't quickly figure out a way to get the Codesandbox working in an iframe)

### Suggested solution

Around https://github.com/radix-ui/primitives/blob/7106f97c84e01e3b4720208ea95c3e8c8da20b9b/packages/core/popper/src/popper.ts#L136-L141, if the opposite side _also_ collides, give the other axis a go.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-tooltip     |     0.1.1    |
| React            | n/a     |     17.0.2    |
| Browser          |    Chrome     |     96.0.4664.35 (Official Build) beta (arm64)    |
| Assistive tech   |     n/a    |         |
| Node             | n/a     |     12.x, says Glitch    |
| npm/yarn         |    Glitch uses pnpm     |     Not sure    |
| Operating System |     macOS    |     12.0.1    |

**Comment by benoitgrelard** [comment] 2021-11-11 21:10
hi @mrdavidjcole,

It is different from #557, so thanks for creating a new issue.
You are also right when you say it currently only swaps whilst preserving original axes.
This was in fact a design decision we made early on when spec'ing what we wanted this solution to be able to do.

I am not convinced that switching axes would be really beneficial in most cases.

For example with your tooltip demo, there's only a small margin of cases that would potentially be improved.
That's basically dependent on the size of the trigger itself.

ie. if you want it on the right, but it can't fit on either right or left, then it's very unlikely for it to fit at the top or bottom either

![image](https://user-images.githubusercontent.com/1539897/141368912-bf7bef1f-5f7b-47d6-9ed6-58aa3bd9cff2.png)

Because the placement would have to become `side="top"` and `align="end"`. So you're really only gaining the width of the trigger.

I think there are probably better ways we can try and improve collisions in general.

Also tooltips might be the worst example because:
1. They should normally be quite small as by design, they shouldn't hold much content
2. Some solutions that could work for things like `Popover` where we could allow the content to overlap the trigger whilst removing the arrow, wouldn't really be ergonomic for `Tooltip` because the interaction is on hover and the content is secondary so you need to be able to access that trigger still.

Thanks for bringing this up though, I am curious to hear what the team thinks about it in general, we can go from there.

cc @jjenzz @andy-hook

**Comment by threehams** [comment] 2022-02-18 20:14
As a real-world example of this, here is a screenshot of the tooltips used on the [docs page for Tooltip](https://www.radix-ui.com/docs/primitives/components/tooltip) on a 360px wide screen.

If the trigger is in the middle of the viewport, everything works as expected.
![Screenshot - 2_18_2022 , 12_12_32 PM](https://user-images.githubusercontent.com/1399894/154754808-97cd1850-c8de-45c7-9e3c-275fa461390f.png)

As the trigger reaches 1/3 to the left or right, however, the tooltip flies out to the left/right instead, cutting it off, despite there being enough room to show above or below.
![Screenshot - 2_18_2022 , 12_09_54 PM](https://user-images.githubusercontent.com/1399894/154754747-0f593be0-abb4-4e68-877c-b5e6984147a9.png)

Please let me know if this is a separate issue, and I'll open one for it.

**Comment by benoitgrelard** [comment] 2022-04-05 14:17
In many ways #557 would be a better resolution for this, so we'll close this one for now.

**Closed by benoitgrelard** 2022-04-05 14:17 UTC
Labels: Resolution: Duplicate

**Comment by jalooc** [comment] 2024-01-22 11:47
I agree with OP and I think that #557 doesn't fully replace an ability to switch axis. One use case is the horizontal mode on mobile / tablet - I can easily imagine a popover big enough to not fit on vertical axis of a trigger located near the center of the screen. So swapping axis could be like a _last resort_ solution for the placement algorithm after it figures that neither side of the defined axis is able to fit the particular popover.

**Comment by iworkinprogress** [comment] 2024-04-11 21:18
My use case that is failing is a wide Popover that I want to appear to the right of some highlighted text on larger devices but top on smaller devices. Sometimes the Popover trigger is quite wide and takes up almost the whole screen width on mobile so it can't fit to the right or left but can easily fit above.

To work around it I have to manually check the screen size and adjust the side to `top` on smaller screens and `right` on larger ones.
