### ISSUE TITLE
ERROR USING RADIX-UI WITH NEXTJS

### ISSUE THREAD

**Issue by gabrielmelodev** [radix-ui/primitives#1513] opened 2022-07-07 02:45 UTC
I'm using nextjs but this error happens when I use radix-ui
![code](https://user-images.githubusercontent.com/50870406/177679297-72de6e55-8f8b-47be-95de-35c2c397eac0.PNG)
![22](https://user-images.githubusercontent.com/50870406/177679307-e4f2b6aa-258e-4f28-b27b-a1aea4698141.PNG)
![radix](https://user-images.githubusercontent.com/50870406/177679323-ba8b4264-f0bf-4318-8a77-bd2868ece542.PNG)

**Comment by benoitgrelard** [comment] 2022-07-07 08:39
Hi @gabrielmelodev,

It's a little bit hard to figure out at first glance what the issue is just by looking.
Have you managed to replicate the issue in a simplified sandbox?

**Comment by nandorojo** [comment] 2022-07-07 18:16
This often happens if you have multiple versions of react installed for some reason. You could try `yarn why react`. If it logs multiple versions of react, try adding a yarn resolution to `package.json` fixing `react` to the version you want.

**Comment by andy-hook** [comment] 2022-07-12 08:13
Closing for now as we lack information and a possible solution has been provided. Feel free to follow up with a simplified reproduction and we'll do our best to help.

**Closed by andy-hook** 2022-07-12 08:13 UTC
