### ISSUE TITLE
Dropdown's stuck open on focus loss

### ISSUE THREAD

**Issue by ariesclark** [radix-ui/primitives#2246] opened 2023-07-03 21:24 UTC
### Current Behavior
When using the Dropdown component, `Alt+Tab` on Windows, or any other similar shortcut, lets you navigate between windows, but if you had a dropdown active, Radix loses control, and now **sub-menus will not disappear** until you click away.

### Reproducible example

https://codesandbox.io/s/radix-ui-primative-dropdown-reproduction-j479ny?file=/src/App.tsx

### Additional context

https://github.com/radix-ui/primitives/assets/10256477/d04c25d7-7507-458c-a901-0c39bacba6f9

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dropdown-menu | ^2.0.5 |
| React            | n/a     |         |
| Browser          |         | Firefox 114 on Windows 10|
| Assistive tech   |         |         |
| Node             | n/a     | 18.16.0 |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by joaom00** [comment] 2023-07-07 20:57
Thank you for the report. The issue is already being tracked in #1441

Duplicate of #1441

**Comment by benoitgrelard** [comment] 2024-03-08 14:42
Duplicate of #1441

**Closed by benoitgrelard** 2024-03-08 14:42 UTC
Labels: Resolution: Duplicate, Package: react/dropdown-menu
