### ISSUE TITLE
Radix Dialog + HCaptcha bug

### ISSUE THREAD

**Issue by gigamesh** [radix-ui/primitives#1385] opened 2022-05-10 17:19 UTC
### Current Behavior

When using Radix Dialog with [this HCaptcha package](https://github.com/hCaptcha/react-hcaptcha/), it isn't possible to click images in the captcha. Attempting to do so makes the captcha modal close. 

At first glance, it seems like a basic z-index issue but it is more complicated than that. I suspect it is something to do with the combination of the HCaptcha iframe & React Portal.

example of the bug: https://superficial-mark.surge.sh/
code: https://github.com/gigamesh/radix-bug

Any ideas would be much appreciated!

## versions
[package.json](https://github.com/gigamesh/radix-bug/blob/master/package.json)
```
pnpm v6.32.10
node v16.13.2
```

**Comment by benoitgrelard** [comment] 2022-05-11 09:02
Hi @gigamesh,

It will be because of the fact dialog disabled outside pointer events when modal.
There are a couple solutions for this:

### Solution 1
Target the modal from hcaptcha and add `pointer-events: auto` to it.
Unfortunately, I haven't been able to find a way to do this as the library seems pretty close and doesn't seems to give any access to DOM/attributes, etc.

### Solution 2
Make the radix dialog non-modal by passing `modal={false}` to `Dialog.Root`. That will fix the issue with pointer events, but it seems an issue still remains as the other dialog steals focus. To prevent that from happening, you can pass `onFocusOutside={event => event.preventDefault()}` to `Dialog.Content`.

https://codesandbox.io/s/elastic-moser-6nfkt9?file=/src/App.js

> Note: I've used your siteKey in the above sandbox, let me know when the issue is resolved your side with either solution and I'll delete the sandbox.

Closing the issue now, but feels free to keep discussing.

**Closed by benoitgrelard** 2022-05-11 09:02 UTC
Labels: Package: react/dialog, Resolution: Solution Provided

**Comment by gigamesh** [comment] 2022-05-11 19:06
@benoitgrelard huge thank you!

I tried solution 2 and it all seems to be working _except_ the DialogOverlay doesn't render. Is that by design?

**Comment by benoitgrelard** [comment] 2022-05-11 19:15
Yes that is by design for a non-modal dialog.

**Comment by gigamesh** [comment] 2022-05-11 19:25
dang ok - I think we'll need to fork the repo to opt out of that. thanks again

**Comment by benoitgrelard** [comment] 2022-05-11 19:27
That wouldn't be really valid to have an overlay for a non-modal dialog. Non-modal means all users can interact with what's outside the dialog. An overlay would block that.

In my opinion, a better solution is to work towards having access to the DOM produced by hcaptcha, or at least being able to add a data attribute, an id, or a className to it to be able to target it.

**Comment by gigamesh** [comment] 2022-05-11 19:51
Good point - I think the hcaptcha script is minified & fetched because its a paid service.

I could try doing surgery on the script but probably going to be easier to write a hacky script to find the DOM node based on its list of style attributes. Not great but should work fine for our needs.

**Comment by benoitgrelard** [comment] 2022-05-11 19:53
Is it open source? Could try and get a change in?

**Comment by gigamesh** [comment] 2022-05-11 21:47
no but that's ok - got it working. thanks again!

**Comment by kdhillon** [comment] 2022-09-11 03:22
Got this same issue -- and your solution worked! Thanks for posting!

Hacky as heck, but here's the way I found the DOM element:
```
 <HCaptcha
          sitekey="..."
          onOpen={() => {
            var hcaptchaElement = document.querySelector(
              '[title="Main content of the hCaptcha challenge"]'
            )
            if (hcaptchaElement) {
              ;(hcaptchaElement as HTMLElement).style.pointerEvents = 'auto'
            }
          }}
```
