### ISSUE TITLE
[Checkbox] Does not work in the documentation

### ISSUE THREAD

**Issue by talaikis** [radix-ui/primitives#597] opened 2021-04-13 20:23 UTC
### Current Behavior

```
<StyledCheckbox defaultChecked>
```

displays nothing checked on https://radix-ui.com/primitives/docs/components/checkbox

### Expected behavior

Should work.

### Your environment

Chrome 86
Windows 10

**Comment by benoitgrelard** [comment] 2021-04-14 07:42
@talaikis which example in the docs are you referring to?

**Comment by talaikis** [comment] 2021-04-14 07:45
> @talaikis which example in the docs are you referring to?

All checkboxes on https://radix-ui.com/primitives/docs/components/checkbox are passive and do not respond to clicks.

**Comment by benoitgrelard** [comment] 2021-04-14 07:47
on Chrome 86 on Windows 10?

**Comment by benoitgrelard** [comment] 2021-04-14 07:50
This is what I get:
https://user-images.githubusercontent.com/1539897/114673700-62507b80-9cfe-11eb-8db2-9a8b80284157.mov

**Comment by talaikis** [comment] 2021-04-14 07:50
> on Chrome 86 on Windows 10?

Yes, Firefox is ok.

**Comment by benoitgrelard** [comment] 2021-04-14 09:03
Ohhhhh I see, thanks for the screenshot that helped a bunch.
The issue is not with the primitive but rather with the dark mode treatment in the docs! haha
So the component is working fine, but the icon just isn't visible in dark mode.
I'll close this issue for now and open another on the docs website. Thanks!

**Closed by benoitgrelard** 2021-04-14 09:03 UTC
