### ISSUE TITLE
[ContextMenu] When the window is not tall enough, hovering items triggers scroll

### ISSUE THREAD

**Issue by wil93** [radix-ui/primitives#1116] opened 2022-01-25 11:50 UTC
### Current Behavior

The page scrolls when hovering elements, if there's not enough space

https://user-images.githubusercontent.com/1285361/150971159-4fe8d442-5250-4009-9e3e-b000bca4e79d.mov

### Expected behavior

I think the page shouldn't scroll... and by scrolling we still don't have access to the "hidden" items of the menu, so it doesn't seem to be useful anyway.

### Reproducible example

https://www.radix-ui.com/docs/primitives/components/context-menu

### Suggested solution

I'm not sure what's the best solution here, maybe allowing to scroll inside the menu itself? (Or would that be responsibility of the styles?) In any case the current behavior is a bit weird.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-context-menu      |      0.1.4   |
| React            | n/a     |         |
| Browser          |   Chrome      |     97.0.4692.71    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |  Mac OS       |    12.1     |

**Comment by benoitgrelard** [comment] 2022-01-25 12:09
See relevant discussion here: #1065

**Comment by benoitgrelard** [comment] 2022-01-25 12:10
In the case of `ContextMenu` you might be able to set a maxHeight (like 100vh) to mitigate the issue in the meantime.

**Comment by hipstersmoothie** [comment] 2022-01-29 03:03
There's a couple problems with the max height though. I saw another thread where you used useRect to take the top into account. This works but isn't the best. You'll end up having enough room to display the full context menu, but because of its align you get a menu that needs scrolling. It would be nice if radix itself took this into account. The current implementation will also flip  the align value when it thinks it will fit above. That adds to the complexity further. 

The current setup I have going that works but is complex to implement:

- align set to start
- collision detection off
- effect logic to use the menu's client rect to shift the menu on screen with negative margin. If the bottom is bigger than the screen it shift up. 
- also has a max height set for content longer than the screen

**Comment by benoitgrelard** [comment] 2022-04-05 15:28
Closing as duplicate of #393

**Closed by benoitgrelard** 2022-04-05 15:28 UTC
Labels: Resolution: Duplicate
