### ISSUE TITLE
[Dialog + Dropdown menu]The dialog cannot be reopened when closing the dropdown menu + dialog

### ISSUE THREAD

**Issue by nhannguyen0411** [radix-ui/primitives#2355] opened 2023-08-22 07:30 UTC
## Bug report

I have a button `Open Dialog` to open `<Dialog>`. In the body of the dialog, there is a button acting as a trigger for a <DropdownMenu>. Clicking this button causes the dropdown menu to open and then I click outside dialog to close all. After that, I try to click the open dialog button again but it doesn't work. Is this a bug?

### Current Behavior

Clicking outside dialog and then try to click the open dialog button again. You can not open dialog.

https://github.com/radix-ui/primitives/assets/49670360/67ee61b4-b5e9-409d-9615-7de6945bc3aa

### Expected behavior

https://github.com/radix-ui/primitives/assets/49670360/702e6eae-1397-4369-b35c-9df6c7f8a5dd

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/p/sandbox/competent-hooks-82dsph?file=%2Fdropdown.jsx%3A6%2C40)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | `@radix-ui/react-dropdown-menu` |  2.0.5  |
| Radix Package(s) | `@radix-ui/react-dialog` |  1.0.4  |
| React            | n/a     | 18.2.0  |
| Browser          | Chrome |         |
| Assistive tech   |         |         |
| Node             | n/a     |     16.17.0    |
| npm/yarn         |   pnpm    |   8.6.10      |
| Operating System |  MacOS       |    Ventura 13.5     |

**Comment by antonio-lazarenni** [comment] 2023-08-22 12:06
It also happens to me due to the Dialog and Select components using the body element as a portal.
https://www.radix-ui.com/primitives/docs/components/select#portal
https://www.radix-ui.com/primitives/docs/components/dialog#portal

When Dialog opens it applies an inline style to the body element `style="pointer-events: none;"`, the Select does the same.
When the Dialog is closed inline style remains because the Select component is still "open"

Maybe changing the portal element to the Dialogue itself resolves the issue

**Comment by Josevictor2** [comment] 2023-09-13 01:10
up

**Comment by ronaldruzicka** [comment] 2023-09-29 09:34
We have the same issue when opening `Dialog` from `DropdownMenu` because of the `style="pointer-events: none;"`.

I made a workaround for us to add `setTimeout` on the handler that opens dialog from `DropdownMenu`, it sends the execution to the end of event loop and therefore the `Dialog` opens when the `style` attribute is removed by `DropdownMenu`. But it would be nice for Radix to handle these behaviors.

Codesandbox: https://codesandbox.io/p/sandbox/radix-bug-dialog-from-dropdown-menu-z5h78x

**Comment by johnsonfamily1234** [comment] 2023-11-19 01:25
Just thought I'd add to this - I had this problem as well. Simple fix for me was to handle open state on the dropdown manually. 

- Add onClick in the element inside DropdownMenu.Trigger to setOpen in state
- use open prop in DropdownMenu.Root
- when calling any functions from menu interactions - setOpen to false
- make sure to add onOpenChange={setOpen} in DropdownMenu.Root, too

That did it for me.

**Comment by joaom00** [comment] 2023-11-20 22:16
@Kibuto your codesandbox is showing another behavior (the correct one I guess?). If you continue to experience the same problem, could you fix your example? Thanks!

**Comment by joaom00** [comment] 2023-11-20 22:19
> We have the same issue when opening `Dialog` from `DropdownMenu` because of the `style="pointer-events: none;"`.
> 
> Codesandbox: https://codesandbox.io/p/sandbox/radix-bug-dialog-from-dropdown-menu-z5h78x
> 
> I made a workaround for us to add `setTimeout` on the handler that opens dialog from `DropdownMenu`, it sends the execution to the end of event loop and therefore the `Dialog` opens when the `style` attribute is removed by `DropdownMenu`. But it would be nice for Radix to handle these behaviors.

Hey, I fork you example and after installing the dropdown and dialog for the latest versions everything seems to be working. Probably you hit https://github.com/radix-ui/primitives/issues/1088

[CodeSandbox](https://codesandbox.io/p/devbox/radix-bug-dialog-from-dropdown-menu-forked-lqdh44?file=%2FApp.jsx%3A31%2C31-31%2C63)

**Comment by joaom00** [comment] 2023-11-20 22:22
> Just thought I'd add to this - I had this problem as well. Simple fix for me was to handle open state on the dropdown manually.
> 
> * Add onClick in the element inside DropdownMenu.Trigger to setOpen in state
> * use open prop in DropdownMenu.Root
> * when calling any functions from menu interactions - setOpen to false
> * make sure to add onOpenChange={setOpen} in DropdownMenu.Root, too
> 
> That did it for me.

Do you have a reproducible example I can take a look at? you can also check if it is the same problem as @ronaldruzicka

**Comment by benoitgrelard** [comment] 2024-03-06 12:35
I cannot reproduce either, same conclusion @joaom00. I will close the issue as there hasn't been activity and the sandbox works as intended.

**Closed by benoitgrelard** 2024-03-06 12:35 UTC

**Comment by RonDaha** [comment] 2024-12-01 09:38
I also encounter the same issue, again that's the case when ever I try to use a Dialog inside any other component which creates a portal (Dropdown, Popover, etc.) If for example one of the dropdown options should open a Dialog this issue will occur. 

The workaround I did for now is the same as @ronaldruzicka, added a setTimeout to the state how open the Dialog

**Comment by ronaldruzicka** [comment] 2024-12-02 19:35
Yes it looks like it was fixed in the newer versions, thanks 👍

**Comment by AllanLandin** [comment] 2024-12-21 21:30
This issue helped me a lot. Thank u guys!

**Comment by yagnik1312** [comment] 2026-01-27 08:55
> It also happens to me due to the Dialog and Select components using the body element as a portal. https://www.radix-ui.com/primitives/docs/components/select#portal https://www.radix-ui.com/primitives/docs/components/dialog#portal
> 
> When Dialog opens it applies an inline style to the body element `style="pointer-events: none;"`, the Select does the same. When the Dialog is closed inline style remains because the Select component is still "open"
> 
> Maybe changing the portal element to the Dialogue itself resolves the issue

Thanks @antonio-lazarenni  for identifying root cause.
I ran into the same issue with Dialog + Select both portaling to document.body.

The root cause is exactly what you described: both components apply
style="pointer-events: none" to <body>, and when the Dialog closes, the inline style never gets cleaned up. This prevents reopening the Dialog.
I fixed it by manually resetting pointer-events when the Dialog closes, using onCloseAutoFocus on DialogContent.

```
const handleCloseAutoFocus = (event: Event) => {
  event.preventDefault(); // Prevent default focus return
  if (document.body.style.pointerEvents === "none") {
    document.body.style.pointerEvents = "";
  }
};

<Dialog open={open} onOpenChange={onOpenChange}>
  <DialogContent
        onCloseAutoFocus={handleCloseAutoFocus} // Key addition
  >
    {title && (
      <DialogHeader>
        <DialogTitle className="text-xl font-semibold border-b pb-2">
          {title}
        </DialogTitle>
      </DialogHeader>
    )}
    <div className="mt-4">{children}</div>
  </DialogContent>
</Dialog>
```

This ensures the body state is restored correctly and prevents the
“Dialog cannot be reopened after closing Select” issue.
Might not be the most elegant fix, but it’s safe and works reliably until portal handling is improved.
