### ISSUE TITLE
[NavigationMenu] Using forceMount breaks escape behavior for native dialogs

### ISSUE THREAD

**Issue by msfragala** [radix-ui/primitives#2476] opened 2023-10-21 21:05 UTC
### Current Behavior

When using the `forceMount` option on a `<NavigationMenu.Content>` component, native `<dialog>` elements on the page no longer close when pressing `Escape`. You _can_ work around this issue with a custom `onKeyDown` handler to close the dialog manually, but it's still probably best to avoid breaking native browser behaviors.

### Expected behavior

Native `<dialog>` elements behave as normal even if a forceMounted `<NavigationMenu.Content>` is present.

### Reproducible example

[CodeSandbox demo](https://codesandbox.io/p/sandbox/empty-night-dh5r7l)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    `@radix-ui/react-navigation-menu`     |    1.1.4     |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment] 2024-03-08 10:21
This is expected because `forceMount` is not supposed to be used to keep the content mounted at all time, it's there only to support JS-based exit animations, so the content should still be unmounted, otherwise things like focus trapping are still active (hence what you see).

I will close the issue because this is the intended behaviour based on what we currently offer.

Note that we have been discussing other options to keep content mounted for other reasons such as SEO, etc over in #1155

**Closed by benoitgrelard** 2024-03-08 10:21 UTC
