### ISSUE TITLE
Dropdown -  Dropdown is not expanding in mobile device's mozilla firefox browser.

### ISSUE THREAD

**Issue by hasan-deriv** [radix-ui/primitives#2241] opened 2023-07-03 08:05 UTC
### Current Behavior

[Screen Record](https://www.awesomescreenshot.com/video/18813673?key=d66c4459acd6f4e9f1e8c1b41504d5ab)

### Expected behavior

It should be behave as dropdown.

### Reproducible example

It is happening when `DropdownMenu.Root`'s prop `modal` is `false`

[CodeSandbox Template](https://codesandbox.io/p/sandbox/zealous-fog-mzw4rz?file=%2FApp.jsx%3A17%2C6-17%2C23)

**Comment by frstua** [comment] 2023-07-03 08:49
I have the same behavior. Also you can try to reproduce it here:

https://www.radix-ui.com/
https://0x0.st/H1qh.mp4

But here it works as expected:
https://www.radix-ui.com/docs/primitives/components/dropdown-menu
https://0x0.st/H1bs.mp4

**Comment by SaveliiLukash** [comment] 2023-12-01 10:42
+1 Experiencing the same behavior in both Firefox on Android and desktop Firefox responsive design mode.

Adding `onFocusOutside={ (event) => event.preventDefault() }` logic specifically to Firefox works, but is a really hacky solution.

Would be nice to have this case handled by the library itself.

**Comment by benoitgrelard** [comment] 2024-03-06 13:44
Duplicate of #2565

**Closed by benoitgrelard** 2024-03-06 13:44 UTC
Labels: Resolution: Duplicate, Package: react/dropdown-menu
