### ISSUE TITLE
[Dialog] Focus trap is escaped when clicked button in dialog disappears

### ISSUE THREAD

**Issue by third774** [radix-ui/primitives#2005] opened 2023-03-07 16:55 UTC
### Current Behavior
When a dialog is open and contains a button that disappears when clicked, the focus trap is escaped.

### Expected behavior
The focus trap should still contain focus. Not sure which element _should_ be focused (if any?)

### Reproducible example
https://codesandbox.io/s/intelligent-fog-ev69hj?file=/src/DialogDemo.tsx

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dialog        | 1.0.2        |
| React            | n/a     | 18.0.0        |
| Browser          | Chrome        | 110.0.5481.177 (Official Build) (arm64)        |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System | MacOS        | 13.2.1 (22D68)        |

**Comment by joaom00** [comment] 2023-03-07 17:54
Duplicate of #1498

**Closed** 2023-03-07 17:58 UTC
