### ISSUE TITLE
[Select] Focus prevents click event

### ISSUE THREAD

**Issue by tommybarvaag** [radix-ui/primitives#1246] opened 2022-03-15 11:23 UTC
### Current Behavior

The Select component's focus must be clicked away before the Select trigger is fired on mobile. The same focus bug also closes open popovers if the select component is present within the popover content.

https://user-images.githubusercontent.com/24416970/158367308-7d6c7f92-cd65-4664-bbb0-c24e97af3818.mp4

### Expected behavior

1. Clicks on select when focused should show values.
2. Clicks on select when focused within popovers should show values and shouldn't dismiss the popover.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/radix-ui-select-focus-popover-hmmpnq)

1. Load on iOS Safari or Chrome
2. Click select
3. Options are shown
4. Select value
5. Options are hidden and select is focused
6. Click select (you can see the black focus border dissapears but no options are shown)
7. Click select again
8. Options are shown

### Suggested solution

Regular click events fires naturally on macOS. Review touch start/click on phone?

### Additional context

Nothing further to add

### Your environment

Codesandbox

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-select + @radix-ui/react-popover        | Select 0.0.1 + Popover 0.1.6        |
| React            | n/a     | 17.0.2        | 
| Browser          | Safari + Chrome        | Safari 15.4 +  Chrome 99.0.4844.59         | 
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System | iOS        | 15.4         |

**Comment by nemdo** [comment] 2022-03-26 09:14
There is also an auto focus on the Trigger after closing the Dialog component on mobile. The user has to tap twice on the screen, first, on the Overlay to close the Dialog and an unexpected second time to remove the focus from the Trigger.

**Comment by benoitgrelard** [comment] 2022-04-04 15:01
Hi @tommybarvaag,

Thanks for reporting this.
I can reproduce the issue when touching an option to select it (as opposed to when touching outside to close it).
I think it has to do with our pointer events disabling handling on the body.

We'll look into it.

**Comment by benoitgrelard** [comment] 2022-04-06 09:36
Duplicate of #1241

**Closed by benoitgrelard** 2022-04-06 09:36 UTC
Labels: Type: Bug, Resolution: Duplicate
