### ISSUE TITLE
Focus doesn't work on select when form is validate.

### ISSUE THREAD

**Issue by Pieszczoch** [radix-ui/primitives#2661] opened 2024-01-23 13:47 UTC
When my form is validate on select, it doesn't focus on him like on input (react-hook-form + zod)
this is how it looks like on input: https://ui.shadcn.com/docs/components/input
and this on select: https://ui.shadcn.com/docs/components/select

Radix package  @radix-ui/react-select

**Comment by Pieszczoch** [comment] 2024-02-05 15:28
unfortunately, it does't work :(

**Comment by benoitgrelard** [comment] 2024-03-08 13:16
Duplicate of #2659 2659

**Closed by benoitgrelard** 2024-03-08 13:16 UTC

**Comment by lsdev200** [comment] 2024-05-07 04:25
it is worked for me .
thanks 

> You need to pass in the ref from your form field down to the select component, and note that select itself does not accept ref, but select trigger does, so you could just copy and past shadcn select example code for form
> 
> Add this `<SelectTrigger ref={field.ref}>`
> 
> Make sure you wrap all your fields in your form inside FormField and FormItem, otherwise the validation focus order gets out of whack

**Comment by madfcat** [comment] 2024-12-22 20:13
Using zod + react-hook-forms + radix ui.
My form validation never focuses on the Select wether I put ref in Select.Trigger as it was suggest or not.

I can `tab` in the browser and focus on the element. Accessibility works as it should. It just does not focus on the element if it is the first to have an error on it.
