### ISSUE TITLE
Transition Components

### ISSUE THREAD

**Issue by kaushalyap** [radix-ui/primitives#994] opened 2021-11-22 13:55 UTC
### Overview

Allow to do different transitions programmatically.

### Examples in other libraries

- [MUI Transitions](https://mui.com/components/transitions/) (Component based)
- [React Transition Group](https://github.com/reactjs/react-transition-group) (Component based)
- [HeadlessUI React Transtions](https://headlessui.dev/react/transition) (Component based)
- [React Transition State](https://github.com/szhsin/react-transition-state) ( Lightweight (~0.7KB), Hook based)

### Who does this impact? Who is this for?

Anyone who want to control transitions programmatically

### Additional context

I am aware of `Presence`  in Radix-UI which is seems limited and for internal use.

**Comment by benoitgrelard** [comment] 2021-11-22 14:08
hey @kaushalyap,

Our components should be compatible with any of these.
Are you having issues with it?
If so, are you able to provide a reproduction? You can use one of our docs example as a base by opening it in codesandbox.

**Comment by kaushalyap** [comment] 2021-11-22 14:47
@benoitgrelard I forgot that radix-ui primitives. sorry.

But it is nice to have own radix-ui transitions primitives do not you think?

**Comment by benoitgrelard** [comment] 2021-11-22 14:50
I see, that is something we could consider later down the line to fully fledge the library.
However right now it probably isn't a priority for us compared to say, other accessible primitives.

**Comment by kaushalyap** [comment] 2021-11-22 15:36
I'll keep it open as reference point for future users, if you do not mind, otherwise close the issue.

**Comment by jjenzz** [comment] 2021-11-22 15:38
> However right now it probably isn't a priority for us compared to say, other accessible primitives.

Agreed, and given that Radix UI is all about being **style-free** (our focus is functionality and a11y), providing a suite of components to that depend on styling doesn't really fall under our umbrella IMO.

The `Presence` component exists purely to postpone unmount when consumers add CSS animation to a primitive, it doesn't handle any styling.

**Comment by kaushalyap** [comment] 2021-11-22 15:56
@jjenzz https://tailwindui.com/components/application-ui/overlays/slide-overs#component-91416d48f50d19d1ad826e5a6c77b1e9

**Comment by jjenzz** [comment] 2021-11-22 16:23
@kaushalyap https://codesandbox.io/s/charming-sun-zp3ch?file=/src/App.js

**Comment by kaushalyap** [comment] 2021-11-22 17:03
@jjenzz thanks, what I linked was simple I want something bit complex like Amazon menu button, which also animate when clicking  through categories and navigating back.

Anyway to do other transitions like grow, fade, collapse, fade like in [MUI](https://mui.com/components/transitions/)?

**Comment by benoitgrelard** [comment] 2022-04-05 14:23
This isn't a priority for us so we'll close this as there are other alternatives in the community.

**Closed by benoitgrelard** 2022-04-05 14:23 UTC
Labels: Resolution: Won't Fix

**Comment by christian-reichart** [comment] 2023-01-19 08:30
I'm still having issues here. So just that I don't miss something, there is currently no way of detecting the open/closed state apart from the data-state attribute, correct?

I'm not sure how I can animate with this, since the Viewport just mounts and unmounts, so there is no initial state I can animate from. It would be a better solution for me, if I can somehow extract the state as a variable inside JSX and control showing/hiding stuff and applying classes that way. Is this in any way possible?

**Comment by andy-hook** [comment] 2023-01-19 08:48
> So just that I don't miss something, there is currently no way of detecting the open/closed state apart from the data-state attribute, correct?

@christian-reichart All of the primitives have controlled props to give you access to that state. Here's a recent example of using them to animate accordion with framer motion

https://codesandbox.io/s/framer-motion-accordion-9nup9l?file=/src/App.js

**Comment by christian-reichart** [comment] 2023-01-19 09:04
@andy-hook  ah thanks, i knew i missed something here

**Comment by christian-reichart** [comment] 2023-01-19 09:34
@andy-hook  Hm... so it exposes the state as a string, but I don't see how open/close state of the content is exposed?

**Comment by andy-hook** [comment] 2023-01-19 10:32
@christian-reichart which primitive are you referring to? in the accordion example `open = accordionValue === itemValue` so when the the value of accordion matches that of a given item then the content is `open`

**Comment by christian-reichart** [comment] 2023-01-19 10:55
@andy-hook sorry, talking about the navigation menu, and especially the Viewport component.

**Comment by christian-reichart** [comment] 2023-01-19 10:56
@andy-hook sorry, talking about the navigation menu, and especially the Viewport component.

**Comment by andy-hook** [comment] 2023-01-19 13:02
@christian-reichart here's an example of deriving the open state for `Content` and `Viewport` with that menu:

https://codesandbox.io/s/controlled-navigation-menu-states-65f7r4?file=/src/App.js

Let me know if that makes sense!

**Comment by christian-reichart** [comment] 2023-01-19 19:37
@andy-hook  Thank you dearly! <3
