### ISSUE TITLE
[New Primitive] Autocomplete

### ISSUE THREAD

**Issue by ranjithpmankada** [radix-ui/primitives#1486] opened 2022-06-21 05:04 UTC
### Overview

A fully customizable search box where the user can type text and filter the results.

### Examples in other libraries

- https://github.com/mui/material-ui/tree/master/packages/mui-material/src/Autocomplete
- https://github.com/ant-design/ant-design/tree/master/components/auto-complete
- https://github.com/sickdyd/react-search-autocomplete

### Who does this impact? Who is this for?
 Its main feature of all UI libraries. It used in case we want to select and search for some options like select menu. It useful in case of big options list.

**Comment by andy-hook** [comment] 2022-06-21 07:51
@benoitgrelard would this be covered by https://github.com/radix-ui/primitives/issues/1342 ?

**Comment by benoitgrelard** [comment] 2022-06-21 11:05
Yeah I think we can close as a duplicate of #1342

**Closed by benoitgrelard** 2022-06-21 11:05 UTC
Labels: Type: New Primitive
