### ISSUE TITLE
[Tooltip] Keep tooltip open when trigger is activated

### ISSUE THREAD

**Issue by bogdansoare** [radix-ui/primitives#1077] opened 2022-01-11 13:10 UTC
## Feature request

I'm trying to implement a tooltip that stays open when activating the trigger but couldn't find any prop to control this.
Something similar to the tooltip for reactions in slack.

### Overview

Add a prop to the tooltip Root component which if set to true will keep the tooltip open even when the trigger is activated

### Examples in other libraries

Chakra UI has `closeOnClick` prop https://chakra-ui.com/docs/overlay/tooltip#more-examples

**Comment by benoitgrelard** [comment] 2022-01-11 14:03
Hi @bogdansoare,

If I understand correctly you want your tooltips to work as normal except that when clicking the trigger you don't want the tooltip to close?

If so, it should be as simple as adding an `onClick` to the `Tooltip.Trigger` part and `event.preventDefault()` the behaviour we run.

**Comment by bogdansoare** [comment] 2022-01-11 16:44
Hey @benoitgrelard , thanks for the suggestion. 

I've tried adding `onClick` but it doesn't work, I thought it was because of the `asChild` prop but even without that prop it doesn't seem to work.

Here is a codesandbox https://codesandbox.io/s/heuristic-sutherland-5d0f6?file=/App.js

**Comment by benoitgrelard** [comment] 2022-01-11 21:38
Ah sorry, my bad it looks like we have an `onMouseDown` too, so if you do the same in `onMouseDown` it should work.

**Comment by jjenzz** [comment] 2022-01-12 22:52
Preventing default in the `onMouseDown` will also prevent the button from receiving focus though which isn't likely intended or a good idea.

@benoitgrelard Perhaps we need to expose a custom `onDismiss` event? 🤔

**Comment by diegohaz** [comment] 2022-01-13 10:15
> Wouldn't preventing default in the `onMouseDown` also prevent the button from receiving focus though?

Yeah, and also dragging and the `:active` state on some browsers.

I think relying on native `event.preventDefault()` is an anti-pattern, not only because of what @jjenzz said. But also because users will rely on implementation details. What if the library starts doing the action in the `onPointerDown` event instead of `onMouseDown` in the future?

Exposing props like the suggested `closeOnClick` is a better solution in my opinion.

**Comment by jjenzz** [comment] 2022-01-13 10:39
> Exposing props like the suggested `closeOnClick` is a better solution in my opinion.

We usually expose `CustomEvent`s like `onDismiss` that consumers can `event.preventDefault()` to avoid reliance on implementation detail and unexpected side effects, hence my suggestion.

There is often an alternate behaviour people want to implement when preventing ours so the event approach gives them the opportunity to prevent and do something else at the time our behaviour would usually execute, all in one prop (reduces API surface).

In the tooltip case, it isn't likely that they need to action something else as part of that event but we like to keep things consistent.

**Comment by benoitgrelard** [comment] 2022-01-13 11:06
Yeah that's all great points. We discussed this many times actually but for some reason I didn't think of it this time, so yeah perhaps we should add a custom event or something like that.

**Comment by jjenzz** [comment] 2022-01-15 10:22
Writing this down before I forget because it just dawned on me that `Tooltip` could probably use `DismissableLayer`, which made me realise that everywhere else we're currently using `Popper` uses `DismissableLayer`:

- `HoverCard` - we added `DismissableLayer` to this recently
- `Menu` - has been using `DismissableLayer` forever
- `Tooltip` - uses `useEscapeKeydown` but would benefit from `onPointerDownOutside` to solve this ticket

So, maybe it's worth baking `DismissableLayer` into `Popper.Content`? 🤔

**Comment by benoitgrelard** [comment] 2022-01-17 10:35
I'm not sure it would make sense for `Tooltip` to use `DismissableLayer`, because of the whole "outside" thing, with a tooltip, you're always outside, because focus never moves inside the tooltip content itself, so not entirely sure if it's just a stretch.

**Comment by jjenzz** [comment] 2022-01-17 17:33
> I'm not sure it would make sense for `Tooltip` to use `DismissableLayer`, because of the whole "outside" thing

That's just one part of `DismissableLayer` that we could disable for tooltip. The "layering' is the main feature of `DismissableLayer` in my mind. For example, if a tooltip is open inside a dialog and someone pressed `Escape` key, it would close the dialog atm.

**Comment by benoitgrelard** [comment] 2022-01-17 17:48
> The layering is the main feature of DismissableLayer in my mind. For example, if a tooltip is open inside a dialog and someone pressed Escape key, it would close the dialog atm.

Yeah I guess that's true, but in the example given somehow I "feel" like tooltip is much more temporary, less important and therefore having to double press escape here would kinda feel wrong?

**Comment by jjenzz** [comment] 2022-01-17 18:22
> having to double press escape here would kinda feel wrong?

Escape keypress is an a11y feature for tooltip, hence the logic existing in the component. If someone is pressing escape to close the tooltip, the expectation is that the tooltip closes and not the dialog.

> It typically appears after a small delay and disappears when `Escape` is pressed or on mouse out.

**Comment by benoitgrelard** [comment] 2022-01-17 18:30
Yeah if I put my "feel" aside and think pragmatically, I think you're right, basically anything that is "dismissable" by design should dismiss just itself.

**Comment by olehkhalin** [comment] 2022-02-24 23:08
Hi!

Found this issue and want to ask u a question about the same functionality for the `HoverCard` component. When I'm trying to use `event.preventDefault()` in `onClick` and `onMouseDown` a hovercard closes anyway.

**Comment by benoitgrelard** [comment] 2022-02-25 08:40
Hey @olehkhalin,

Can you show me a sandbox with what you're trying to do? Then I should be able to help you with it.

✌️

**Comment by olehkhalin** [comment] 2022-02-25 16:15
Yeah, sorry for that.

I have created a sandbox based on the one used in docs. There is the link https://codesandbox.io/s/relaxed-cannon-hjhtsm?file=/App.js

I have added there `event.preventDefault()` on `Trigger` component.

**Expected behavior:** hovercard doesn't close on trigger click.

**Comment by jjenzz** [comment] 2022-02-25 16:48
@olehkhalin when the link is clicked it would change the page URL so i'm unsure why keeping it open would be useful... what's your use-case?

**Comment by liaujianjie** [comment] 2022-02-26 09:33
I can contribute an example use case. :-)

Sometimes, we may have buttons or interactive components that copies a value when clicked. E.g. "click to copy URL". In such a case, we may want the tooltip to remain open after clicking on it so that we can show the the value is indeed copied to the clipboard.

![CleanShot 2022-02-26 at 17 31 39](https://user-images.githubusercontent.com/3143132/155837994-15c65dbe-9089-499a-9a6a-22beddde35df.gif)

**Comment by AdsonCicilioti** [comment] 2022-03-15 06:23
> 

Yep! 
I really need this behavior myself and I thought it would already be implemented. But OK! Primitives are great, and this feature would definitely be awesome.

**Comment by benoitgrelard** [comment] 2022-03-31 12:57
Closing this issue in favour of a new one capturing the change: #1290

**Closed by benoitgrelard** 2022-03-31 12:57 UTC
Labels: feature

**Comment by arpitprod** [comment] 2022-04-07 06:20
> I can contribute an example use case. :-)
> 
> Sometimes, we may have buttons or interactive components that copies a value when clicked. E.g. "click to copy URL". In such a case, we may want the tooltip to remain open after clicking on it so that we can show the the value is indeed copied to the clipboard.
> 
> ![CleanShot 2022-02-26 at 17 31 39](https://user-images.githubusercontent.com/3143132/155837994-15c65dbe-9089-499a-9a6a-22beddde35df.gif)

Please share example code

**Comment by KonradLinkowski** [comment] 2022-05-25 15:21
> You can also see here an example of how to keep it open on activation thanks to the update: https://github.com/radix-ui/primitives/blob/main/packages/react/tooltip/src/Tooltip.stories.tsx#L588-L614

Just to make sure that the line reference won't change
https://github.com/radix-ui/primitives/blob/768bc53149aa1f432b5e630b99589237f6333364/packages/react/tooltip/src/Tooltip.stories.tsx#L617-L643

**Comment by benoitgrelard** [comment] 2022-05-25 16:22
Thanks!

**Comment by benoitgrelard** [comment] 2022-07-13 07:36
Hey @dannyhkim, I have answered your question in #1524, but feel free to comment in that issue still if you need more help.
