### ISSUE TITLE
`modal` components are incompatible with third-party modals

### ISSUE THREAD

**Issue by ciampo** [radix-ui/primitives#2219] opened 2023-06-19 07:32 UTC
### Current Behavior

When using any components supporting the option to render as `modal`, other third-party pieces of UI that would need to also render as modal on top of the radix component stop working as expected, due to the pointer events / scroll / focus trap that Radix components create.

**This makes it practically impossible to integrate Radix in existing projects, where not all UI elements are using Radix.**

Furthermore, this also breaks browser extensions (like Grammarly or Google Translate) that would display additional UI when activated.

### Expected behavior

There should be a way for third-party "Modal" content to render and be interactive of top of Radix's modal components.

### Reproducible example

https://codesandbox.io/s/interesting-julien-9lr83p

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by JesseKuntz** [comment] 2023-06-20 19:23
Encountering the same issue. I've tried preventing default in `onInteractOutside` (and a few of the other options) but I've resorted to closing the Radix Dialog before opening the 3rd party modal, and opening the Radix Dialog again upon closing the 3rd party modal.

**Comment by ciampo** [comment] 2023-06-21 08:45
> I've resorted to closing the Radix Dialog before opening the 3rd party modal, and opening the Radix Dialog again upon closing the 3rd party modal.

This may not be an option for all projects, especially if not the entirety of the UI is implemented using Radix. On top of that, browser overlays and browser extensions may not work properly too, which is not good.

**Comment by JesseKuntz** [comment] 2023-06-25 04:10
I agree. I think we're just missing a way to remove the focus trap on demand.

**Comment by AlexMNet** [comment] 2023-07-31 01:26
@JesseKuntz @ciampo it was so much gymnastics just to get that too work properly I just created my own dialog. Haha. I am using the next-cloudindary widget to upload images which opens up in its own modal. Hopefully this will get fixed soon as this is a common scenario.

**Comment by magoz** [comment] 2023-08-15 11:07
I'm also encountering this issue. In my case, the issue is not being able to get pointer events when the Dialog is open.

**Comment by Jonas-C** [comment] 2023-09-05 11:12
Related discussions in other repositories: 
https://github.com/pacocoursey/cmdk/issues/167
https://github.com/JedWatson/react-select/issues/5732

Has anyone managed to find a fix for this while keeping the `modal` functionality?

**Comment by nacho-villanueva** [comment] 2023-09-20 01:44
I'm having the same problem. I have a modal with a login form and all password managers like NordPass become unclickable. Any updates on this? Seems quite like a pretty common scenario in general.

**Comment by nacho-villanueva** [comment] 2023-09-20 01:57
A quick fix for me was to add this to the css: 
```
body[style*='pointer-events: none'] > * {
  pointer-events: all;
}
```

(Thank you ChatGPT)

**Comment by benoitgrelard** [comment] 2024-03-07 09:34
Duplicate of #1859

**Closed by benoitgrelard** 2024-03-07 09:34 UTC
Labels: Resolution: Duplicate, Package: react/dialog
