### ISSUE TITLE
[Accordion][Collapsible] `styled(Content)` seems to break animation

### ISSUE THREAD

**Issue by IHIutch** [radix-ui/primitives#1509] opened 2022-07-05 00:19 UTC
### Current Behavior

Collapsible or Accordion (maybe others?) receive inline styles of 
```
transition-duration: 0s;
animation-duration: 0s;
animation-fill-mode: none;
```

when component state is managed externally

### Expected behavior

Components receive the same style attributes regardless of where component state is managed

### Reproducible example

https://codesandbox.io/s/laughing-meitner-nqu71w?file=/src/App.js

### Suggested solution

Components don't get the following inline styles
```
transition-duration: 0s;
animation-duration: 0s;
animation-fill-mode: none;
```

### Additional context

I don't see anywhere in the docs that this is mentioned so it feels like a bug to me. I'm particularly running into issues when I need to access the state of an Accordion or set the default value when the page loads. But this causes my components to never animate when open or closing.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Accordion, Collapsible     |      0.1.6   |
| React            | n/a     |    17.0.2     |
| Browser          |     Firefox    |     102.0     |
| Assistive tech   |      n/a   |         |
| Node             | n/a     |     v16.14.0    |
| npm/yarn         |     yarn    |     1.22.19    |
| Operating System |     MacOS    |       12.4  |

**Comment by benoitgrelard** [comment] 2022-07-05 08:03
Hi @IHIutch,

Thanks for reporting.
I looked into it a bit, this is actually quite weird. I couldn't reproduce it locally on `main`, so I thought we'd fix the issue recently and you'd just need to upgrade to the latest release candidate. But I tried that in your sandbox and it didn't work still. The only difference I could see was that in our storybook we use stitches core API (`css()`) and you use `styled()` so it creates a new element.

It looks like that's what breaks it, but I'm really stumped as to why it does…

**Comment by benoitgrelard** [comment] 2022-07-05 08:36
Oh! I found what your issue is, you are re-defining the animations/styled component in render!

This bit:
```tsx
  const open = keyframes({
    from: { height: 0 },
    to: { height: "var(--radix-collapsible-content-height)" }
  });

  const close = keyframes({
    from: { height: "var(--radix-collapsible-content-height)" },
    to: { height: 0 }
  });

  const CollapsibleContent = styled(Collapsible.Content, {
    overflow: "hidden",
    '&[data-state="open"]': {
      animation: `${open} 200ms ease-in-out forwards`
    },
    '&[data-state="closed"]': {
      animation: `${close} 200ms ease-in-out forwards`
    }
  });
```

needs to be outside of the main component (`App`), they need to be static at the module level.

I'll close the issue now.

✌️

**Closed by benoitgrelard** 2022-07-05 08:36 UTC
Labels: Type: Bug, Resolution: Needs Investigation, Package: react/accordion, Package: react/collapsible

**Comment by IHIutch** [comment] 2022-07-05 11:46
Oohh I see. Thank you very much for your help!

**Comment by benoitgrelard** [comment] 2022-07-05 13:48
No, those styles are necessary for the animation handling.
