### ISSUE TITLE
[Dialog] Dialog.Overlay preventing mousewheel scrolls from happening outside the modal

### ISSUE THREAD

**Issue by mauriciosoares** [radix-ui/primitives#2125] opened 2023-05-02 16:35 UTC
### Current Behavior

When using a Dialog with an `Overlay`, all elements outside the dialog are not scrollable using mouse wheels, even if that element has a `pointerEvents` set to `auto`

https://user-images.githubusercontent.com/2321259/235728624-12a5de20-0a58-41f8-aa32-ac99eb342794.mov

### Expected behavior

Elements outisde a Dialog should be scrollable when we define a `pointerEvents` different from `none`.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/holy-glitter-rky5qp)

In this template if you uncomment `<Overlay />` then the gray div with some text is not scrollable anymore using a mouse wheel

### Suggested solution

Not sure the reason why Overlay is preventing this behaviour, but honestly I'd just remove whatever is preventing these mouse wheel scrollings from happening

### Additional context

To give more context, I have a custom select input that renders the options in a fixed div that is rendered in the root of the HTML inside the body, so when I use this select input inside a modal, I just can't scroll though the options with my mousewheel anymore.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dialog     |     1.0.3    |
| React            | n/a     |     18.2.0    |
| Browser          |     Chrome    |     112.0.5615.137    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |   Mac      |     Ventura (13.3.1)    |

**Comment by joaom00** [comment] 2023-05-12 15:02
Same as https://github.com/radix-ui/primitives/issues/1159. If you are using the Radix select, a workaround would be to remove the `Portal` part of the select

**Comment by joaom00** [comment] 2023-07-04 16:08
Hey @mauriciosoares, 

disabling interaction outside the modal is the default behavior. If you want the outside elements to be interactive you need to pass `modal={false}`. However, there is bug #1159 that it is not possible to scroll on elements inside `Dialog.Content`. Would this be your case?

**Comment by mauriciosoares** [comment] 2023-07-04 17:50
@joaom00 the problem is that this element that is "in theory" outside the modal, is actually the dropdown from a select input, this dropdown is rendered outside the modal using react's Portal in the document's body. So in terms of usability that content is used inside the modal, and not outside it... But the HTML is rendered outside it. That's why I think elements outside the modal, which we explicitly set the `pointerEvents` to `auto` should be scrollable.

**Comment by joaom00** [comment] 2023-07-04 18:03
Oh okay, so the issue is the same as in #1159. A PR #2250 has been raised to fix this issue

**Comment by Morningstar0000** [comment] 2024-03-01 14:28
Pls there should fix scrollable inside Dialog itself .. am facing this now . And had tried all my way to I can't.. so its seems is the @Radix thing to work on. Because i can see smililar conplaint going on.. Pls they should fix this up . Mean while if anyone had a  other way to do it in react ..  pls help out .

**Comment by benoitgrelard** [comment] 2024-03-07 09:35
Duplicate of #1159

**Closed by benoitgrelard** 2024-03-07 09:35 UTC
Labels: Resolution: Duplicate, Package: react/dialog
