### ISSUE TITLE
When server rendering, you must wrap your application in an <IdProvider>

### ISSUE THREAD

**Issue by albingroen** [radix-ui/primitives#967] opened 2021-11-10 08:54 UTC
### Current Behavior

Using a Radix primitive in a server rendered environment like Next.js produced this message in the server console:

```
When server rendering, you must wrap your application in an <IdProvider> to ensure consistent ids are generated between the client and server.
```

Wrapping the app in a `<IdProvider>` doesn't seem to help either.

### Expected behavior

Wrapping the app in a `<IdProvider>` should make the message disappear.

### Reproducible example

[GitHub repo](https://github.com/albingroen/react-cmdk-usage)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dialog     |     ^0.1.1    |
| React            | n/a     |     ^17.0.2   |
| Browser          |      Safari   |     15.1    |
| Node             | n/a     |     14.15.5    |
| npm/yarn         |    yarn     |     1.22.15    |
| Operating System |    MacOS     |    12.0.1     |

**Comment by benoitgrelard** [comment] 2021-11-10 09:45
Closing as duplicate of #811

**Closed by benoitgrelard** 2021-11-10 09:45 UTC

**Comment by daniellizik** [comment] 2022-09-26 02:17
how can I silence this message? i'm not able to upgrade to react 18 at the moment and this msg is adding unnecessary messages to kibana
