### ISSUE TITLE
react-remove-scroll keeps give me warnings after use the Select in the Dialog component

### ISSUE THREAD

**Issue by abbazabacto** [radix-ui/primitives#2395] opened 2023-09-19 10:02 UTC
The console error in the linked [discussion](https://github.com/radix-ui/primitives/discussions/1594) can be prevented by upgrading the `react-remove-scroll` to version `2.5.6` which includes the [fix of `react-remove-scroll-bar` version `2.3.4`](https://github.com/theKashey/react-remove-scroll-bar/issues/35#issuecomment-1276809669).

For example in the Dialog [package.json](https://github.com/radix-ui/primitives/blob/28bebf2c6992d056244845c898abeff45dec2871/packages/react/dialog/package.json#L45)

Without this upgrade I need to use module resolution to enforce `react-remove-scroll` version `2.5.6` to prevent the console error to appear in my console.

### Discussed in https://github.com/radix-ui/primitives/discussions/1594

<div type='discussions-op-text'>

<sup>Originally posted by **JhonM** August  3, 2022</sup>
Hi,

When I use a `Select` component inside the `Dialog`, I get an error when clicking the `Select` trigger.
```
react-remove-scroll-bar: cannot calculate scrollbar size because it is removed (overflow:hidden on body 
    at RemoveScrollBar (http://localhost:3000/project-x/index.js:45320:29)
    at RemoveScrollSideCar (http://localhost:3000/project-x/index.js:45444:37)
```
I noticed that react-remove-scroll adds an overflow hidden on the `body` element that is causing this error. Is there any solution how to fix this?

For clarification I created a sandbox where I could reproduce it: https://codesandbox.io/s/select-in-dialog-primitive-react-remove-scroll-error-dfkobw

Thank You in advance and keep up the great work!

Jhon 
</div>

**Comment by benoitgrelard** [comment] 2024-03-07 09:41
Duplicate of #2367

**Closed by benoitgrelard** 2024-03-07 09:41 UTC
