### ISSUE TITLE
[DropdownMenu] `jest` / `react-testing-library` tests failing on `@radix-ui/react-dropdown-menu` after upgrade 

### ISSUE THREAD

**Issue by ItzaMi** [radix-ui/primitives#1220] opened 2022-03-03 18:44 UTC
### Current Behavior

Went from `"@radix-ui/react-dropdown-menu": "0.1.4",` to ` "@radix-ui/react-dropdown-menu": "0.1.6",` and the tests were working on `0.1.4`.
Actually, any test that involves some sort of _pop up box_ appearing currently fails (so `"@radix-ui/react-dropdown-menu": "0.1.6"` and `"@radix-ui/react-dialog": "0.1.7",` for me).

My current test looks like this (there's more of it inside my `CodeSandbox` example down below)
```javascript
test('BulkActions dropdown gets clicked and shows content', () => {
  userEvent.click(screen.getByTestId(bulkActionsDropdownName))

  expect(screen.queryByTestId(dropdownContentName)).toBeInTheDocument()
})
```

Output looks like this
```
 FAIL  src/components/BulkActions/bulk-actions.test.tsx
  ✓ BulkActions gets rendered (20 ms)
  ✕ BulkActions dropdown gets clicked and shows content (23 ms)

  ● BulkActions dropdown gets clicked and shows content

    expect(received).toBeInTheDocument()

    received value must be an HTMLElement or an SVGElement.
    Received has value: null

      39 |   userEvent.click(screen.getByTestId(bulkActionsDropdownName))
      40 |
    > 41 |   expect(screen.queryByTestId(dropdownContentName)).toBeInTheDocument()
         |                                                     ^
      42 | })
      43 |
```

This was a passing test using `"@radix-ui/react-dropdown-menu": "0.1.4"`. Seems like the `userEvent.click` isn't getting triggered

### Expected behavior

Having not changed anything within my code except for upgrading the dependency, I expect the test to pass

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/laughing-shirley-l4vtzl?file=/src/App.tsx)

### Suggested solution

No idea, I don't even understand what's happening, really

### Additional context

_Nothing to add_

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-dropdown-menu    |    0.1.6     |
| React            | n/a     |    17.0.2     |
| Browser          |    Chrome     |     Version 98.0.4758.80    |
| Assistive tech   |     -    |     -    |
| Node             | n/a     |    v14.19.0     |
| npm/yarn         |    yarn     |    1.22.17     |
| Operating System |   MacOS      |      11.2.3   |

**Comment by assuncaocharles** [comment] 2022-03-06 17:04
I feel like this https://github.com/radix-ui/primitives/commit/c8745e582710be77178ccf553554d90b2a59c74e is possibly the cause ?!

**Comment by erkivrff** [comment] 2022-03-09 18:29
I can confirm this. Started writing tests for a component that consumes `@radix-ui/react-dropdown-menu@0.1.6` and was scratching my head as couldn't figure out what's wrong with my test. 

Downgrading to `0.1.4` made my test(s) pass.

**Comment by daves-weblab** [comment] 2022-03-11 08:48
Can confirm this. As a workaround I got my tests to work by triggering an arrow down event on the menu trigger ` userEvent.type(trigger, '{arrowdown}');`

**Comment by andy-hook** [comment] 2022-04-04 11:59
Related: https://github.com/radix-ui/primitives/issues/856

Sorry for the delay responding here. You’re seeing this because the event bindings were adjusted in the recent version and now exclusively bind to `PointerEvent`, where before they also used `onClick`.

JSDOM doesn’t currently support `PointerEvent`, and thus testing-library can't provide the correct properties on the Event.

Providing you’re using `user-event`, testing lib should be firing `PointerEvent`s, but you’ll need to provide your own implementation to be able to test with the expected properties: 

```ts
 // setupTests.ts

// JSDOM doesn't implement PointerEvent so we need to mock our own implementation
// Default to mouse left click interaction
// https://github.com/radix-ui/primitives/issues/1207
// https://github.com/jsdom/jsdom/pull/2666
class MockPointerEvent extends Event {
  button: number;
  ctrlKey: boolean;
  pointerType: string;

  constructor(type: string, props: PointerEventInit) {
    super(type, props);
    this.button = props.button || 0;
    this.ctrlKey = props.ctrlKey || false;
    this.pointerType = props.pointerType || 'mouse';
  }
}

window.PointerEvent = MockPointerEvent as any;

```

The above sets some properties to mock a "mouse left click" by default, you can pass your own properties inline too when needed:

```js
userEvent.click(myElem, { pointerType: "touch", ... })
```

I'll make a note to add something about this in our documentation as it is quite a common issue, hopefully the above helps though. I'm going to close the issue now but feel free to follow up if you have any other questions 🙏

**Closed by andy-hook** 2022-04-04 11:59 UTC
