### ISSUE TITLE
[Select] Are there any plans to support non-modal mode in the select component?

### ISSUE THREAD

**Issue by hoiheart** [radix-ui/primitives#2486] opened 2023-10-25 22:30 UTC
### Overview

The popover, dropdown menu supports modal and non-modal modes, which allow you to click on external elements even when the content is opened.

However, the select component does not support non-modal mode, so you cannot click on an external element while the select is open.

In native select, UX is a different situation because external elements can be clicked while open.

Do you have plans to support non-modal mode or can you guide me on other ways to click external elements?

**Comment by BrendanBerkley** [comment] 2023-12-05 21:25
I'm wondering this as well. In particular, I'm looking to implement a design where the dropdown opens underneath and remains there while you scroll.

Even if `Select.Portal` did what I expected here (it doesn't, because both of `Select.Content`'s position options use `position: fixed`, which means an inline style is impossible without overrides), you end up in trouble because focus guard takes out the ability to scroll.

**Comment by ThePiyushAggarwal** [comment] 2023-12-06 17:02
+1

**Comment by pietroanello** [comment] 2024-02-19 15:35
Any plans about this?

**Comment by benoitgrelard** [comment] 2024-03-06 15:02
Duplicate of #1927

**Closed by benoitgrelard** 2024-03-06 15:02 UTC

**Comment by YakuBrangJa** [comment] 2026-01-16 06:07
If anyone's only issue is layout shift caused by the scrollbar appearing/disappearing when select popover is opened, this CSS may help:

```css
html {
  scrollbar-gutter: stable;
}

body {
 margin: 0 !important;
```
scrollbar-gutter: stable prevents viewport width changes when scroll locking occurs (e.g. when a select/popover opens).

⚠️ Note: When enabling scrollbar-gutter: stable, I noticed an unexpected default margin appearing on body when the select popover opens. Resetting body { margin: 0 } resolves this.
