### ISSUE TITLE
[DropdownMenu] Sub menu keep always open when click outside the browser viewport

### ISSUE THREAD

**Issue by DaanMoura** [radix-ui/primitives#2259] opened 2023-07-07 20:40 UTC
### Current Behavior

Using the DropdownMenu, with sub menus, they keep open when I click on developer tools.

![QuickTime movie](https://github.com/radix-ui/primitives/assets/26843282/6609dbb1-64f5-462b-8d8e-b2a9a0561864)

### Expected behavior

I expected to close when I click outside by default and doesn't matter where.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/p/sandbox/romantic-ben-99584h)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-dropdown-menu  |   2.0.5   |
| React            | n/a     |   18.2.0    |
| Browser          |   Arc   |    0.111.0   |
| Node             | n/a     |   v16.18.1   |
| npm/yarn         |    yarn     |   1.22.10    |
| Operating System |     macOS Ventura    |   13.4.1     |

**Comment by joaom00** [comment] 2023-07-07 20:57
Thank you for the report. The issue is already being tracked in #1441

Duplicate of #1441

**Closed** 2023-07-10 12:26 UTC
