### ISSUE TITLE
Property 'className' does not exist on type 'IntrinsicAttributes & AlertDialogPortalProps'

### ISSUE THREAD

**Issue by rafaelsilva81** [radix-ui/primitives#2410] opened 2023-09-25 18:40 UTC
### Current Behavior

The latest release of `@radix-ui/react-dialog` introduced a "bug" where the `DialogPortalProps` typing is not extending all properties from `PortalProps`. (In fact, its only extending the container property)

![image](https://github.com/radix-ui/primitives/assets/57678093/f2093c1e-0b12-4324-9828-64b4eef567f2)

### Expected behavior

Some libraries, such as [shadcn/ui](https://github.com/shadcn-ui/) rely on this typing. I'm opening this issue but I don't know if this is something that should be fixed here or there. I think portals really don't need classNames, and they probably shouldn't have, but this might break some usecases. 

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/silent-night-7n25n2)

### Suggested solution

Firstly, discuss if this is a problem that should be solved. Then if decided to solve, its a simple change on the `PortalProps` typing

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    dialog, alert-dialog     |   1.0.5 (latest)     |
| React            | n/a     |    latest   |
| Browser          |    n/a     |   n/a  |
| Node             | n/a     |    latest LTS     |
| npm/yarn         |     n/a  |     n/a    |
| Operating System |   n/a      |   n/a      |

**Comment by tecoad** [comment] 2023-09-25 18:43
I am experiencing exactly the same issue. Spend yours to realize they have changed this.

**Comment by rafaelsilva81** [comment] 2023-09-25 18:46
> I am experiencing exactly the same issue. Spend yours to realize they have changed this.

For now, removing the classname property or sticking with 1.0.4 solves the problem

**Comment by Lenghak** [comment] 2023-09-26 01:16
Not to mention that `SheetPortal` & `DialogPortal` also facing the same problem as well. I guess perhaps they find no reason to add some styles to portals at all.

**Comment by WynstelleID** [comment] 2023-09-26 05:54
<img width="710" alt="image" src="https://github.com/radix-ui/primitives/assets/58036512/9f708283-e4ee-4773-9ab9-0c8f1870bd50">
I am facing the same issue, where several portals are throwing errors, namely sheetPortal, dialogPortal, alertDialogPortal, and all of them are caused by the 'className' property.

**Comment by Lenghak** [comment] 2023-09-26 06:29
@WynstelleID you can follow this solution mentioned [here](https://github.com/shadcn-ui/ui/issues/1595).

**Comment by lachieh** [comment] 2023-09-26 12:38
This issue seems to be that this API change was labelled as a patch instead of a breaking change.
https://github.com/radix-ui/primitives/pull/2178

**Comment by Lenghak** [comment] 2023-09-26 13:58
If that is the case, perhaps they do have a reason to remove the className for portals of those components. In my opinion, mainly the portal components always stay as the background of the modals or dialogs body of which components they associates with, and most of the time it does not require much styling or does not need at styles overriding at all.

**Comment by Ansub** [comment] 2023-09-26 16:50
Experiencing the same issue.

**Comment by rafaelsilva81** [comment] 2023-09-26 18:06
> This issue seems to be that this API change was labelled as a patch instead of a breaking change.
> https://github.com/radix-ui/primitives/pull/2178

Seems to be an expected behavior and not in fact a bug. Still would like to hear from a main contributor to make sure, but I think patching the libraries and projects that use radix is going to be the alternative here.

**Comment by lachieh** [comment] 2023-09-26 21:33
Agreed that it's expected behavior, what's causing everyone to have problems is that removing type definition this is an API change and this was released as a patch. If the package version is listed in package.json with a `^` (i.e. `^1.0.0`) then npm/yarn/etc will install the latest patch version in this case `1.0.5`.

**Comment by benoitgrelard** [comment] 2023-09-27 08:25
Yes, as @lachieh is putting it, this was intentional: https://github.com/radix-ui/primitives/pull/2178
It should have been like that the whole time as `className` or all the other DOM attributes don't make sense there.

> what's causing everyone to have problems is that removing type definition this is an API change and this was released as a patch. 

We indeed, didn't realise that people might have been using them in their types even though the following is true also:

> most likely would never have been used with a className prop since it doesn't actually output anything to the DOM

> It seems that a majority of users here are coming through shadcn/ui. I've opened a PR which solves the problem against that tool: https://github.com/shadcn-ui/ui/pull/1606

It'll probably be the same for all components that re-wrap Portal (`Dialog`, `AlertDialog`, `ContextMenu`, `DropdownMenu`, `HoverCard`, `Popover`, etc)

Sorry about the confusion, versioning is hard… 😅

**Closed** 2023-09-27 08:25 UTC

**Comment by lachieh** [comment] 2023-09-27 14:49
Thanks @benoitgrelard! The Radix project and the entire team are greatly appreciated.
