### ISSUE TITLE
Accordion requires 2 clicks to collapse a panel after the first open + close. 

### ISSUE THREAD

**Issue by acc-nicholas** [radix-ui/primitives#621] opened 2021-04-26 23:31 UTC
### Current Behavior
Go to https://radix-ui.com/primitives/docs/components/accordion#basic-example
Try to open and close the accordion panels. It works correctly the first time, but subsequent attempts require 2 clicks to collapse the panel.

### Expected behavior
It should not take 2 clicks to collapse a panel.

### Reproducible example
https://radix-ui.com/primitives/docs/components/accordion#basic-example

**Comment by benoitgrelard** [comment] 2021-04-27 07:35
Hi there, we have fixed this already but it hasn't been released: https://github.com/radix-ui/primitives/pull/594

Duplicate of #593

**Closed by benoitgrelard** 2021-04-27 07:35 UTC
