### ISSUE TITLE
[Tabs] Opt-in fixed height tabs

### ISSUE THREAD

**Issue by rortan134** [radix-ui/primitives#2072] opened 2023-04-08 18:21 UTC
## Feature request

Would it be possible to expose a method to have tabs always have a min-height of the biggest tab content? Either through exposing a radix CSS variable like --radix-tabs-viewport-height and allowing the user to manually set the content min-height to it preventing variable heights and following other component's patterns, or passing a `fixedHeight` prop to the tab root.

### Overview

Before:
![opera_5qFMVRRwSo](https://user-images.githubusercontent.com/37253958/230736965-d68a51fc-0484-4b5a-bc69-d7e45e4cd468.gif)

After:
 
![opera_QjoPZxeWAc](https://user-images.githubusercontent.com/37253958/230736966-62b4c7e8-426f-4d11-9288-f92b67bf1201.gif)

### Who does this impact? Who is this for?

Essentially everyone who has a strict taste for good UX, having the entire page move feels weird.

**Comment by benoitgrelard** [comment] 2023-04-13 14:23
Duplicate of #1505

**Closed by benoitgrelard** 2023-04-13 14:23 UTC
Labels: Resolution: Duplicate, Package: react/tabs
