### ISSUE TITLE
[Accordion] initial open glitches slightly

### ISSUE THREAD

**Issue by DanielBailey-web** [radix-ui/primitives#1375] opened 2022-05-06 03:46 UTC
### Current Behavior

There is a glitch the first time an accordion is opened. It can be seen on the radix-ui website. It looks like it is not smoothly transitioning the first time it is opened. I assume that this is due to it not accurately reading the value at 0% and then it is just jumping to the value at 100%. This could very well just be a pure CSS issue, but it might also be a problem with assigning data values that I am not familiar with; However, it appears that they are all starting at data-state="closed" correctly. So I doubt this is the cause.

### Expected behavior

The accordion should open smoothly every time. But it "fails" on the first open.

### Reproducible example

[Accordion - Radix UI](https://www.radix-ui.com/docs/primitives/components/accordion)

### Additional context

It works fine on Brave (chromium-based browser).

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   accordion      |        @latest |
| React            | n/a     |    18     |
| Browser          |     Firefox & Safari    |     100 & unknown    |
| Node             | n/a     |      14.18.1   |
| npm/yarn         |    yarn     |     1.22.18    |
| Operating System |     ubuntu & iOS    |   22.04  & 15.4.1    |

**Comment by benoitgrelard** [comment] 2022-05-06 08:14
Hi @DanielBailey-web,

I can't see what the issue is on the provided link. Do you have more info?
Is it a duplicate of this? #1265

**Comment by andy-hook** [comment] 2022-05-06 08:59
> Browser | Firefox & Safari

Looks like the same issue given this constraint, I'm going to close as a dupe and we'll continue to track in https://github.com/radix-ui/primitives/issues/1265

**Closed by andy-hook** 2022-05-06 08:59 UTC
Labels: Resolution: Needs More Information, Package: react/accordion

**Comment by DanielBailey-web** [comment] 2022-05-06 21:27
@benoitgrelard Yeah it is. Sorry I missed that issue when I was looking for dups.
