### ISSUE TITLE
Is there a way to disable "Component" must be within "component" ? 

### ISSUE THREAD

**Issue by maxpaleo** [radix-ui/primitives#2679] opened 2024-02-02 03:55 UTC
## Feature request

Hi! We're using Radix within a block-based project, where UI elements are based on JSON block data. 
The UI can be moved around so that the user can put a navigation menu item within a different navbar, for example. 

Now, we keep on running into issues where, as soon as a component is "In transit," it triggers the error of the component having to be within a separate component. So when the user drags a component into another one, it immediately shows this error. 

Is there a way to disable these errors? 

<img width="839" alt="Screenshot 2024-02-01 at 7 51 33 PM" src="https://github.com/radix-ui/primitives/assets/91980500/8cac02d2-e752-4e11-8553-15a7c18a2025">

**Comment by benoitgrelard** [comment] 2024-03-08 15:07
Duplicate of #2678 where we have already answered.

**Closed by benoitgrelard** 2024-03-08 15:07 UTC
