### ISSUE TITLE
[react-dropdown-menu] Dropdown which opens a dialog not removing the pointer-events:none style

### ISSUE THREAD

**Issue by felixmosh** [radix-ui/primitives#837] opened 2021-08-30 09:05 UTC
### Current Behavior

If you open radix-ui dialog from a dropdown item, the pointer-events:none not removes, the UI becomes un clickable.

### Expected behavior

It should handle the style properly.

### Reproducible example

[Example](https://codesandbox.io/s/radix-ui-react-dropdown-menu-bug-0x5q4)
1. Click on the `Dropdown open` -> `Open dialog` item
2. Click on `cancel` / `confirm`
3. See that the `body` element remains with `pointer-events: none`

as a reference, the same code works with regular button. 
### Suggested solution

I don't know.

### Additional context

I've narrowed the issue to `@radix-ui/react-dropdown-menu` **v0.0.23**, with `v0.0.22` all works fine.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-alert-dialog    |    0.0.20     |
| Radix Package(s) |    @radix-ui/react-dropdown-menu     |    0.0.22     |
| React            | n/a     |   17.0.2      |
| Browser          |    Chrome     |   latest      |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment] 2021-08-30 09:20
Hey @felixmosh, thanks for reporting. This was fixed in #819 and will be available soon in the next release.

**Closed by benoitgrelard** 2021-08-30 09:20 UTC

**Comment by clearly-outsane** [comment] 2023-03-05 16:39
I still have this problem on the latest - I"m not sure why

**Comment by joaom00** [comment] 2023-03-05 17:02
@clearly-outsane Can you provide a sandbox?

**Comment by clearly-outsane** [comment] 2023-03-05 17:03
I'll try! I hope it's not a bug only in my project xd

**Comment by clearly-outsane** [comment] 2023-03-05 17:32
https://codesandbox.io/s/radix-ui-react-dropdown-menu-dialog-bug-nz4rg6

Here I don't know if this is the right way to have a dialog inside a dropdown but this was causing the weird behaviour.

**Comment by joaom00** [comment] 2023-03-05 18:01
It's because when you select a `DropdownMenu.Item` the `DropdownMenu.Content` is unmounted which causes the `Dialog` unmount too. To fix this you need keep `DropdownMenu.Content` open when open dialog.

Here some examples https://codesandbox.io/s/dropdownmenu-dialog-items-r9sq1q

**Comment by clearly-outsane** [comment] 2023-03-05 19:16
Oh I see! Good catch thank you :D

**Comment by mrmattrc** [comment] 2023-05-11 05:05
I have a similar use case where I need to open alert dialogs from a context menu. I forked the example and used ContextMenu (https://codesandbox.io/s/contextmenu-dialog-items-3gp329), but it does not behave the way I'd expected. When closing the dialog, the context menu reappears. How can I close the context menu when the dialog is closed?

**Comment by benoitgrelard** [comment] 2023-05-22 11:14
@mrmattrc That's because you need to ensure you use a release of `Dialog` and `ContextMenu` that are from the same batch (easiest way to always be inline is to use the latest version of each).

https://codesandbox.io/s/contextmenu-dialog-items-forked-uiyuk0?file=/src/App.js

**Comment by brettinternet** [comment] 2023-05-28 00:04
Thank you, I also recently ran into this issue and upgrading a few minor versions fixed it.

**Comment by uncvrd** [comment] 2023-06-16 20:19
> @mrmattrc That's because you need to ensure you use a release of `Dialog` and `ContextMenu` that are from the same batch (easiest way to always be inline is to use the latest version of each).
> 
> https://codesandbox.io/s/contextmenu-dialog-items-forked-uiyuk0?file=/src/App.js

Hi @benoitgrelard did the API for the ContextMenu Root component change in `2.1.4`? I no longer have the option to add an `open` prop on the `ContextMenu.Root` component which means I cannot control the closure of the context menu once an element is selected from the context menu.

Current docs don't show it as an option either: https://www.radix-ui.com/docs/primitives/components/context-menu#root

Is there a better way to handle context menu's now? Thanks a lot for your time!

**Comment by CarlosSimon02** [comment] 2024-04-21 10:30
Hi @uncvrd, I was wondering if you found a solution to the problem because I've encountered a similar situation.

**Comment by uncvrd** [comment] 2024-04-21 17:01
@CarlosSimon02 unfortunately not :(

**Comment by seleckis** [comment] 2024-05-27 16:18
I would say that this issue is still actual and the way to solve it needs to be rethought. I mean the workaround provided (checking trigger reference and comparing to focused one) is counterintuitive and poorly maintainable. We need a normal solution so that the menu closes and can trigger the opening of modal windows and other interactive elements. Preventing methods onCloseAutoFocus and onFocusOutside also don't help, Dialog opens and closes immediately. We also need a solution so that the menu can be closed programmatically later as a result of some actions.

**Comment by noahsark769** [comment] 2025-03-12 06:13
Based on https://github.com/shadcn-ui/ui/issues/1859, seems like this is still happening in March 2025 - the workaround is to make sure to specifically set the dropdown to closed _before_ triggering the dialog. See [this comment](https://github.com/shadcn-ui/ui/issues/1859#issuecomment-2434816790) for more context

**Comment by jsimonrichard** [comment] 2025-05-23 00:13
I just ran into this issue (I'm having the same problem using shadcn-ui), and I was a little confused since this issue is closed... any chance we can reopen it?

**Comment by bastiaandewaele** [comment] 2025-11-05 21:06
A quick fix that solved the issue for me was setting modal={false} on the dropdown.

```tsx
return (
  <DropdownMenu.Root modal={false}>...</DropdownMenu.Root>
)
```

> Description about the prop `modal`:
> The modality of the dropdown menu. When set to true, interaction with outside elements will be disabled and only menu content will be visible to screen readers.
> https://www.radix-ui.com/primitives/docs/components/dropdown-menu#root
