### ISSUE TITLE
Can we allow Tabs to be hidden instead of re-rendering?

### ISSUE THREAD

**Issue by kientran-clubspark** [radix-ui/primitives#1527] opened 2022-07-13 10:11 UTC
## Question

I'm using Tabs https://www.radix-ui.com/docs/primitives/components/tabs. Whenever changing tab, Content will be re-render. Is there any way to keep it in DOM (only need hide it)? Please help to support. Many thanks!

**Comment by benoitgrelard** [comment] 2022-07-13 12:00
Closing as duplicate of #1155

**Closed by benoitgrelard** 2022-07-13 12:00 UTC
Labels: Resolution: Duplicate, Package: react/tabs
