### ISSUE TITLE
[RadioGroup] Screen reader incorrectly counts the number of available radio items

### ISSUE THREAD

**Issue by dominikmlynarczyk** [radix-ui/primitives#1694] opened 2022-09-28 18:43 UTC
## Bug report

When navigating the radio buttons, the screen reader reads the wrong number of available radio items. The quantity of radio buttons is always doubled.

### Current Behavior

In the "reproducible example" below, four radio buttons/items are rendered and the screen reader suggests that there are eight radio items.

Quote from screen reader (selecting the first radio item):

>  Address, selected, radio button, **1 of 8**, Select target object, radio group.

### Expected behavior

Correctly read the number of available radio buttons; for this bug report example:

> Address, selected, radio button, **1 of 4**, Select target object, radio group.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/radix-radiogroup-screenreader-count-issue-snbo1b)

### Suggested solution

The problem seems to be generated by rendering both the `<button>` and `<input>` elements (for one radio item). When for example `<input>` elements are removed from the DOM tree , the number of elements within the radio group seems to be read correctly. 

For the example listed above, the screen reader correctly announces the number of available radio buttons:

> Address, selected, radio button, **1 of 4**, Selected target object, radio group.

[CodeSandbox - reader counts items properly](https://codesandbox.io/s/radix-radiogroup-screenreader-count-issue-without-duplication-9h6zux)

### Additional context

The problem is independent of the environment (Windows, macOS) and occurs on more readers than the VoiceOver listed in the table below.

### Your environment

| Software         | Name(s)                       | Version                                  |
| ---------------- | ----------------------------- | ---------------------------------------- |
| Radix Package(s) | `@radix-ui/react-radio-group` | 1.0.0                                    |
| React            | n/a                           | 18.0.0                                   |
| Browser          | Brave                         | 1.42.97 Chromium: 104.0.5112.102 (arm64) |
| Assistive tech   | VoiceOver                     | shipped with macOS Monterey 12.4         |
| Node             | n/a                           | 16.15                                    |
| npm/yarn         | npm                           | 8.5.5                                    |
| Operating System | macOS                         | macOS Monterey 12.4                      |

**Comment by benoitgrelard** [comment] 2022-09-28 20:48
Duplicate of #1326

**Closed by benoitgrelard** 2022-09-28 20:48 UTC
Labels: Resolution: Duplicate, Package: react/radio-group
