### ISSUE TITLE
How to stop propagation on SelectPrimitive.Item?

### ISSUE THREAD

**Issue by inje-hottestlab** [radix-ui/primitives#1700] opened 2022-10-06 08:27 UTC
## Question
Hi, I want to stop propagation click event on `SelectPrimitive.Item`.
I already checked that current `SelectPrimitive.Item` use `onPointerUp()` event to handle select event.
I tried like below, but it is not working correctly.
Please let me know how to stop propagation or fixed it if it is a bug.

```jsx
<SelectPrimitive.Item
    onPointerUp={(event) => {
        console.log('onPointerUp');
        event.stopPropagation();
    }}
    onClick={(event) => {
        console.log('onClick');
        event.stopPropagation();
    }}>
    ....
</SelectPrimitive.Item>
```

**Comment by benoitgrelard** [comment] 2022-10-10 09:01
Hi @inje-hottestlab,

What exactly are you trying to achieve?

**Comment by inje-hottestlab** [comment] 2022-10-10 09:18
@benoitgrelard 
If I click select item, the div behind the item is also clicked.
I want to stop propagation of item click event.

**Comment by benoitgrelard** [comment] 2022-10-10 09:27
Could you please provide us with a reduced test-case in codesandbox so we can take a look and determine if there's a bug somewhere?

Thanks!

**Comment by inje-hottestlab** [comment] 2022-10-10 10:48
@benoitgrelard 
I just created test-case in CodeSandbox, but I cannot reproduce the bug on it.
https://codesandbox.io/s/flamboyant-pateu-3ckit0?file=/src/App.tsx&resolutionWidth=320&resolutionHeight=675

I found that the bug is only occurred on Chrome mobile dimension mode.
Please refer to attached video.

https://user-images.githubusercontent.com/77093262/194849439-2c8cf0d8-4808-4f78-912c-42a49c68f5ee.mov

**Comment by benoitgrelard** [comment] 2022-10-10 10:53
Ah I see, in which case I will close this as a duplicate of #1658 🙂

**Closed by benoitgrelard** 2022-10-10 10:53 UTC
Labels: Resolution: Duplicate, Package: react/select
