### ISSUE TITLE
[Dialog] Add forceMount without side effect behaviour

### ISSUE THREAD

**Issue by x318** [radix-ui/primitives#2463] opened 2023-10-17 23:57 UTC
### Overview

Using `<Dialog/>`with a lot of child nodes causes >300ms freezes. It would be nice to have option to use `forceMount` (with some other probably) prop to have ability to keep whole dialog present at DOM, but without creating "focus-locks", styles on `body` and other side effects when it's closed

**Comment by benoitgrelard** [comment] 2024-03-07 10:30
Duplicate of #1155

**Closed by benoitgrelard** 2024-03-07 10:30 UTC
Labels: Resolution: Duplicate, Package: react/dialog
