### ISSUE TITLE
Dialog loses focus to body and focus guard when updating content

### ISSUE THREAD

**Issue by bolivier** [radix-ui/primitives#1981] opened 2023-02-22 21:10 UTC
### Current Behavior

When using dialog for multi-step forms, focus is sent to a span with `data-radix-focus-guard` and `body` before the first element inside the Dialog.

### Expected behavior

Non Dialog content elements should not be focused.

### Reproducible example

https://codesandbox.io/s/funny-bird-gs7tv1?file=/src/App.js

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dialog     |    1.0.2     |
| React            | n/a     |     16    |
| Browser          |      Firefox   |       110  |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |     8.5.5    |         |
| Operating System |    MacOS Ventura    |         |

**Comment by joaom00** [comment] 2023-02-22 21:28
Do you want the input to be focused when you change the step? same as when you open the dialog in the first step?

**Comment by bolivier** [comment] 2023-02-22 22:17
@joaom00 My use case (and assumption per the a11y info I've read online) is that the first input in follow up steps shouldn't be focused automatically.

But when I change the step, non dialog elements need to be tabbed through before the dialog content is active.

**Comment by benoitgrelard** [comment] 2023-02-23 10:30
Hi @bolivier, I will close this as a duplicate of #1498 as this is the same issue.

**Closed by benoitgrelard** 2023-02-23 10:30 UTC
