### ISSUE TITLE
Virtualization support for list-like components

### ISSUE THREAD

**Issue by DaniGuardiola** [radix-ui/primitives#894] opened 2021-10-07 16:44 UTC
### Overview

Virtualization of long lists for components like `DropdownMenu`.

### Examples in other libraries

MUI, `react-aria`, etc support virtualization in their components.

### Who does this impact? Who is this for?

Once the lists start getting bigger, performance can degrade pretty fast, specially on low-end devices. I think it'll be specially critical for the combobox component, which is more likely to have a large amount of items.

### Additional context

We're having performance issues in our product due to this.

**Comment by jjenzz** [comment] 2021-10-08 21:00
> For example, we have a timezone selector with a lot of entries, and they're all already loaded locally in our app.

My comment in the code probably wasn't clear but for this you would do something like:

```jsx
<DropdownMenu.Root>
	<DropdownMenu.Trigger>Open</DropdownMenu.Trigger>
	<DropdownMenu.Content>
		<Virtualized.Root     
			itemsPerPage={itemsPerPage}
			itemsCount={totalItemsLength}
			onPageLoad={(page, updateItems) => {
				const from = itemsPerPage * page;
				const items = timezones.slice(from, itemsPerPage);
				setItems(updateItems(items));
			}}
		>
			{items.map((item) => (
				<Virtualized.Item asChild key={item.id}>
					<DropdownMenu.Item>{item.label}</DropdownMenu.Item>
				</Virtualized.Item>
			))}
		</Virtualized.Root>
	</DropdownMenu.Content>
</DropdownMenu.Root>
```

The `itemsPerPage` isn't intended to mean "number of items that fit in the viewport" but rather, "number of items that you're happy for us to render at a time before we attempt to render more". Unfortunately, without that information it seems we would need to render all items first to determine how many "fit" in the viewport and then re-render to hide those that don't which wouldn't be great for perf.

**Comment by DaniGuardiola** [comment] 2021-10-11 16:40
I see. I guess what I am expecting is something more versatile like `react-window`. If you look at the examples [here](https://react-window.vercel.app/), you can see that there are many ways to approach this problem. One would be fixed size, but dynamic size is also possible by passing a setter.

Honestly I think that it could be ideal if Radix just made sure that list-like components are **compatible** with these libraries, rather than having it's own implementation -and some guides on how to compose them. Or at least have feature parity with the most common features, like being able to specify a size. Wrapping something like `react-window` in a Radix-style API is also a good option IMHO.

I think (correct me if I'm wrong) that the approach you mention is not really virtualization, but rather "infinite scrolling" (be it with a remote or local data set). Virtualization, AFAIK, is often achieved using techniques like absolute positioning so that you can render some items in the middle, and not render anything before/after that for performance. If you're not aware of the size of the items, there's no way you can reliably keep track of where the items should be and you can't unmount previous elements without messing up the visible elements' position (or doing a double-render which, as you mention, is not ideal). That means that, while at first it does help, performance would degrade the more you scroll.

Twitter is a good example of what I mean. The web app has infinite scrolling, but also virtualization. Otherwise it would be impossible to use once you have scrolled down for a while.

Ideally Radix would support both, but virtualization is more pressing for us.

**Comment by DaniGuardiola** [comment] 2021-10-11 16:49
Also relevant what you can achieve with these additional libs: https://github.com/bvaughn/react-window#related-libraries

Our use case could take advantage of some of these as well. I wonder if Radix could just make sure that these can be composed with all list-like components?

**Comment by hnordt** [comment] 2021-12-15 05:10
Very good and simple API https://github.com/petyosi/react-virtuoso

**Comment by benoitgrelard** [comment] 2022-04-05 11:46
Duplicate of #750

**Closed by benoitgrelard** 2022-04-05 11:46 UTC
Labels: Type: New Primitive
